export const AllConceptsInLargeKB = [
  String.raw `dead language`,
  String.raw `fictional species`,
  String.raw `neighborhood`,
  String.raw `family name`,
  String.raw `fictional character`,
  String.raw `jam band`,
  String.raw `urban rail transit`,
  String.raw `biography`,
  String.raw `special administrative region of China`,
  String.raw `engineering`,
  String.raw `residue`,
  String.raw `zither`,
  String.raw `science award`,
  String.raw `genre`,
  String.raw `competition`,
  String.raw `female given name`,
  String.raw `Southern rock`,
  String.raw `post-industrial music`,
  String.raw `strait`,
  String.raw `presidential system`,
  String.raw `house cat`,
  String.raw `role-playing game`,
  String.raw `soundtrack`,
  String.raw `departments of France`,
  String.raw `magnet school`,
  String.raw `Primetime Emmy Award`,
  String.raw `teacher`,
  String.raw `record label`,
  String.raw `plucked string instrument`,
  String.raw `hip hop music`,
  String.raw `theater`,
  String.raw `head of government`,
  String.raw `water area`,
  String.raw `agent`,
  String.raw `city of Pennsylvania`,
  String.raw `county of Arizona`,
  String.raw `military branch`,
  String.raw `ranking`,
  String.raw `land vehicle`,
  String.raw `school`,
  String.raw `horse`,
  String.raw `piano`,
  String.raw `free software license`,
  String.raw `human settlement`,
  String.raw `song`,
  String.raw `reserve currency`,
  String.raw `humour`,
  String.raw `property`,
  String.raw `Wikimedia list article`,
  String.raw `animated feature film`,
  String.raw `peninsula`,
  String.raw `Nazism`,
  String.raw `trance`,
  String.raw `specialty channel`,
  String.raw `research university`,
  String.raw `school district`,
  String.raw `respiratory system disease`,
  String.raw `official`,
  String.raw `Eastern Orthodox Church`,
  String.raw `genetic disease`,
  String.raw `functional programming`,
  String.raw `fictional extraterrestrial`,
  String.raw `former French region`,
  String.raw `steel guitar`,
  String.raw `county of Pennsylvania`,
  String.raw `legal institution`,
  String.raw `tabletop game`,
  String.raw `anime`,
  String.raw `county of Ireland`,
  String.raw `basketball`,
  String.raw `political philosophy`,
  String.raw `philosophy`,
  String.raw `science fiction`,
  String.raw `region of France`,
  String.raw `UK garage`,
  String.raw `MTV Video Music Award`,
  String.raw `disease`,
  String.raw `academic major`,
  String.raw `popular music`,
  String.raw `video game publisher`,
  String.raw `railway station`,
  String.raw `folk rock`,
  String.raw `Christian holy day`,
  String.raw `unsaturated fat`,
  String.raw `athlete`,
  String.raw `secretary of state`,
  String.raw `metalcore`,
  String.raw `film genre`,
  String.raw `announcer`,
  String.raw `medicine`,
  String.raw `interstellar cloud`,
  String.raw `private university`,
  String.raw `screenwriter`,
  String.raw `chemical substance`,
  String.raw `album`,
  String.raw `drum`,
  String.raw `speed skating`,
  String.raw `electronic musical instrument`,
  String.raw `special ward of Japan`,
  String.raw `physician`,
  String.raw `manga`,
  String.raw `bridge by structural type`,
  String.raw `management`,
  String.raw `vegetarianism`,
  String.raw `songwriter`,
  String.raw `Private Hochschule`,
  String.raw `road`,
  String.raw `food ingredient`,
  String.raw `belief system`,
  String.raw `contemporary R&B`,
  String.raw `Major League Baseball draft`,
  String.raw `Latin American music`,
  String.raw `independent city`,
  String.raw `monster`,
  String.raw `type of sport`,
  String.raw `feature film`,
  String.raw `woodwind instrument`,
  String.raw `arts festival`,
  String.raw `male given name`,
  String.raw `planetary system`,
  String.raw `painting`,
  String.raw `legislative term`,
  String.raw `lyricist`,
  String.raw `mathematician`,
  String.raw `emotion`,
  String.raw `pop rock`,
  String.raw `profession`,
  String.raw `historical period`,
  String.raw `colleges and universities in the United States`,
  String.raw `province of the Philippines`,
  String.raw `doctrine`,
  String.raw `fighting game`,
  String.raw `fiction`,
  String.raw `unitary authority of England`,
  String.raw `pop music`,
  String.raw `alternative rock`,
  String.raw `economic branch`,
  String.raw `musical instrument part`,
  String.raw `constituency of the Rajya Sabha`,
  String.raw `county of Texas`,
  String.raw `class of instruments`,
  String.raw `municipality of Germany`,
  String.raw `keyboard instrument`,
  String.raw `displacement`,
  String.raw `eye color`,
  String.raw `final`,
  String.raw `MTV Movie Awards`,
  String.raw `anarcho-punk`,
  String.raw `mental disorder`,
  String.raw `state of the United States`,
  String.raw `secondary school`,
  String.raw `award`,
  String.raw `liberal arts college in the United States`,
  String.raw `tool`,
  String.raw `province of the Netherlands`,
  String.raw `body fluid`,
  String.raw `state school`,
  String.raw `general officer`,
  String.raw `knowledge`,
  String.raw `film gauge`,
  String.raw `funk`,
  String.raw `type of business entity in the USA`,
  String.raw `board game`,
  String.raw `suicide`,
  String.raw `fictional profession`,
  String.raw `brass instrument`,
  String.raw `symphonic metal`,
  String.raw `art form`,
  String.raw `television presenter`,
  String.raw `newscast`,
  String.raw `outfielder`,
  String.raw `seminary`,
  String.raw `social issue`,
  String.raw `city with millions of inhabitants`,
  String.raw `keyboardist`,
  String.raw `higher education institution`,
  String.raw `programming language`,
  String.raw `abjad`,
  String.raw `association`,
  String.raw `military officer`,
  String.raw `episode`,
  String.raw `region of Italy`,
  String.raw `death metal`,
  String.raw `equity`,
  String.raw `group or class of chemical substances`,
  String.raw `drawing`,
  String.raw `speed metal`,
  String.raw `area of London`,
  String.raw `free software copyleft license`,
  String.raw `county seat`,
  String.raw `state`,
  String.raw `music genre`,
  String.raw `metropolis`,
  String.raw `monarch`,
  String.raw `programming paradigm`,
  String.raw `master's degree`,
  String.raw `financial services`,
  String.raw `bass guitar`,
  String.raw `politician`,
  String.raw `national association football team`,
  String.raw `unisex given name`,
  String.raw `architectural style`,
  String.raw `techno`,
  String.raw `punk rock`,
  String.raw `Islam`,
  String.raw `river`,
  String.raw `Indigenous peoples of the Americas`,
  String.raw `mythical creature`,
  String.raw `dynasty`,
  String.raw `family`,
  String.raw `television channel`,
  String.raw `symphonic rock`,
  String.raw `mercenary`,
  String.raw `language family`,
  String.raw `superpower`,
  String.raw `Indian people`,
  String.raw `county of Illinois`,
  String.raw `gospel music`,
  String.raw `proprietary software`,
  String.raw `problem`,
  String.raw `action game`,
  String.raw `print`,
  String.raw `republic`,
  String.raw `lawyer`,
  String.raw `theatrical genre`,
  String.raw `shooter game`,
  String.raw `double act`,
  String.raw `structured programming`,
  String.raw `college of the University of Oxford`,
  String.raw `video game`,
  String.raw `product`,
  String.raw `medical specialty`,
  String.raw `subsidiary company`,
  String.raw `ceremonial county of England`,
  String.raw `liberal arts college`,
  String.raw `version, edition, or translation`,
  String.raw `drama`,
  String.raw `symptom`,
  String.raw `stroke`,
  String.raw `cinema film format`,
  String.raw `palace`,
  String.raw `type of business entity`,
  String.raw `group of fictional characters`,
  String.raw `death`,
  String.raw `television program`,
  String.raw `census-designated place`,
  String.raw `TV production company`,
  String.raw `cause of death`,
  String.raw `political cinema`,
  String.raw `public educational institution of the United States`,
  String.raw `diabetes mellitus`,
  String.raw `impresario`,
  String.raw `thriller`,
  String.raw `software engineering`,
  String.raw `filmmaking`,
  String.raw `author`,
  String.raw `shoegazing`,
  String.raw `Academy Awards ceremony`,
  String.raw `airline`,
  String.raw `ethnic group`,
  String.raw `county of Oregon`,
  String.raw `biology`,
  String.raw `airliner`,
  String.raw `type of food or dish`,
  String.raw `corporation`,
  String.raw `crematory`,
  String.raw `pathogen`,
  String.raw `industrial music`,
  String.raw `dog`,
  String.raw `chemical element`,
  String.raw `village`,
  String.raw `pome`,
  String.raw `cult film`,
  String.raw `Indo-European languages`,
  String.raw `reggae`,
  String.raw `electric piano`,
  String.raw `coach`,
  String.raw `city of New York`,
  String.raw `wind instrument`,
  String.raw `city/town`,
  String.raw `video game developer`,
  String.raw `province of Canada`,
  String.raw `organization`,
  String.raw `natural satellite`,
  String.raw `historical fiction`,
  String.raw `Tour de France`,
  String.raw `television genre`,
  String.raw `scientist`,
  String.raw `biographical film`,
  String.raw `comics character`,
  String.raw `electronic dance music`,
  String.raw `animated series`,
  String.raw `Asian American`,
  String.raw `process`,
  String.raw `romance film`,
  String.raw `borough of Alaska`,
  String.raw `university-preparatory school`,
  String.raw `musical composition`,
  String.raw `non-metropolitan county`,
  String.raw `decimal currency`,
  String.raw `Primetime Emmy Award annual ceremony`,
  String.raw `college of the University of Cambridge`,
  String.raw `bebop`,
  String.raw `has part`,
  String.raw `non-metropolitan district`,
  String.raw `folklore`,
  String.raw `bowed string instrument`,
  String.raw `heavy metal`,
  String.raw `literary genre`,
  String.raw `town of the United States`,
  String.raw `census area of Alaska`,
  String.raw `rockabilly`,
  String.raw `declaration of independence`,
  String.raw `taxonomic rank`,
  String.raw `literature`,
  String.raw `rock`,
  String.raw `designer`,
  String.raw `amino acid`,
  String.raw `history`,
  String.raw `television film`,
  String.raw `conservatory`,
  String.raw `video game console model`,
  String.raw `bobsleigh`,
  String.raw `fantasy`,
  String.raw `house music`,
  String.raw `experimental music`,
  String.raw `jazz`,
  String.raw `island`,
  String.raw `county of Virginia`,
  String.raw `county of California`,
  String.raw `National Football League Draft`,
  String.raw `film`,
  String.raw `television comedy`,
  String.raw `county of North Carolina`,
  String.raw `humor magazine`,
  String.raw `provincial or territorial capital city in Canada`,
  String.raw `creative work`,
  String.raw `market town`,
  String.raw `method`,
  String.raw `scene`,
  String.raw `interdisciplinarity`,
  String.raw `tragedy`,
  String.raw `improvised explosive device`,
  String.raw `ball`,
  String.raw `businessperson`,
  String.raw `blues rock`,
  String.raw `sport discipline`,
  String.raw `island nation`,
  String.raw `ancient civilization`,
  String.raw `disco`,
  String.raw `enterprise`,
  String.raw `sports season`,
  String.raw `crime`,
  String.raw `role-playing video game`,
  String.raw `estate in land`,
  String.raw `manifestation`,
  String.raw `activity`,
  String.raw `politics`,
  String.raw `Golden Globe Award ceremony`,
  String.raw `physics engine`,
  String.raw `film award`,
  String.raw `high school`,
  String.raw `single-tier municipality`,
  String.raw `film production company`,
  String.raw `historical country`,
  String.raw `Golden Raspberry Awards`,
  String.raw `sex`,
  String.raw `post-hardcore`,
  String.raw `communication medium`,
  String.raw `class of chemical compounds with similar source or occurence`,
  String.raw `alphabetic script`,
  String.raw `vocal music`,
  String.raw `philosophical movement`,
  String.raw `chemical compound`,
  String.raw `television station`,
  String.raw `human`,
  String.raw `ChEBI Ontology term`,
  String.raw `film noir`,
  String.raw `concept`,
  String.raw `religious building`,
  String.raw `formula`,
  String.raw `civil and political rights`,
  String.raw `sectarian violence`,
  String.raw `psychosis`,
  String.raw `literary award`,
  String.raw `pain`,
  String.raw `tennis court`,
  String.raw `taxon`,
  String.raw `county of Michigan`,
  String.raw `soul music`,
  String.raw `natural language`,
  String.raw `city of the United States`,
  String.raw `martial arts`,
  String.raw `clinical sign`,
  String.raw `imperative programming`,
  String.raw `facility`,
  String.raw `clarinet`,
  String.raw `medication`,
  String.raw `Roman deity`,
  String.raw `independent city of Germany`,
  String.raw `member of parliament`,
  String.raw `state of India`,
  String.raw `male organism`,
  String.raw `poetry`,
  String.raw `lake`,
  String.raw `cruise ship`,
  String.raw `operating system`,
  String.raw `psychedelic rock`,
  String.raw `county of Maine`,
  String.raw `county of Florida`,
  String.raw `inner planet`,
  String.raw `written work`,
  String.raw `First Lady`,
  String.raw `writer`,
  String.raw `computer programming`,
  String.raw `diaspora`,
  String.raw `award ceremony`,
  String.raw `language`,
  String.raw `garage rock`,
  String.raw `play`,
  String.raw `group of organisms known by one particular common name`,
  String.raw `permissive free software licence`,
  String.raw `calendar month`,
  String.raw `church building`,
  String.raw `research institute`,
  String.raw `political party`,
  String.raw `learned society`,
  String.raw `national park`,
  String.raw `military rank`,
  String.raw `composer`,
  String.raw `alternative metal`,
  String.raw `short gun`,
  String.raw `contemporary folk music`,
  String.raw `voice actor`,
  String.raw `Mormonism`,
  String.raw `state of Germany`,
  String.raw `urban area of Sweden`,
  String.raw `merchant`,
  String.raw `fat`,
  String.raw `climate change`,
  String.raw `stop-motion`,
  String.raw `modern language`,
  String.raw `family of isomeric compounds`,
  String.raw `duo`,
  String.raw `music`,
  String.raw `role`,
  String.raw `art movement`,
  String.raw `optical illusion`,
  String.raw `university`,
  String.raw `food`,
  String.raw `blues`,
  String.raw `subject of international law`,
  String.raw `comedy`,
  String.raw `musical`,
  String.raw `county town`,
  String.raw `literary work`,
  String.raw `Hispanic`,
  String.raw `Indian classical music`,
  String.raw `3D film`,
  String.raw `guitar`,
  String.raw `law degree`,
  String.raw `speaker`,
  String.raw `execution method`,
  String.raw `United States presidential election`,
  String.raw `autobiography`,
  String.raw `civil war`,
  String.raw `student society`,
  String.raw `anthology series`,
  String.raw `class of award`,
  String.raw `novel`,
  String.raw `Screen Actors Guild Award`,
  String.raw `Critics' Choice Movie Award`,
  String.raw `democracy`,
  String.raw `soundtrack album`,
  String.raw `chemist`,
  String.raw `county of Ohio`,
  String.raw `unitary state`,
  String.raw `musician`,
  String.raw `pattern of behaviour`,
  String.raw `municipality of the Netherlands`,
  String.raw `crime fiction`,
  String.raw `title of Mary`,
  String.raw `island group`,
  String.raw `violin`,
  String.raw `city in New Jersey`,
  String.raw `county of Massachusetts`,
  String.raw `entertainment`,
  String.raw `new wave`,
  String.raw `broadcasting`,
  String.raw `community college`,
  String.raw `art school`,
  String.raw `Winter Olympic Games`,
  String.raw `county of Wisconsin`,
  String.raw `religious denomination`,
  String.raw `mathematics`,
  String.raw `bass`,
  String.raw `state or insular area capital in the United States`,
  String.raw `strategy video game`,
  String.raw `winger`,
  String.raw `adventure film`,
  String.raw `power pop`,
  String.raw `independent school`,
  String.raw `education`,
  String.raw `topology`,
  String.raw `law`,
  String.raw `country music`,
  String.raw `human rights`,
  String.raw `Renaissance`,
  String.raw `volleyball`,
  String.raw `natural disaster`,
  String.raw `fictional universe`,
  String.raw `mechanical wave`,
  String.raw `ethnic community`,
  String.raw `baseball team`,
  String.raw `academic degree`,
  String.raw `television series episode`,
  String.raw `Continental Congress`,
  String.raw `electronic music`,
  String.raw `empire`,
  String.raw `initialism`,
  String.raw `heritage designation`,
  String.raw `commune of France`,
  String.raw `division`,
  String.raw `museum`,
  String.raw `manner of death`,
  String.raw `boarding school`,
  String.raw `minister`,
  String.raw `television`,
  String.raw `independent record label`,
  String.raw `technology`,
  String.raw `television special`,
  String.raw `British Academy Film Awards`,
  String.raw `musical instrument`,
  String.raw `religious identity`,
  String.raw `public university`,
  String.raw `environmentalism`,
  String.raw `public office`,
  String.raw `group action`,
  String.raw `first-person shooter`,
  String.raw `medal`,
  String.raw `academic discipline`,
  String.raw `American football position`,
  String.raw `Christian music`,
  String.raw `researcher`,
  String.raw `county of Alabama`,
  String.raw `fictional government`,
  String.raw `synth-pop`,
  String.raw `electronic device`,
  String.raw `model`,
  String.raw `editorial collection`,
  String.raw `audio engineer`,
  String.raw `extracellular fluid`,
  String.raw `privately held company`,
  String.raw `restaurant`,
  String.raw `recurring event`,
  String.raw `anthology`,
  String.raw `filmmaking occupation`,
  String.raw `Christianity`,
  String.raw `therapy`,
  String.raw `rhythm and blues`,
  String.raw `saxophone`,
  String.raw `television character`,
  String.raw `zone of Nepal`,
  String.raw `academic institution`,
  String.raw `paranormal`,
  String.raw `mountain range`,
  String.raw `situation comedy`,
  String.raw `cemetery`,
  String.raw `time zone`,
  String.raw `United States Congress`,
  String.raw `baseball position`,
  String.raw `string`,
  String.raw `opera`,
  String.raw `software license`,
  String.raw `comune of Italy`,
  String.raw `homicide`,
  String.raw `industry`,
  String.raw `forward`,
  String.raw `army`,
  String.raw `Iranian musical instrument`,
  String.raw `educational institution`,
  String.raw `superhero`,
  String.raw `motor vehicle`,
  String.raw `college town`,
  String.raw `political ideology`,
  String.raw `miniseries`,
  String.raw `sea`,
  String.raw `campus`,
  String.raw `prime minister`,
  String.raw `health care`,
  String.raw `running back`,
  String.raw `artist`,
  String.raw `social movement`,
  String.raw `ice hockey team`,
  String.raw `automobile marque`,
  String.raw `business school`,
  String.raw `travel`,
  String.raw `position`,
  String.raw `Academy Awards`,
  String.raw `synthesizer`,
  String.raw `province of Spain`,
  String.raw `National Basketball Association Draft`,
  String.raw `actor`,
  String.raw `administrative territorial entity of Canada`,
  String.raw `county of Maryland`,
  String.raw `fictional energy`,
  String.raw `borough in the United Kingdom`,
  String.raw `documentary film`,
  String.raw `form of government`,
  String.raw `animation`,
  String.raw `Tagalog`,
  String.raw `cable channel`,
  String.raw `landform`,
  String.raw `bluegrass music`,
  String.raw `Protestantism`,
  String.raw `Grammy Award`,
  String.raw `Summer Olympic Games`,
  String.raw `administrative territorial entity`,
  String.raw `nationality`,
  String.raw `president`,
  String.raw `educational year`,
  String.raw `single`,
  String.raw `sound`,
  String.raw `human biblical figure`,
  String.raw `action film`,
  String.raw `judge`,
  String.raw `social group`,
  String.raw `color`,
  String.raw `national cuisine`,
  String.raw `killing`,
  String.raw `governor`,
  String.raw `orange`,
  String.raw `marriage`,
  String.raw `basketball team`,
  String.raw `Jewish people`,
  String.raw `sorority`,
  String.raw `American football team`,
  String.raw `nonprofit organization`,
  String.raw `college`,
  String.raw `professional sports team`,
  String.raw `city`,
  String.raw `rock band`,
  String.raw `capital`,
  String.raw `port city`,
  String.raw `red`,
  String.raw `film series`,
  String.raw `research`,
  String.raw `experience`,
  String.raw `avant-garde`,
  String.raw `first-level administrative country subdivision`,
  String.raw `finance minister`,
  String.raw `Unix-like operating system`,
  String.raw `private not-for-profit educational institution`,
  String.raw `social science`,
  String.raw `return specialist`,
  String.raw `law school`,
  String.raw `base material`,
  String.raw `trademark`,
  String.raw `constitutional monarchy`,
  String.raw `short film`,
  String.raw `Calvinism`,
  String.raw `energy`,
  String.raw `aircraft functional class`,
  String.raw `Malay`,
  String.raw `journalist`,
  String.raw `music scene`,
  String.raw `phenomenon`,
  String.raw `aptitude`,
  String.raw `county of New Jersey`,
  String.raw `county of Washington`,
  String.raw `thrash metal`,
  String.raw `sport`,
  String.raw `special effects`,
  String.raw `Chinese`,
  String.raw `Power Rangers`,
  String.raw `film format`,
  String.raw `newspaper`,
  String.raw `beauty contest`,
  String.raw `marine propulsion`,
  String.raw `second largest city`,
  String.raw `news`,
  String.raw `animated character`,
  String.raw `art`,
  String.raw `biological process`,
  String.raw `municipality of Portugal`,
  String.raw `prefecture of Japan`,
  String.raw `LGBT`,
  String.raw `postmodernism`,
  String.raw `county of New York`,
  String.raw `band`,
  String.raw `district with city status`,
  String.raw `entrepreneur`,
  String.raw `government`,
  String.raw `glacial lake`,
  String.raw `hardcore punk`,
  String.raw `suspension bridge`,
  String.raw `animated film`,
  String.raw `religion`,
  String.raw `jump blues`,
  String.raw `video game genre`,
  String.raw `group`,
  String.raw `studio album`,
  String.raw `film festival`,
  String.raw `melodrama`,
  String.raw `province of China`,
  String.raw `circumstellar disk`,
  String.raw `bay`,
  String.raw `infectious disease`,
  String.raw `guitarist`,
  String.raw `baroque music`,
  String.raw `rock music`,
  String.raw `transport accident`,
  String.raw `chief executive officer`,
  String.raw `mythology`,
  String.raw `province of Italy`,
  String.raw `town`,
  String.raw `drama film`,
  String.raw `star`,
  String.raw `geographic region`,
  String.raw `astronomical object type`,
  String.raw `cardiovascular disease`,
  String.raw `game show`,
  String.raw `critic`,
  String.raw `phase of life`,
  String.raw `string instrument`,
  String.raw `software`,
  String.raw `county of Indiana`,
  String.raw `private school`,
  String.raw `country`,
  String.raw `boy band`,
  String.raw `silent film`,
  String.raw `television series`,
  String.raw `physiological condition`,
  String.raw `Serbo-Croatian`,
  String.raw `marketing`,
  String.raw `corporate title`,
  String.raw `rock and roll`,
  String.raw `art exhibition`,
  String.raw `currency`,
  String.raw `progressive rock`,
  String.raw `pitcher`,
  String.raw `front`,
  String.raw `drug`,
  String.raw `performing arts`,
  String.raw `term`,
  String.raw `satire`,
  String.raw `cathedral`,
  String.raw `independent music`,
  String.raw `war`,
  String.raw `film character`,
  String.raw `hardcore`,
  String.raw `big city`,
  String.raw `association football club`,
  String.raw `fictional duck`,
  String.raw `detective fiction`,
  String.raw `media franchise`,
  String.raw `data stream`,
  String.raw `computer science`,
  String.raw `national university`,
  String.raw `metropolitan area`,
  String.raw `metropolitan borough`,
  String.raw `village in the United States`,
  String.raw `English`,
  String.raw `forest`,
  String.raw `rights`,
  String.raw `business`,
  String.raw `television network`,
  String.raw `visual artwork`,
  String.raw `anime television series`,
  String.raw `film festival edition`,
  String.raw `radio format`,
  String.raw `spirit`,
  String.raw `historical period drama`,
  String.raw `science`,
  String.raw `photograph`,
  String.raw `historic county of England`,
  String.raw `theatre award`,
  String.raw `land-grant university`,
  String.raw `foundation`,
  String.raw `designation for an administrative territorial entity`,
  String.raw `real property`,
  String.raw `chess piece`,
  String.raw `sovereign state`,
  String.raw `vice president`,
  String.raw `alphabet`,
  String.raw `fictional human`,
  String.raw `legislator`,
  String.raw `occupation`,
  String.raw `parish of Louisiana`,
  String.raw `public company`,
  String.raw `animal`
];