export const AllQualifiersInLargeKB = [
  String.raw `organization directed by the office or person`,
  String.raw `capital of`,
  String.raw `name of the character role`,
  String.raw `represented by`,
  String.raw `proxy`,
  String.raw `offset`,
  String.raw `introduced feature`,
  String.raw `has parts of the class`,
  String.raw `academic minor`,
  String.raw `number of speakers`,
  String.raw `parliamentary group`,
  String.raw `chemical formula`,
  String.raw `social classification`,
  String.raw `fee`,
  String.raw `Wikidata usage instructions`,
  String.raw `total valid votes`,
  String.raw `yard number`,
  String.raw `cost`,
  String.raw `codename`,
  String.raw `daily patronage`,
  String.raw `male population`,
  String.raw `lower limit`,
  String.raw `modified version of`,
  String.raw `cuisine`,
  String.raw `number of victims of killer`,
  String.raw `dam`,
  String.raw `Soundex`,
  String.raw `has decorative pattern`,
  String.raw `printed by`,
  String.raw `participant in`,
  String.raw `HDS ID`,
  String.raw `official color`,
  String.raw `intended public`,
  String.raw `designed by`,
  String.raw `described by source`,
  String.raw `number of matches played/races/starts`,
  String.raw `sourcing circumstances`,
  String.raw `class`,
  String.raw `total equity`,
  String.raw `input set`,
  String.raw `maintained by`,
  String.raw `audio`,
  String.raw `reason for deprecation`,
  String.raw `THL Simplified Phonetic Transcription`,
  String.raw `time of spacecraft landing`,
  String.raw `manner of death`,
  String.raw `road number`,
  String.raw `lighthouse range`,
  String.raw `street address`,
  String.raw `field of training`,
  String.raw `phase of matter`,
  String.raw `penalty`,
  String.raw `broadcast by`,
  String.raw `statement is subject of`,
  String.raw `search formatter URL`,
  String.raw `epoch`,
  String.raw `canonization status`,
  String.raw `length`,
  String.raw `light characteristic of lighthouse`,
  String.raw `student of`,
  String.raw `commissioned by`,
  String.raw `item operated`,
  String.raw `website username`,
  String.raw `conflict`,
  String.raw `earliest date`,
  String.raw `location of discovery`,
  String.raw `molecule conformation`,
  String.raw `Deutsche Bahn station category`,
  String.raw `measured physical quantity`,
  String.raw `quantity`,
  String.raw `ticker symbol`,
  String.raw `opinion joined by`,
  String.raw `qualifies for event`,
  String.raw `rector`,
  String.raw `instrumentation`,
  String.raw `narrator`,
  String.raw `oxidation state`,
  String.raw `slope`,
  String.raw `discoverer or inventor`,
  String.raw `final event`,
  String.raw `Lagrangian point`,
  String.raw `plot expanded in`,
  String.raw `opening time`,
  String.raw `input method`,
  String.raw `for work`,
  String.raw `followed by`,
  String.raw `doubles record`,
  String.raw `decay mode`,
  String.raw `protocol`,
  String.raw `name of the character role (theatre)`,
  String.raw `field of work`,
  String.raw `located on astronomical location`,
  String.raw `statistical unit`,
  String.raw `ballots cast`,
  String.raw `sports league level`,
  String.raw `structural engineer`,
  String.raw `parliamentary term`,
  String.raw `number of houses`,
  String.raw `post town`,
  String.raw `relative to`,
  String.raw `points/goal scored by`,
  String.raw `found in taxon`,
  String.raw `addressee`,
  String.raw `narrative location`,
  String.raw `sexual orientation`,
  String.raw `conversion to standard unit`,
  String.raw `image`,
  String.raw `significant place`,
  String.raw `appointed by`,
  String.raw `earthquake magnitude on the Richter magnitude scale`,
  String.raw `catalog code`,
  String.raw `contains settlement`,
  String.raw `service retirement`,
  String.raw `recorded at studio or venue`,
  String.raw `bore`,
  String.raw `date of official opening`,
  String.raw `running mate`,
  String.raw `league`,
  String.raw `comment (DEPRECATED)`,
  String.raw `International Standard Industrial Classification code Rev.4`,
  String.raw `record label`,
  String.raw `youth wing`,
  String.raw `UniProt protein ID`,
  String.raw `retrieved`,
  String.raw `regnal ordinal`,
  String.raw `open period to`,
  String.raw `MusicBrainz artist ID`,
  String.raw `International Nuclear Event Scale`,
  String.raw `guest of honor`,
  String.raw `award received`,
  String.raw `instrument`,
  String.raw `rules for classification`,
  String.raw `candidacy in election`,
  String.raw `URL`,
  String.raw `category combines topics`,
  String.raw `spatial reference system`,
  String.raw `descriptive solubility`,
  String.raw `media franchise`,
  String.raw `distribution`,
  String.raw `chord progression`,
  String.raw `has cause`,
  String.raw `killed by`,
  String.raw `cabinet`,
  String.raw `noble title`,
  String.raw `contributing factor of`,
  String.raw `source of material`,
  String.raw `described at URL`,
  String.raw `Google Maps Customer ID`,
  String.raw `school district`,
  String.raw `size of team at finish`,
  String.raw `ex taxon author`,
  String.raw `alternate names`,
  String.raw `immediate cause of`,
  String.raw `speed`,
  String.raw `McCune-Reischauer romanization`,
  String.raw `horizontal depth`,
  String.raw `category contains`,
  String.raw `collection or exhibition size`,
  String.raw `base`,
  String.raw `date of official closure`,
  String.raw `Hungarian-style transcription`,
  String.raw `number of subscribers`,
  String.raw `cast member`,
  String.raw `column`,
  String.raw `name in native language`,
  String.raw `thickness`,
  String.raw `together with`,
  String.raw `volume as quantity`,
  String.raw `part of the series`,
  String.raw `review score`,
  String.raw `in opposition to`,
  String.raw `history of topic`,
  String.raw `ancestral home`,
  String.raw `territory claimed by`,
  String.raw `electoral district`,
  String.raw `vehicle normally used`,
  String.raw `asteroid taxonomy`,
  String.raw `legislated by`,
  String.raw `author`,
  String.raw `damaged`,
  String.raw `natural product of taxon`,
  String.raw `place of publication`,
  String.raw `distinctive jersey`,
  String.raw `short name`,
  String.raw `number of parts of this work`,
  String.raw `Twitter user numeric ID`,
  String.raw `quotation or excerpt`,
  String.raw `feast day`,
  String.raw `number of survivors`,
  String.raw `taxonomic type`,
  String.raw `closed on`,
  String.raw `subsidiary`,
  String.raw `wavelength`,
  String.raw `takes place in fictional universe`,
  String.raw `codomain`,
  String.raw `part of`,
  String.raw `family`,
  String.raw `exception to constraint`,
  String.raw `numeric value`,
  String.raw `legal citation of this text`,
  String.raw `depicts`,
  String.raw `partnership with`,
  String.raw `Unicode character`,
  String.raw `level of description`,
  String.raw `political ideology`,
  String.raw `singles record`,
  String.raw `concentration`,
  String.raw `reason for preferred rank`,
  String.raw `offset from vertical`,
  String.raw `chairperson`,
  String.raw `stepparent`,
  String.raw `mouth of the watercourse`,
  String.raw `female population`,
  String.raw `substitute/deputy/replacement of office/officeholder`,
  String.raw `temporal range start`,
  String.raw `ammunition`,
  String.raw `parent astronomical body`,
  String.raw `military designation`,
  String.raw `scale`,
  String.raw `type of orbit`,
  String.raw `vertical depth`,
  String.raw `officially opened by`,
  String.raw `developer`,
  String.raw `oath of office date`,
  String.raw `country of citizenship`,
  String.raw `series ordinal`,
  String.raw `clock speed`,
  String.raw `tonality`,
  String.raw `quote`,
  String.raw `applies to jurisdiction`,
  String.raw `room number`,
  String.raw `flag`,
  String.raw `periapsis`,
  String.raw `highest point`,
  String.raw `ethnic group`,
  String.raw `volcanic explosivity index`,
  String.raw `quantity symbol (string)`,
  String.raw `OCLC control number`,
  String.raw `Caverphone`,
  String.raw `number of seasons`,
  String.raw `premiere type`,
  String.raw `light sector`,
  String.raw `number probable`,
  String.raw `fax number`,
  String.raw `located at street address (DEPRECATED)`,
  String.raw `duration`,
  String.raw `incidence`,
  String.raw `present in work`,
  String.raw `competition class`,
  String.raw `narrative role`,
  String.raw `subclass of`,
  String.raw `online service`,
  String.raw `does not have quality`,
  String.raw `vehicle range`,
  String.raw `elected in`,
  String.raw `affiliation`,
  String.raw `sponsor`,
  String.raw `type locality (geology)`,
  String.raw `focal height`,
  String.raw `source of energy`,
  String.raw `minimum number of players`,
  String.raw `uses property`,
  String.raw `sRGB color hex triplet`,
  String.raw `signatory`,
  String.raw `rural population`,
  String.raw `EThOS thesis ID`,
  String.raw `wheelchair accessibility`,
  String.raw `date of death`,
  String.raw `located in time zone`,
  String.raw `place of burial`,
  String.raw `does not have effect`,
  String.raw `external data available at`,
  String.raw `regulated by`,
  String.raw `twinned administrative body`,
  String.raw `number of representations`,
  String.raw `statement describes`,
  String.raw `court`,
  String.raw `Wikidata SPARQL query equivalent`,
  String.raw `e-mail address`,
  String.raw `stroke`,
  String.raw `national team caps`,
  String.raw `edition number`,
  String.raw `rating`,
  String.raw `commander of (DEPRECATED)`,
  String.raw `dissertation submitted to`,
  String.raw `cell component`,
  String.raw `collection`,
  String.raw `attested in`,
  String.raw `number of points/goals conceded`,
  String.raw `target`,
  String.raw `honorific prefix`,
  String.raw `field of this occupation`,
  String.raw `streaming media URL`,
  String.raw `archives at`,
  String.raw `coordinate location`,
  String.raw `file extension`,
  String.raw `dialect of`,
  String.raw `focal length`,
  String.raw `practiced by`,
  String.raw `grade of kanji`,
  String.raw `continent`,
  String.raw `writing language`,
  String.raw `director`,
  String.raw `named after`,
  String.raw `dedicated to`,
  String.raw `direction`,
  String.raw `anatomical location`,
  String.raw `drug used for treatment`,
  String.raw `replaces`,
  String.raw `frequency`,
  String.raw `properties for this type`,
  String.raw `married name`,
  String.raw `number of losses`,
  String.raw `excluding`,
  String.raw `copyright status`,
  String.raw `minimum date (property constraint)`,
  String.raw `mapping relation type`,
  String.raw `taxon name`,
  String.raw `political coalition`,
  String.raw `engine configuration`,
  String.raw `performer`,
  String.raw `of`,
  String.raw `has effect`,
  String.raw `CPU`,
  String.raw `closest approach`,
  String.raw `year of taxon publication`,
  String.raw `via`,
  String.raw `power consumed`,
  String.raw `depicted by`,
  String.raw `has part`,
  String.raw `work period (end)`,
  String.raw `constellation`,
  String.raw `edition or translation of`,
  String.raw `EU VAT number`,
  String.raw `school class`,
  String.raw `industry`,
  String.raw `spouse`,
  String.raw `refine date`,
  String.raw `personal best`,
  String.raw `operator`,
  String.raw `shape`,
  String.raw `Revised Hepburn romanization`,
  String.raw `academic major`,
  String.raw `party chief representative`,
  String.raw `official name`,
  String.raw `encoding`,
  String.raw `number of viewers/listeners`,
  String.raw `health specialty`,
  String.raw `cause of death`,
  String.raw `full work available at URL`,
  String.raw `consecrator`,
  String.raw `position held`,
  String.raw `adjacent station`,
  String.raw `brand`,
  String.raw `decays to`,
  String.raw `draft pick number`,
  String.raw `trading name`,
  String.raw `cause of destruction`,
  String.raw `start point`,
  String.raw `possible creator`,
  String.raw `anatomical branch of`,
  String.raw `funder`,
  String.raw `Cologne phonetics`,
  String.raw `sports discipline competed in`,
  String.raw `drafted by`,
  String.raw `motto text`,
  String.raw `field of view`,
  String.raw `notable work`,
  String.raw `main subject`,
  String.raw `distribution format`,
  String.raw `official website`,
  String.raw `central bank/issuer`,
  String.raw `educational stage`,
  String.raw `phone number`,
  String.raw `albedo`,
  String.raw `historic county`,
  String.raw `detail map`,
  String.raw `archive date`,
  String.raw `location of landing`,
  String.raw `cites work`,
  String.raw `armament`,
  String.raw `from narrative universe`,
  String.raw `taxon common name`,
  String.raw `destination point`,
  String.raw `floors above ground`,
  String.raw `ELSTAT geographical code`,
  String.raw `director / manager`,
  String.raw `dan/kyu rank`,
  String.raw `employer`,
  String.raw `volume`,
  String.raw `sport number`,
  String.raw `UTC date of spacecraft launch`,
  String.raw `executive producer`,
  String.raw `parent peak`,
  String.raw `media legend`,
  String.raw `broader concept`,
  String.raw `mountain range`,
  String.raw `production rate`,
  String.raw `date depicted`,
  String.raw `authority`,
  String.raw `date of assent`,
  String.raw `electoral district number`,
  String.raw `stock exchange`,
  String.raw `title in HTML`,
  String.raw `memory capacity`,
  String.raw `astronaut mission`,
  String.raw `laps completed`,
  String.raw `place served by transport hub`,
  String.raw `votes received`,
  String.raw `site of astronomical discovery`,
  String.raw `date of the first one`,
  String.raw `time of spacecraft orbit decay`,
  String.raw `symbolizes`,
  String.raw `exhibition history`,
  String.raw `partner in business or sport`,
  String.raw `subject has role`,
  String.raw `office held by head of state`,
  String.raw `published in`,
  String.raw `uncertainty corresponds to`,
  String.raw `house publication`,
  String.raw `follows`,
  String.raw `central bank`,
  String.raw `member of political party`,
  String.raw `end period`,
  String.raw `destroyed`,
  String.raw `captain`,
  String.raw `number of deaths`,
  String.raw `connecting service`,
  String.raw `author of foreword`,
  String.raw `objective of project or action`,
  String.raw `time gap`,
  String.raw `funding scheme`,
  String.raw `season`,
  String.raw `choreographer`,
  String.raw `demonym`,
  String.raw `residual stroke count`,
  String.raw `software version identifier`,
  String.raw `aircraft registration`,
  String.raw `open days`,
  String.raw `official residence`,
  String.raw `announcement date`,
  String.raw `wears`,
  String.raw `winner`,
  String.raw `operating system`,
  String.raw `MusicBrainz recording ID`,
  String.raw `member count`,
  String.raw `said to be the same as`,
  String.raw `definition domain`,
  String.raw `place of marriage`,
  String.raw `name`,
  String.raw `unmarried partner`,
  String.raw `affiliation string`,
  String.raw `order number`,
  String.raw `latest date`,
  String.raw `defendant`,
  String.raw `IPA transcription`,
  String.raw `elevation above sea level`,
  String.raw `number of draws/ties`,
  String.raw `child`,
  String.raw `attendance`,
  String.raw `UTC timezone offset`,
  String.raw `members have occupation`,
  String.raw `statutory purpose`,
  String.raw `number of works accessible online`,
  String.raw `download link`,
  String.raw `investor`,
  String.raw `disjoint union of`,
  String.raw `has immediate cause`,
  String.raw `original language of film or TV show`,
  String.raw `relative position within image`,
  String.raw `donated by`,
  String.raw `maximum size or capacity`,
  String.raw `plaintiff`,
  String.raw `culture`,
  String.raw `time of discovery or invention`,
  String.raw `voltage`,
  String.raw `edibility`,
  String.raw `Alexa rank`,
  String.raw `intangible cultural heritage status`,
  String.raw `acquisition transaction`,
  String.raw `significant environmental impact`,
  String.raw `charted in`,
  String.raw `date of the latest one`,
  String.raw `seed`,
  String.raw `earliest end date`,
  String.raw `interested in`,
  String.raw `subject item of this property`,
  String.raw `web feed URL`,
  String.raw `type of variable star`,
  String.raw `total revenue`,
  String.raw `OpenStreetMap tag or key`,
  String.raw `timezone offset`,
  String.raw `route of administration`,
  String.raw `contributor to the creative work or subject`,
  String.raw `studies`,
  String.raw `article ID`,
  String.raw `vehicle`,
  String.raw `writing system`,
  String.raw `candidate number`,
  String.raw `people or cargo transported`,
  String.raw `genre`,
  String.raw `maximum capacity`,
  String.raw `occupation`,
  String.raw `route number`,
  String.raw `IUCN conservation status`,
  String.raw `corporate officer`,
  String.raw `business division`,
  String.raw `towards`,
  String.raw `number of households`,
  String.raw `race time`,
  String.raw `score method`,
  String.raw `birth name`,
  String.raw `point of penalty`,
  String.raw `VIAF ID`,
  String.raw `streak color`,
  String.raw `media type`,
  String.raw `public key fingerprint`,
  String.raw `criterion used`,
  String.raw `code`,
  String.raw `native label`,
  String.raw `minimum value`,
  String.raw `ISBN-13`,
  String.raw `Instagram username`,
  String.raw `temperature`,
  String.raw `represents`,
  String.raw `coolant`,
  String.raw `ordered by`,
  String.raw `linear reference`,
  String.raw `cost of damage`,
  String.raw `family relationship degree`,
  String.raw `page(s)`,
  String.raw `conscription number`,
  String.raw `licence plate code`,
  String.raw `location of first performance`,
  String.raw `cardinality of this set`,
  String.raw `replaced by`,
  String.raw `Unicode hex codepoint`,
  String.raw `set in environment`,
  String.raw `is pollinator of`,
  String.raw `number of children`,
  String.raw `connecting line`,
  String.raw `languages spoken, written or signed`,
  String.raw `floruit`,
  String.raw `permanent resident of`,
  String.raw `nickname`,
  String.raw `characters`,
  String.raw `record held`,
  String.raw `production date`,
  String.raw `professorship`,
  String.raw `issued by`,
  String.raw `item of property constraint`,
  String.raw `typeface/font used`,
  String.raw `direction relative to location`,
  String.raw `end cause`,
  String.raw `maximum age`,
  String.raw `office contested`,
  String.raw `Twitter username`,
  String.raw `pennant number`,
  String.raw `Internet Archive ID`,
  String.raw `country calling code`,
  String.raw `maximum value`,
  String.raw `educated at`,
  String.raw `regular expression syntax`,
  String.raw `day in year for periodic occurrence`,
  String.raw `theme music`,
  String.raw `ISBN-10`,
  String.raw `PO Box`,
  String.raw `age at event`,
  String.raw `charge`,
  String.raw `participant`,
  String.raw `burial plot reference`,
  String.raw `chief executive officer`,
  String.raw `discontinued date`,
  String.raw `population`,
  String.raw `icon`,
  String.raw `legislative body`,
  String.raw `powered by`,
  String.raw `ranking`,
  String.raw `director of photography`,
  String.raw `OS grid reference`,
  String.raw `list of episodes`,
  String.raw `occupant`,
  String.raw `grants`,
  String.raw `general manager`,
  String.raw `office held by head of the organization`,
  String.raw `conversion to SI unit`,
  String.raw `host`,
  String.raw `relative`,
  String.raw `docking port`,
  String.raw `reference URL`,
  String.raw `number of seats`,
  String.raw `chromosome`,
  String.raw `influenced by`,
  String.raw `set in period`,
  String.raw `sports competition competed at`,
  String.raw `caliber`,
  String.raw `school of`,
  String.raw `instance of`,
  String.raw `date of burial or cremation`,
  String.raw `ICD-10`,
  String.raw `vessel class`,
  String.raw `including`,
  String.raw `located in present-day administrative territorial entity`,
  String.raw `place of birth`,
  String.raw `installed capacity`,
  String.raw `movement`,
  String.raw `spectral class`,
  String.raw `applies to name`,
  String.raw `plea`,
  String.raw `departure transaction`,
  String.raw `editor-in-chief`,
  String.raw `office held by head of government`,
  String.raw `crosses`,
  String.raw `file format`,
  String.raw `match interval`,
  String.raw `depends on software`,
  String.raw `price`,
  String.raw `voice type`,
  String.raw `terminus`,
  String.raw `work location`,
  String.raw `nighttime view`,
  String.raw `state of use`,
  String.raw `intended subject of deprecated statement`,
  String.raw `grammatical aspect`,
  String.raw `PubMed ID`,
  String.raw `foundational text`,
  String.raw `reviewed by`,
  String.raw `EHAK id`,
  String.raw `significant event`,
  String.raw `upper limit`,
  String.raw `applies to name of item`,
  String.raw `prize money`,
  String.raw `military rank`,
  String.raw `Wylie transliteration`,
  String.raw `unabbreviated text`,
  String.raw `date of first performance`,
  String.raw `TeX string`,
  String.raw `parent taxon`,
  String.raw `maximum number of players`,
  String.raw `version type`,
  String.raw `female form of label`,
  String.raw `programming language`,
  String.raw `time of earliest written record`,
  String.raw `first line`,
  String.raw `sex or gender`,
  String.raw `asteroid family`,
  String.raw `number of representatives in an organization/legislature or won in elections`,
  String.raw `structure replaces`,
  String.raw `circle of`,
  String.raw `relative humidity`,
  String.raw `last update`,
  String.raw `end time`,
  String.raw `drainage basin`,
  String.raw `number of processor cores`,
  String.raw `mean age`,
  String.raw `wingspan`,
  String.raw `apoapsis`,
  String.raw `discovery method`,
  String.raw `item disputed by`,
  String.raw `annual energy output`,
  String.raw `diameter`,
  String.raw `member category`,
  String.raw `transmitted signal type`,
  String.raw `character role`,
  String.raw `test score`,
  String.raw `call sign`,
  String.raw `position played on team / speciality`,
  String.raw `Unicode block`,
  String.raw `allegiance`,
  String.raw `Library of Congress authority ID`,
  String.raw `start period`,
  String.raw `grammatical gender`,
  String.raw `perpetrator`,
  String.raw `sport`,
  String.raw `Schl\u00E4fli symbol`,
  String.raw `contains administrative territorial entity`,
  String.raw `member of`,
  String.raw `contains`,
  String.raw `fineness`,
  String.raw `title of chess person`,
  String.raw `different from`,
  String.raw `genomic assembly`,
  String.raw `number of participants`,
  String.raw `jockey`,
  String.raw `valid in place`,
  String.raw `offers view on`,
  String.raw `solvent`,
  String.raw `IAST transliteration`,
  String.raw `statistical leader`,
  String.raw `PEGI rating`,
  String.raw `currency symbol description`,
  String.raw `pressure`,
  String.raw `location of creation`,
  String.raw `curator`,
  String.raw `successful candidate`,
  String.raw `original combination`,
  String.raw `ISRC`,
  String.raw `applies to part`,
  String.raw `title`,
  String.raw `inflows`,
  String.raw `GUI toolkit or framework`,
  String.raw `World Heritage criteria`,
  String.raw `payload mass`,
  String.raw `nominated for`,
  String.raw `test taken`,
  String.raw `residence`,
  String.raw `syntax clarification`,
  String.raw `deprecated in version`,
  String.raw `place of death`,
  String.raw `event distance`,
  String.raw `epigraph (literature)`,
  String.raw `Tibetan pinyin`,
  String.raw `significant person`,
  String.raw `stability of property value`,
  String.raw `currency`,
  String.raw `lakes on river`,
  String.raw `voice actor`,
  String.raw `number of episodes`,
  String.raw `pronunciation`,
  String.raw `language used`,
  String.raw `data size`,
  String.raw `use`,
  String.raw `locator map image`,
  String.raw `number of wins`,
  String.raw `carries`,
  String.raw `Commons category`,
  String.raw `see also`,
  String.raw `opponent during disputation`,
  String.raw `callsign of airline`,
  String.raw `military casualty classification`,
  String.raw `checksum`,
  String.raw `maximum date (property constraint)`,
  String.raw `reward`,
  String.raw `given name`,
  String.raw `total produced`,
  String.raw `physically interacts with`,
  String.raw `aspect ratio`,
  String.raw `shown with features`,
  String.raw `home venue`,
  String.raw `founded by`,
  String.raw `inception`,
  String.raw `molar volume`,
  String.raw `literal translation`,
  String.raw `manner of`,
  String.raw `statement is regarded as spoiler for`,
  String.raw `territory overlaps`,
  String.raw `presented in`,
  String.raw `licensed to broadcast to`,
  String.raw `material used`,
  String.raw `sibling`,
  String.raw `number suspected`,
  String.raw `nominated by`,
  String.raw `ISIN`,
  String.raw `highway system`,
  String.raw `subreddit`,
  String.raw `medical condition`,
  String.raw `trophy awarded`,
  String.raw `tuition fee`,
  String.raw `nomenclatural status`,
  String.raw `lowest point`,
  String.raw `partially coincident with`,
  String.raw `country`,
  String.raw `organizer`,
  String.raw `fabrication method`,
  String.raw `IPI name number`,
  String.raw `contributed to creative work`,
  String.raw `forgery after`,
  String.raw `radio format`,
  String.raw `diocese`,
  String.raw `ISO standard`,
  String.raw `speaker`,
  String.raw `BHL Page ID`,
  String.raw `transliteration`,
  String.raw `wind speed`,
  String.raw `business model`,
  String.raw `literate population`,
  String.raw `model item`,
  String.raw `HTML entity`,
  String.raw `doctoral thesis`,
  String.raw `based on`,
  String.raw `approximation algorithm`,
  String.raw `illiterate population`,
  String.raw `coach of sports team`,
  String.raw `number of pages`,
  String.raw `image of grave`,
  String.raw `event interval`,
  String.raw `NSDAP membership number (1925\u20131945)`,
  String.raw `native language`,
  String.raw `social media followers`,
  String.raw `architectural style`,
  String.raw `capital`,
  String.raw `quotation`,
  String.raw `term length of office`,
  String.raw `ISSN`,
  String.raw `producer`,
  String.raw `has quality`,
  String.raw `valid in period`,
  String.raw `facet of`,
  String.raw `uses`,
  String.raw `license`,
  String.raw `coat of arms image`,
  String.raw `number of points/goals/set scored`,
  String.raw `therapeutic area`,
  String.raw `location of formation`,
  String.raw `density`,
  String.raw `medical condition treated`,
  String.raw `date of birth`,
  String.raw `archive URL`,
  String.raw `depicted part`,
  String.raw `angular distance`,
  String.raw `approved by`,
  String.raw `removed feature`,
  String.raw `award rationale`,
  String.raw `data transfer speed`,
  String.raw `IUCN taxon ID`,
  String.raw `commanded by`,
  String.raw `instruction set`,
  String.raw `investigated by`,
  String.raw `possible treatment`,
  String.raw `military branch`,
  String.raw `studied by`,
  String.raw `applies to people`,
  String.raw `main regulatory text`,
  String.raw `copyright license`,
  String.raw `godparent`,
  String.raw `issue`,
  String.raw `structure replaced by`,
  String.raw `country of origin`,
  String.raw `content descriptor`,
  String.raw `minimum quantity`,
  String.raw `DNB editions`,
  String.raw `stated as`,
  String.raw `points awarded`,
  String.raw `product or material produced`,
  String.raw `Dewey Decimal Classification`,
  String.raw `lowest income threshold`,
  String.raw `country for sport`,
  String.raw `doctoral student`,
  String.raw `located in or next to body of water`,
  String.raw `student`,
  String.raw `editor`,
  String.raw `thermal design power`,
  String.raw `located on street`,
  String.raw `pseudonym`,
  String.raw `flag bearer`,
  String.raw `format as a regular expression`,
  String.raw `member of sports team`,
  String.raw `generational suffix`,
  String.raw `worshipped by`,
  String.raw `head coach`,
  String.raw `unveiled by`,
  String.raw `closing time`,
  String.raw `student organization of`,
  String.raw `match time of event`,
  String.raw `standards body`,
  String.raw `day of week`,
  String.raw `angle from vertical`,
  String.raw `head of government`,
  String.raw `title of broader work`,
  String.raw `separated from`,
  String.raw `Revised Romanization`,
  String.raw `has contributing factor`,
  String.raw `parent organization`,
  String.raw `follower of`,
  String.raw `named by`,
  String.raw `has edition or translation`,
  String.raw `inspired by`,
  String.raw `chapter`,
  String.raw `tributary orientation`,
  String.raw `website account on`,
  String.raw `officeholder`,
  String.raw `catalog`,
  String.raw `father`,
  String.raw `rating certificate ID`,
  String.raw `located at street address`,
  String.raw `screenwriter`,
  String.raw `Google Books ID`,
  String.raw `inventory number`,
  String.raw `space launch vehicle`,
  String.raw `hashtag`,
  String.raw `religious name`,
  String.raw `area`,
  String.raw `main building contractor`,
  String.raw `located in the ecclesiastical territorial entity`,
  String.raw `taxon author`,
  String.raw `atomic number`,
  String.raw `minimum age`,
  String.raw `teaching method`,
  String.raw `season of club or team`,
  String.raw `second family name in Spanish name`,
  String.raw `name in kana`,
  String.raw `color`,
  String.raw `conferred by`,
  String.raw `gender of a scientific name of a genus`,
  String.raw `production company`,
  String.raw `headquarters location`,
  String.raw `creator`,
  String.raw `ploidy`,
  String.raw `maximum thrust`,
  String.raw `mobile country code`,
  String.raw `diplomatic mission sent`,
  String.raw `form of creative work`,
  String.raw `heritage designation`,
  String.raw `date of baptism in early childhood`,
  String.raw `does not have part`,
  String.raw `author name string`,
  String.raw `in work`,
  String.raw `urban population`,
  String.raw `Möllendorff transliteration`,
  String.raw `victory`,
  String.raw `convicted of`,
  String.raw `relevant qualification`,
  String.raw `month of the year`,
  String.raw `religion`,
  String.raw `adjacent building`,
  String.raw `nominee`,
  String.raw `United States Armed Forces service number`,
  String.raw `soundtrack release`,
  String.raw `number of reviews/ratings`,
  String.raw `runway`,
  String.raw `game mode`,
  String.raw `software engine`,
  String.raw `Wikimedia language code`,
  String.raw `street address (DEPRECATED)`,
  String.raw `employees`,
  String.raw `object has role`,
  String.raw `constraint status`,
  String.raw `astronomical filter`,
  String.raw `official language`,
  String.raw `identifier shared with`,
  String.raw `possessed by spirit`,
  String.raw `member of military unit`,
  String.raw `applies to taxon`,
  String.raw `average speed`,
  String.raw `publication interval`,
  String.raw `defender`,
  String.raw `point in time`,
  String.raw `has facility`,
  String.raw `patronym or matronym for this person`,
  String.raw `type of kinship`,
  String.raw `is a list of`,
  String.raw `stated in`,
  String.raw `common equity tier 1 capital ratio (CETI)`,
  String.raw `participating team`,
  String.raw `shares border with`,
  String.raw `end of covered period`,
  String.raw `force`,
  String.raw `measurement scale`,
  String.raw `state of conservation`,
  String.raw `candidate`,
  String.raw `serial number`,
  String.raw `temporal range end`,
  String.raw `animal breed`,
  String.raw `directions`,
  String.raw `tributary`,
  String.raw `derivative work`,
  String.raw `admissible rule in`,
  String.raw `determination method`,
  String.raw `manufacturer`,
  String.raw `nature of statement`,
  String.raw `Gallica ID`,
  String.raw `less than`,
  String.raw `after a work by`,
  String.raw `medical evacuation to`,
  String.raw `start time`,
  String.raw `number of injured`,
  String.raw `reservoir created`,
  String.raw `applies to name of value`,
  String.raw `patron saint`,
  String.raw `doctoral advisor`,
  String.raw `legal form`,
  String.raw `dissolved, abolished or demolished`,
  String.raw `art director`,
  String.raw `operating area`,
  String.raw `place of detention`,
  String.raw `effective firing range`,
  String.raw `open period from`,
  String.raw `expected completeness`,
  String.raw `pinyin transliteration`,
  String.raw `pronunciation variety`,
  String.raw `presenter`,
  String.raw `reports periodicity`,
  String.raw `co-driver`,
  String.raw `publication date`,
  String.raw `orientation`,
  String.raw `stated age at event`,
  String.raw `chivalric order`,
  String.raw `original network`,
  String.raw `handedness`,
  String.raw `owned by`,
  String.raw `number of platform tracks`,
  String.raw `retirement age`,
  String.raw `used by`,
  String.raw `highest income threshold`,
  String.raw `origin of the watercourse`,
  String.raw `track gauge`,
  String.raw `filming location`,
  String.raw `measures`,
  String.raw `number of cylinders`,
  String.raw `platform`,
  String.raw `effective date`,
  String.raw `unit symbol`,
  String.raw `home port`,
  String.raw `terminus location`,
  String.raw `mass`,
  String.raw `work period (start)`,
  String.raw `victim`,
  String.raw `radius`,
  String.raw `connects with`,
  String.raw `original spelling`,
  String.raw `hair color`,
  String.raw `diplomatic relation`,
  String.raw `interactive elements`,
  String.raw `time in space`,
  String.raw `OSM tag or key`,
  String.raw `executive body`,
  String.raw `subtitle`,
  String.raw `IIIF manifest`,
  String.raw `composer`,
  String.raw `height`,
  String.raw `head of state`,
  String.raw `mother`,
  String.raw `identity of subject in context`,
  String.raw `owner of`,
  String.raw `complies with`,
  String.raw `statement supported by`,
  String.raw `judge`,
  String.raw `political party`,
  String.raw `samples from work`,
  String.raw `proportion`,
  String.raw `section, verse, paragraph, or clause`,
  String.raw `hyphenation`,
  String.raw `calculated from`,
  String.raw `key performance indicator`,
  String.raw `indigenous to`,
  String.raw `cover art by`,
  String.raw `basic form of government`,
  String.raw `translator`,
  String.raw `points for`,
  String.raw `symptoms`,
  String.raw `collection creator`,
  String.raw `topographic prominence`,
  String.raw `property`,
  String.raw `afflicts`,
  String.raw `laws applied`,
  String.raw `number of works`,
  String.raw `publisher`,
  String.raw `stage classification`,
  String.raw `review score by`,
  String.raw `public domain date`,
  String.raw `fleet or registration number`,
  String.raw `architect`,
  String.raw `width`,
  String.raw `greater than`,
  String.raw `year of taxon name publication`,
  String.raw `musical conductor`,
  String.raw `academic degree`,
  String.raw `hydraulic head`,
  String.raw `quotes work`,
  String.raw `location`,
  String.raw `religious order`,
  String.raw `incertae sedis`,
  String.raw `mascot`,
  String.raw `Wikidata property`,
  String.raw `located in the administrative territorial entity`,
  String.raw `ISO 9:1995`,
  String.raw `size of team at start`,
  String.raw `identity of object in context`,
  String.raw `expression, gesture or body pose`,
  String.raw `DOI`,
  String.raw `based on heuristic`,
  String.raw `flight number`,
  String.raw `time period`,
  String.raw `sitter`,
  String.raw `inscription`,
  String.raw `habitat`,
  String.raw `lyrics by`,
  String.raw `original broadcaster`,
  String.raw `taxon rank`,
  String.raw `IMDb ID`,
  String.raw `sports season of league or competition`,
  String.raw `ISO 639-3 code`,
  String.raw `SOC Code (2010)`,
  String.raw `throughput`,
  String.raw `street key`,
  String.raw `FAA airport code`,
  String.raw `stage reached`,
  String.raw `video`,
  String.raw `location of the point of view`,
  String.raw `family name`,
  String.raw `street number`,
  String.raw `service entry`,
  String.raw `latest start date`,
  String.raw `adapted by`,
  String.raw `manifestation of`,
  String.raw `results`,
  String.raw `watershed area`,
  String.raw `postal code`,
  String.raw `located on terrain feature`,
  String.raw `number confirmed`,
  String.raw `floor number`,
  String.raw `station code`,
  String.raw `incarnation of`,
  String.raw `workshop of`,
  String.raw `language of work or name`,
  String.raw `M\u00F6llendorff transliteration`,
  String.raw `crew member`,
  String.raw `start of covered period`,
  String.raw `commemorates`,
  String.raw `has edition`,
  String.raw `Brazilian municipality code`,
  String.raw `statement disputed by`,
  String.raw `partition table type`,
  String.raw `time index`,
  String.raw `named as`,
  String.raw `newspaper format`,
  String.raw `distributed by`,
  String.raw `distance from river mouth`,
  String.raw `copyright holder`,
  String.raw `vocalized name`
];