export const AllRelationsInLargeKB = [
  String.raw `capital of`,
  String.raw `organization directed by the office or person`,
  String.raw `supercharger`,
  String.raw `model year`,
  String.raw `represented by`,
  String.raw `proxy`,
  String.raw `introduced feature`,
  String.raw `has parts of the class`,
  String.raw `academic minor`,
  String.raw `social classification`,
  String.raw `parliamentary group`,
  String.raw `symbol of`,
  String.raw `repealed by`,
  String.raw `acknowledged`,
  String.raw `proved by`,
  String.raw `dam`,
  String.raw `emergency phone number`,
  String.raw `metrically compatible typeface`,
  String.raw `modified version of`,
  String.raw `cuisine`,
  String.raw `has decorative pattern`,
  String.raw `encoded by`,
  String.raw `muscle action`,
  String.raw `colonel-in-chief`,
  String.raw `merged into`,
  String.raw `participant in`,
  String.raw `printed by`,
  String.raw `intended public`,
  String.raw `designed by`,
  String.raw `described by source`,
  String.raw `commander of`,
  String.raw `input set`,
  String.raw `maintained by`,
  String.raw `manner of death`,
  String.raw `tempo marking`,
  String.raw `penalty`,
  String.raw `geography of topic`,
  String.raw `film distribute region`,
  String.raw `broadcast by`,
  String.raw `statement is subject of`,
  String.raw `film editor`,
  String.raw `works in collection`,
  String.raw `software quality assurance`,
  String.raw `tussenvoegsel`,
  String.raw `epoch`,
  String.raw `canonization status`,
  String.raw `type of electrification`,
  String.raw `commissioned by`,
  String.raw `student of`,
  String.raw `item operated`,
  String.raw `by-product`,
  String.raw `conflict`,
  String.raw `gender inflection of surname`,
  String.raw `location of discovery`,
  String.raw `station class`,
  String.raw `launch contractor`,
  String.raw `fandom`,
  String.raw `partner`,
  String.raw `lymphatic drainage`,
  String.raw `measured physical quantity`,
  String.raw `side effect`,
  String.raw `monomer of`,
  String.raw `rector`,
  String.raw `instrumentation`,
  String.raw `narrator`,
  String.raw `final event`,
  String.raw `discoverer or inventor`,
  String.raw `plot expanded in`,
  String.raw `basionym`,
  String.raw `received signal type`,
  String.raw `honorific suffix`,
  String.raw `for work`,
  String.raw `followed by`,
  String.raw `structural engineer`,
  String.raw `statistical unit`,
  String.raw `antiparticle`,
  String.raw `protocol`,
  String.raw `field of work`,
  String.raw `located on astronomical location`,
  String.raw `enclave within`,
  String.raw `type foundry`,
  String.raw `parliamentary term`,
  String.raw `relative to`,
  String.raw `points/goal scored by`,
  String.raw `found in taxon`,
  String.raw `addressee`,
  String.raw `narrative location`,
  String.raw `parish church`,
  String.raw `inflorescence`,
  String.raw `sexual orientation`,
  String.raw `mount`,
  String.raw `significant place`,
  String.raw `appointed by`,
  String.raw `coat of arms`,
  String.raw `contains settlement`,
  String.raw `recorded at studio or venue`,
  String.raw `backup or reserve team or crew`,
  String.raw `running mate`,
  String.raw `designed to carry`,
  String.raw `parent cell line`,
  String.raw `league`,
  String.raw `scheduled service destination`,
  String.raw `record label`,
  String.raw `has active ingredient`,
  String.raw `first aid measures`,
  String.raw `youth wing`,
  String.raw `test method`,
  String.raw `elector`,
  String.raw `has melody`,
  String.raw `conjugate acid`,
  String.raw `home world`,
  String.raw `guest of honor`,
  String.raw `established from medical condition`,
  String.raw `award received`,
  String.raw `instrument`,
  String.raw `muscle origin`,
  String.raw `candidacy in election`,
  String.raw `theorised by`,
  String.raw `spatial reference system`,
  String.raw `media franchise`,
  String.raw `distribution`,
  String.raw `has phenotype`,
  String.raw `has cause`,
  String.raw `chord progression`,
  String.raw `significant drug interaction`,
  String.raw `killed by`,
  String.raw `noble title`,
  String.raw `contributing factor of`,
  String.raw `source of material`,
  String.raw `school district`,
  String.raw `EC enzyme classification`,
  String.raw `implementation of`,
  String.raw `immediate cause of`,
  String.raw `category contains`,
  String.raw `asteroid spectral type`,
  String.raw `supported sports team`,
  String.raw `revival or touring version of`,
  String.raw `film regional debut venue`,
  String.raw `sound designer`,
  String.raw `overrules`,
  String.raw `demonym of`,
  String.raw `organized response related to outbreak`,
  String.raw `study type`,
  String.raw `cast member`,
  String.raw `in opposition to`,
  String.raw `together with`,
  String.raw `history of topic`,
  String.raw `part of the series`,
  String.raw `country of registry`,
  String.raw `ancestral home`,
  String.raw `territory claimed by`,
  String.raw `electoral district`,
  String.raw `has anatomical branch`,
  String.raw `vehicle normally used`,
  String.raw `debut participant`,
  String.raw `legislated by`,
  String.raw `author`,
  String.raw `damaged`,
  String.raw `primary note`,
  String.raw `natural product of taxon`,
  String.raw `place of publication`,
  String.raw `appears in the form of`,
  String.raw `chassis`,
  String.raw `feast day`,
  String.raw `taxonomic type`,
  String.raw `subsidiary`,
  String.raw `closed on`,
  String.raw `had as last meal`,
  String.raw `exported to`,
  String.raw `codomain`,
  String.raw `part of`,
  String.raw `family`,
  String.raw `political ideology`,
  String.raw `patron saint`,
  String.raw `takes place in fictional universe`,
  String.raw `depicts`,
  String.raw `partnership with`,
  String.raw `colorist`,
  String.raw `is pollinator of`,
  String.raw `manner of inhumane treatment`,
  String.raw `level of description`,
  String.raw `recommended unit of measurement`,
  String.raw `vaccine for`,
  String.raw `chairperson`,
  String.raw `stepparent`,
  String.raw `mouth of the watercourse`,
  String.raw `substitute/deputy/replacement of office/officeholder`,
  String.raw `parent astronomical body`,
  String.raw `ammunition`,
  String.raw `temporal range start`,
  String.raw `superpartner of`,
  String.raw `medical treatment`,
  String.raw `Code of nomenclature`,
  String.raw `type of orbit`,
  String.raw `officially opened by`,
  String.raw `relegated`,
  String.raw `enemy of`,
  String.raw `developer`,
  String.raw `natural reservoir of`,
  String.raw `choral conductor`,
  String.raw `type of rear suspension`,
  String.raw `airline alliance`,
  String.raw `country of citizenship`,
  String.raw `election called by`,
  String.raw `landscape architect`,
  String.raw `microstructure`,
  String.raw `has evaluation`,
  String.raw `referee`,
  String.raw `perfume note`,
  String.raw `tonality`,
  String.raw `located in protected area`,
  String.raw `applies to jurisdiction`,
  String.raw `Sandbox-Item`,
  String.raw `flag`,
  String.raw `train depot`,
  String.raw `highest point`,
  String.raw `ethnic group`,
  String.raw `premiere type`,
  String.raw `airline hub`,
  String.raw `assistant director`,
  String.raw `eligible recipient`,
  String.raw `by-product of`,
  String.raw `original film format`,
  String.raw `stereoisomer of`,
  String.raw `language style`,
  String.raw `space tug`,
  String.raw `present in work`,
  String.raw `competition class`,
  String.raw `narrative role`,
  String.raw `online service`,
  String.raw `affiliation`,
  String.raw `elected in`,
  String.raw `sponsor`,
  String.raw `type locality (geology)`,
  String.raw `source of energy`,
  String.raw `signatory`,
  String.raw `Fach`,
  String.raw `tracklist`,
  String.raw `located in time zone`,
  String.raw `real estate developer`,
  String.raw `place of burial`,
  String.raw `used metre`,
  String.raw `does not have effect`,
  String.raw `regulated by`,
  String.raw `twinned administrative body`,
  String.raw `statement describes`,
  String.raw `court`,
  String.raw `output method`,
  String.raw `underlies`,
  String.raw `Scandinavian middle family name`,
  String.raw `dissertation submitted to`,
  String.raw `typing discipline`,
  String.raw `commander of (DEPRECATED)`,
  String.raw `cell component`,
  String.raw `legislative committee`,
  String.raw `rating`,
  String.raw `collection`,
  String.raw `target`,
  String.raw `attested in`,
  String.raw `honorific prefix`,
  String.raw `field of this occupation`,
  String.raw `dialect of`,
  String.raw `archives at`,
  String.raw `positive diagnostic predictor`,
  String.raw `grade of kanji`,
  String.raw `practiced by`,
  String.raw `continent`,
  String.raw `writing language`,
  String.raw `director`,
  String.raw `style of karate`,
  String.raw `supervised by`,
  String.raw `interchange station`,
  String.raw `named after`,
  String.raw `key col`,
  String.raw `dedicated to`,
  String.raw `direction`,
  String.raw `pendant of`,
  String.raw `drug used for treatment`,
  String.raw `expression of`,
  String.raw `replaces`,
  String.raw `properties for this type`,
  String.raw `professional name (Japan)`,
  String.raw `GPU`,
  String.raw `copyright status`,
  String.raw `volcano observatory`,
  String.raw `tautomer of`,
  String.raw `replaced synonym (for nom. nov.)`,
  String.raw `excluding`,
  String.raw `decay mode`,
  String.raw `maintenance method`,
  String.raw `secretary general`,
  String.raw `political coalition`,
  String.raw `engine configuration`,
  String.raw `performer`,
  String.raw `has effect`,
  String.raw `CPU`,
  String.raw `of`,
  String.raw `raga`,
  String.raw `given name version for other gender`,
  String.raw `via`,
  String.raw `language regulatory body`,
  String.raw `depicted by`,
  String.raw `has part`,
  String.raw `edition or translation of`,
  String.raw `constellation`,
  String.raw `this taxon is source of`,
  String.raw `has tense`,
  String.raw `Roman nomen gentilicium`,
  String.raw `produced by`,
  String.raw `industry`,
  String.raw `fuel system`,
  String.raw `active ingredient in`,
  String.raw `spouse`,
  String.raw `member of the deme`,
  String.raw `peak bagging classification`,
  String.raw `operator`,
  String.raw `nutrient`,
  String.raw `shape`,
  String.raw `academic major`,
  String.raw `party chief representative`,
  String.raw `health specialty`,
  String.raw `fictional universe described in`,
  String.raw `cause of death`,
  String.raw `accredited by`,
  String.raw `consecrator`,
  String.raw `position held`,
  String.raw `next lower rank`,
  String.raw `adjacent station`,
  String.raw `brand`,
  String.raw `fossil found in this unit`,
  String.raw `decays to`,
  String.raw `classification of race`,
  String.raw `moved by`,
  String.raw `cause of destruction`,
  String.raw `start point`,
  String.raw `electrical plug type`,
  String.raw `anatomical branch of`,
  String.raw `possible creator`,
  String.raw `funder`,
  String.raw `writable file format`,
  String.raw `sports discipline competed in`,
  String.raw `age of onset`,
  String.raw `drafted by`,
  String.raw `notable work`,
  String.raw `main subject`,
  String.raw `distribution format`,
  String.raw `central bank/issuer`,
  String.raw `educational stage`,
  String.raw `next higher rank`,
  String.raw `director/manager`,
  String.raw `cites work`,
  String.raw `location of landing`,
  String.raw `from narrative universe`,
  String.raw `armament`,
  String.raw `list of characters`,
  String.raw `is recto of`,
  String.raw `worn by`,
  String.raw `destination point`,
  String.raw `parent club`,
  String.raw `update method`,
  String.raw `director / manager`,
  String.raw `academic appointment`,
  String.raw `dan/kyu rank`,
  String.raw `employer`,
  String.raw `geographic distribution`,
  String.raw `notation`,
  String.raw `executive producer`,
  String.raw `parent peak`,
  String.raw `fastest lap`,
  String.raw `mountain range`,
  String.raw `authority`,
  String.raw `music video`,
  String.raw `port of registry`,
  String.raw `stock exchange`,
  String.raw `prime factor`,
  String.raw `dialect of computer language`,
  String.raw `astronaut mission`,
  String.raw `place served by transport hub`,
  String.raw `display technology`,
  String.raw `designated as terrorist by`,
  String.raw `has natural reservoir`,
  String.raw `site of astronomical discovery`,
  String.raw `exhibition history`,
  String.raw `symbolizes`,
  String.raw `partner in business or sport`,
  String.raw `subject has role`,
  String.raw `copyright status as a creator`,
  String.raw `office held by head of state`,
  String.raw `published in`,
  String.raw `house publication`,
  String.raw `follows`,
  String.raw `central bank`,
  String.raw `member of political party`,
  String.raw `end period`,
  String.raw `destroyed`,
  String.raw `captain`,
  String.raw `strand orientation`,
  String.raw `connecting service`,
  String.raw `author of foreword`,
  String.raw `objective of project or action`,
  String.raw `funding scheme`,
  String.raw `season`,
  String.raw `award disciplines or subjects`,
  String.raw `choreographer`,
  String.raw `place of devotion`,
  String.raw `first attested from`,
  String.raw `symptom of`,
  String.raw `official residence`,
  String.raw `coextensive with`,
  String.raw `open days`,
  String.raw `crystal system`,
  String.raw `fictional analog of`,
  String.raw `wears`,
  String.raw `winner`,
  String.raw `operating system`,
  String.raw `superhuman feature or ability`,
  String.raw `patient of`,
  String.raw `said to be the same as`,
  String.raw `definition domain`,
  String.raw `unmarried partner`,
  String.raw `input method`,
  String.raw `presented in`,
  String.raw `sports season of league or competition`,
  String.raw `defendant`,
  String.raw `members have occupation`,
  String.raw `child`,
  String.raw `pole position`,
  String.raw `supports programming language`,
  String.raw `political alignment`,
  String.raw `has column`,
  String.raw `readable file format`,
  String.raw `investor`,
  String.raw `teams classification by time`,
  String.raw `league system`,
  String.raw `interleaves with`,
  String.raw `foods traditionally associated`,
  String.raw `disjoint union of`,
  String.raw `has immediate cause`,
  String.raw `BBFC rating`,
  String.raw `original language of film or TV show`,
  String.raw `culture`,
  String.raw `donated by`,
  String.raw `plaintiff`,
  String.raw `mode of inheritance`,
  String.raw `filmography`,
  String.raw `film script`,
  String.raw `edibility`,
  String.raw `famous people`,
  String.raw `type of water supply`,
  String.raw `intangible cultural heritage status`,
  String.raw `significant environmental impact`,
  String.raw `charted in`,
  String.raw `interested in`,
  String.raw `spore print color`,
  String.raw `innervated by`,
  String.raw `invasive to`,
  String.raw `primary destinations`,
  String.raw `crystal habit`,
  String.raw `author of afterword`,
  String.raw `contributor to the creative work or subject`,
  String.raw `route of administration`,
  String.raw `studies`,
  String.raw `vehicle`,
  String.raw `has pet`,
  String.raw `writing system`,
  String.raw `professional or sports partner`,
  String.raw `cites`,
  String.raw `people or cargo transported`,
  String.raw `interests`,
  String.raw `genre`,
  String.raw `IUCN conservation status`,
  String.raw `occupation`,
  String.raw `segmental innervation`,
  String.raw `towards`,
  String.raw `business division`,
  String.raw `corporate officer`,
  String.raw `streak color`,
  String.raw `sexually homologous with`,
  String.raw `list of monuments`,
  String.raw `supervisory board member`,
  String.raw `exclave of`,
  String.raw `fault`,
  String.raw `has grammatical case`,
  String.raw `represents`,
  String.raw `arterial supply`,
  String.raw `coolant`,
  String.raw `ordered by`,
  String.raw `distributary`,
  String.raw `Han character in this lexeme`,
  String.raw `Catholic rite`,
  String.raw `depositor`,
  String.raw `location of first performance`,
  String.raw `cardinality of this set`,
  String.raw `replaced by`,
  String.raw `network bands`,
  String.raw `set in environment`,
  String.raw `UNESCO language status`,
  String.raw `connecting line`,
  String.raw `languages spoken, written or signed`,
  String.raw `permanent resident of`,
  String.raw `requires grammatical feature`,
  String.raw `characters`,
  String.raw `record held`,
  String.raw `activity policy in this place`,
  String.raw `professorship`,
  String.raw `programming paradigm`,
  String.raw `issued by`,
  String.raw `typeface/font used`,
  String.raw `direction relative to location`,
  String.raw `found`,
  String.raw `location of final assembly`,
  String.raw `Vox-ATypI classification`,
  String.raw `end cause`,
  String.raw `draft pick from school`,
  String.raw `office contested`,
  String.raw `illustrator`,
  String.raw `polymer of`,
  String.raw `located on linear feature`,
  String.raw `educated at`,
  String.raw `theme music`,
  String.raw `day in year for periodic occurrence`,
  String.raw `conjugate base`,
  String.raw `seed team`,
  String.raw `highest note`,
  String.raw `charge`,
  String.raw `participant`,
  String.raw `parent of this hybrid, breed, or cultivar`,
  String.raw `chief executive officer`,
  String.raw `activating neurotransmitter`,
  String.raw `list of episodes`,
  String.raw `legislative body`,
  String.raw `powered by`,
  String.raw `director of photography`,
  String.raw `occupant`,
  String.raw `grants`,
  String.raw `day of regular release`,
  String.raw `general manager`,
  String.raw `office held by head of the organization`,
  String.raw `host`,
  String.raw `covered period`,
  String.raw `relative`,
  String.raw `set in period`,
  String.raw `lake outflow`,
  String.raw `chromosome`,
  String.raw `docking port`,
  String.raw `influenced by`,
  String.raw `sports competition competed at`,
  String.raw `climbing route`,
  String.raw `has listed ingredient`,
  String.raw `avionics`,
  String.raw `school of`,
  String.raw `vessel class`,
  String.raw `including`,
  String.raw `presynaptic connection`,
  String.raw `surface played on`,
  String.raw `located in present-day administrative territorial entity`,
  String.raw `place of birth`,
  String.raw `video system`,
  String.raw `movement`,
  String.raw `plea`,
  String.raw `generalization of`,
  String.raw `crosses`,
  String.raw `office held by head of government`,
  String.raw `film crew member`,
  String.raw `editor-in-chief`,
  String.raw `file format`,
  String.raw `corrigendum / erratum`,
  String.raw `amended by`,
  String.raw `reference vocabulary`,
  String.raw `motto`,
  String.raw `depends on software`,
  String.raw `public holiday`,
  String.raw `terminus`,
  String.raw `voice type`,
  String.raw `work location`,
  String.raw `endorsed by`,
  String.raw `state of use`,
  String.raw `foundational text`,
  String.raw `reviewed by`,
  String.raw `interaction`,
  String.raw `venous drainage`,
  String.raw `is metaclass for`,
  String.raw `significant event`,
  String.raw `combination classification`,
  String.raw `public transport stop`,
  String.raw `military rank`,
  String.raw `official symbol`,
  String.raw `official color`,
  String.raw `office held by head of the organisation`,
  String.raw `parent taxon`,
  String.raw `programming language`,
  String.raw `references work, tradition or theory`,
  String.raw `reward program`,
  String.raw `sex or gender`,
  String.raw `asteroid family`,
  String.raw `end grade`,
  String.raw `structure replaces`,
  String.raw `is verso of`,
  String.raw `circle of`,
  String.raw `cathedral`,
  String.raw `located in the statistical territorial entity`,
  String.raw `drainage basin`,
  String.raw `game artist`,
  String.raw `voting system`,
  String.raw `lifestyle`,
  String.raw `discovery method`,
  String.raw `item disputed by`,
  String.raw `transmitted signal type`,
  String.raw `member category`,
  String.raw `development of anatomical structure`,
  String.raw `character role`,
  String.raw `recovered by`,
  String.raw `innervates`,
  String.raw `category for alumni of educational institution`,
  String.raw `position played on team / speciality`,
  String.raw `carries scientific instrument`,
  String.raw `ambitus`,
  String.raw `Unicode block`,
  String.raw `allegiance`,
  String.raw `motif represents`,
  String.raw `perpetrator`,
  String.raw `start period`,
  String.raw `sport`,
  String.raw `takeoff and landing capability`,
  String.raw `enclosure`,
  String.raw `contains administrative territorial entity`,
  String.raw `league points system`,
  String.raw `glacier status`,
  String.raw `member of`,
  String.raw `contains`,
  String.raw `copyright representative`,
  String.raw `main food source`,
  String.raw `title of chess person`,
  String.raw `different from`,
  String.raw `copyright exemption`,
  String.raw `film release region`,
  String.raw `valid in place`,
  String.raw `offers view on`,
  String.raw `recording location`,
  String.raw `ICTV virus genome composition`,
  String.raw `season starts`,
  String.raw `statistical leader`,
  String.raw `PEGI rating`,
  String.raw `currency symbol description`,
  String.raw `location of creation`,
  String.raw `curator`,
  String.raw `successful candidate`,
  String.raw `means of locomotion`,
  String.raw `original combination`,
  String.raw `first appearance`,
  String.raw `applies to part`,
  String.raw `recording or performance of`,
  String.raw `Ethnologue language status`,
  String.raw `inflows`,
  String.raw `GUI toolkit or framework`,
  String.raw `may prevent`,
  String.raw `wing configuration`,
  String.raw `World Heritage criteria`,
  String.raw `nominated for`,
  String.raw `name day`,
  String.raw `test taken`,
  String.raw `residence`,
  String.raw `emulates`,
  String.raw `totem`,
  String.raw `deprecated in version`,
  String.raw `has works in the collection`,
  String.raw `place of death`,
  String.raw `research intervention`,
  String.raw `mandates`,
  String.raw `significant person`,
  String.raw `soundtrack album`,
  String.raw `type locality (biology)`,
  String.raw `costume designer`,
  String.raw `reads environment variable`,
  String.raw `radix`,
  String.raw `phase point`,
  String.raw `currency`,
  String.raw `advertises`,
  String.raw `programmer`,
  String.raw `genetic association`,
  String.raw `prerequisite`,
  String.raw `lakes on river`,
  String.raw `voice actor`,
  String.raw `stock market index`,
  String.raw `comorbidity`,
  String.raw `military conflicts`,
  String.raw `language used`,
  String.raw `use`,
  String.raw `opposite of`,
  String.raw `appears in the heritage monument list`,
  String.raw `carries`,
  String.raw `league level above`,
  String.raw `animator`,
  String.raw `mod of`,
  String.raw `biosafety level`,
  String.raw `color produced`,
  String.raw `associated electoral district`,
  String.raw `military casualty classification`,
  String.raw `serving temperature`,
  String.raw `reward`,
  String.raw `given name`,
  String.raw `template's main topic`,
  String.raw `linguistic typology`,
  String.raw `physically interacts with`,
  String.raw `hydrated form of`,
  String.raw `has boundary`,
  String.raw `study or design for`,
  String.raw `mirrors data from`,
  String.raw `organisation directed from the office or person`,
  String.raw `best combative classification`,
  String.raw `basin country`,
  String.raw `aspect ratio`,
  String.raw `official religion`,
  String.raw `home venue`,
  String.raw `promoted`,
  String.raw `founded by`,
  String.raw `microarchitecture`,
  String.raw `ratified by`,
  String.raw `territory overlaps`,
  String.raw `licensed to broadcast to`,
  String.raw `sibling`,
  String.raw `material used`,
  String.raw `nominated by`,
  String.raw `highway system`,
  String.raw `medical condition`,
  String.raw `trophy awarded`,
  String.raw `vice-county`,
  String.raw `lowest point`,
  String.raw `endemic to`,
  String.raw `partially coincident with`,
  String.raw `projection designer`,
  String.raw `organizer`,
  String.raw `country`,
  String.raw `contributed to creative work`,
  String.raw `radio format`,
  String.raw `fabrication method`,
  String.raw `board member`,
  String.raw `image of function`,
  String.raw `diocese`,
  String.raw `speaker`,
  String.raw `time signature`,
  String.raw `species kept`,
  String.raw `Roman praenomen`,
  String.raw `business model`,
  String.raw `antagonist muscle`,
  String.raw `model item`,
  String.raw `reply to`,
  String.raw `is proceedings from`,
  String.raw `source of income`,
  String.raw `discography`,
  String.raw `external auditor`,
  String.raw `bus`,
  String.raw `place of origin (Switzerland)`,
  String.raw `doctoral thesis`,
  String.raw `series spin-off`,
  String.raw `category for people who died here`,
  String.raw `based on`,
  String.raw `approximation algorithm`,
  String.raw `highest judicial authority`,
  String.raw `coach of sports team`,
  String.raw `category for ship name`,
  String.raw `native language`,
  String.raw `talk show guest`,
  String.raw `category for maps`,
  String.raw `capital`,
  String.raw `architectural style`,
  String.raw `taxa found at location`,
  String.raw `dataset distribution`,
  String.raw `producer`,
  String.raw `has quality`,
  String.raw `observed in`,
  String.raw `facet of`,
  String.raw `positive therapeutic predictor`,
  String.raw `diaspora`,
  String.raw `uses`,
  String.raw `make-up artist`,
  String.raw `license`,
  String.raw `has written for`,
  String.raw `research site`,
  String.raw `medical examinations`,
  String.raw `solves`,
  String.raw `parallel street`,
  String.raw `location of formation`,
  String.raw `molecular function`,
  String.raw `medical condition treated`,
  String.raw `game mechanics`,
  String.raw `neurological function`,
  String.raw `use restriction status`,
  String.raw `Carnegie Classification of Institutions of Higher Education`,
  String.raw `approved by`,
  String.raw `removed feature`,
  String.raw `contributor(s) to the creative work`,
  String.raw `principal investigator`,
  String.raw `is pollinated by`,
  String.raw `child astronomical body`,
  String.raw `commanded by`,
  String.raw `instruction set`,
  String.raw `investigated by`,
  String.raw `military branch`,
  String.raw `studied by`,
  String.raw `godparent`,
  String.raw `copyright license`,
  String.raw `main regulatory text`,
  String.raw `applies to people`,
  String.raw `structure replaced by`,
  String.raw `entry receptor`,
  String.raw `country of origin`,
  String.raw `doctoral student`,
  String.raw `product or material produced`,
  String.raw `companion of`,
  String.raw `country for sport`,
  String.raw `has census`,
  String.raw `located in or next to body of water`,
  String.raw `student`,
  String.raw `editor`,
  String.raw `located on street`,
  String.raw `flag bearer`,
  String.raw `repeals`,
  String.raw `member of sports team`,
  String.raw `start grade`,
  String.raw `worshipped by`,
  String.raw `head coach`,
  String.raw `unveiled by`,
  String.raw `kit supplier`,
  String.raw `student organization of`,
  String.raw `standards body`,
  String.raw `day of week`,
  String.raw `head of government`,
  String.raw `historical region`,
  String.raw `separated from`,
  String.raw `tournament format`,
  String.raw `image captured with`,
  String.raw `has contributing factor`,
  String.raw `parent organization`,
  String.raw `follower of`,
  String.raw `named by`,
  String.raw `has edition or translation`,
  String.raw `inspired by`,
  String.raw `satellite bus`,
  String.raw `website account on`,
  String.raw `officeholder`,
  String.raw `catalog`,
  String.raw `father`,
  String.raw `screenwriter`,
  String.raw `depicted format`,
  String.raw `general classification of race participants`,
  String.raw `space launch vehicle`,
  String.raw `partially contains`,
  String.raw `guidance system`,
  String.raw `main building contractor`,
  String.raw `possible medical findings`,
  String.raw `has facet polytope`,
  String.raw `camera setup`,
  String.raw `located in the ecclesiastical territorial entity`,
  String.raw `taxon author`,
  String.raw `risk factor`,
  String.raw `biological phase`,
  String.raw `dual to`,
  String.raw `agonist of`,
  String.raw `Thibaudeau classification`,
  String.raw `second family name in Spanish name`,
  String.raw `season of club or team`,
  String.raw `chief operating officer`,
  String.raw `visitor centre`,
  String.raw `teaching method`,
  String.raw `color`,
  String.raw `package management system`,
  String.raw `conferred by`,
  String.raw `production company`,
  String.raw `headquarters location`,
  String.raw `creator`,
  String.raw `compressor type`,
  String.raw `antagonist of`,
  String.raw `scenographer`,
  String.raw `diplomatic mission sent`,
  String.raw `form of creative work`,
  String.raw `heritage designation`,
  String.raw `character designer`,
  String.raw `does not have part`,
  String.raw `in work`,
  String.raw `relevant qualification`,
  String.raw `victory`,
  String.raw `convicted of`,
  String.raw `binding of software library`,
  String.raw `month of the year`,
  String.raw `religion`,
  String.raw `adjacent building`,
  String.raw `nominee`,
  String.raw `distributor`,
  String.raw `soundtrack release`,
  String.raw `game mode`,
  String.raw `software engine`,
  String.raw `MediaWiki hooks used`,
  String.raw `astronomical filter`,
  String.raw `official language`,
  String.raw `registered with`,
  String.raw `valvetrain configuration`,
  String.raw `expansion of`,
  String.raw `Wi-Fi access`,
  String.raw `member of military unit`,
  String.raw `from fictional universe`,
  String.raw `director of archaeological fieldwork`,
  String.raw `publication in which this taxon name was established`,
  String.raw `seal description`,
  String.raw `storyboard artist`,
  String.raw `railway signalling system`,
  String.raw `connector`,
  String.raw `defender`,
  String.raw `has facility`,
  String.raw `has superpartner`,
  String.raw `patronym or matronym for this person`,
  String.raw `is a list of`,
  String.raw `has fruit type`,
  String.raw `gene duplication association with`,
  String.raw `stated in`,
  String.raw `top-level Internet domain`,
  String.raw `participating team`,
  String.raw `shares border with`,
  String.raw `torch lit by`,
  String.raw `radical`,
  String.raw `measurement scale`,
  String.raw `state of conservation`,
  String.raw `candidate`,
  String.raw `tributary`,
  String.raw `temporal range end`,
  String.raw `animal breed`,
  String.raw `ortholog`,
  String.raw `derivative work`,
  String.raw `admissible rule in`,
  String.raw `manufacturer`,
  String.raw `determination method`,
  String.raw `has phoneme`,
  String.raw `bowling style`,
  String.raw `playing hand`,
  String.raw `less than`,
  String.raw `flower color`,
  String.raw `after a work by`,
  String.raw `medical evacuation to`,
  String.raw `develops from`,
  String.raw `reservoir created`,
  String.raw `doctoral advisor`,
  String.raw `legal form`,
  String.raw `participant of`,
  String.raw `presenter`,
  String.raw `operating area`,
  String.raw `place of detention`,
  String.raw `art director`,
  String.raw `size designation`,
  String.raw `OSI Model layer location`,
  String.raw `member of the crew of`,
  String.raw `co-driver`,
  String.raw `reports periodicity`,
  String.raw `production designer`,
  String.raw `chivalric order`,
  String.raw `script directionality`,
  String.raw `handedness`,
  String.raw `original network`,
  String.raw `access status`,
  String.raw `substitute director/manager`,
  String.raw `orientation`,
  String.raw `owned by`,
  String.raw `autologous cell line`,
  String.raw `used by`,
  String.raw `overlies`,
  String.raw `origin of the watercourse`,
  String.raw `list of works`,
  String.raw `filming location`,
  String.raw `track gauge`,
  String.raw `measures`,
  String.raw `home port`,
  String.raw `platform`,
  String.raw `sidekick of`,
  String.raw `postsynaptic connection`,
  String.raw `evaluation of`,
  String.raw `terminus location`,
  String.raw `victim`,
  String.raw `Gram staining`,
  String.raw `official app`,
  String.raw `connects with`,
  String.raw `hair color`,
  String.raw `diplomatic relation`,
  String.raw `executive body`,
  String.raw `mtDNA haplogroup`,
  String.raw `composer`,
  String.raw `head of state`,
  String.raw `prosecutor`,
  String.raw `mother`,
  String.raw `complies with`,
  String.raw `owner of`,
  String.raw `has lyrics`,
  String.raw `statement supported by`,
  String.raw `notable people with this condition`,
  String.raw `undercarriage`,
  String.raw `judge`,
  String.raw `Roman cognomen`,
  String.raw `political party`,
  String.raw `samples from work`,
  String.raw `payment types accepted`,
  String.raw `calculated from`,
  String.raw `IUCN protected areas category`,
  String.raw `indigenous to`,
  String.raw `multi-channel network`,
  String.raw `oath made by`,
  String.raw `cover art by`,
  String.raw `basic form of government`,
  String.raw `translator`,
  String.raw `symptoms`,
  String.raw `collection creator`,
  String.raw `suggests the existence of`,
  String.raw `afflicts`,
  String.raw `laws applied`,
  String.raw `typically sells`,
  String.raw `publisher`,
  String.raw `stage classification`,
  String.raw `mother house`,
  String.raw `review score by`,
  String.raw `anthem`,
  String.raw `architect`,
  String.raw `mountains classification`,
  String.raw `musical conductor`,
  String.raw `academic degree`,
  String.raw `uses capitalization for`,
  String.raw `majority opinion by`,
  String.raw `location`,
  String.raw `mascot`,
  String.raw `Wikidata property`,
  String.raw `religious order`,
  String.raw `quotes work`,
  String.raw `located in the administrative territorial entity`,
  String.raw `category for films shot at this location`,
  String.raw `order of battle`,
  String.raw `target muscle`,
  String.raw `minor planet group`,
  String.raw `next crossing downstream`,
  String.raw `expression, gesture or body pose`,
  String.raw `sitter`,
  String.raw `time period`,
  String.raw `Saros cycle of eclipse`,
  String.raw `imprimitur granted by`,
  String.raw `habitat`,
  String.raw `lyrics by`,
  String.raw `original broadcaster`,
  String.raw `taxon rank`,
  String.raw `young rider classification`,
  String.raw `fracturing`,
  String.raw `seconded by`,
  String.raw `location of the point of view`,
  String.raw `family name`,
  String.raw `storage device`,
  String.raw `next crossing upstream`,
  String.raw `birthday`,
  String.raw `decreased expression in`,
  String.raw `era name`,
  String.raw `domain of saint or deity`,
  String.raw `librettist`,
  String.raw `adapted by`,
  String.raw `manifestation of`,
  String.raw `muscle insertion`,
  String.raw `results`,
  String.raw `located on terrain feature`,
  String.raw `solved by`,
  String.raw `incarnation of`,
  String.raw `gens`,
  String.raw `workshop of`,
  String.raw `language of work or name`,
  String.raw `crew member`,
  String.raw `eye color`,
  String.raw `inhibitor of`,
  String.raw `commemorates`,
  String.raw `audio system`,
  String.raw `has edition`,
  String.raw `course`,
  String.raw `statement disputed by`,
  String.raw `lowest note`,
  String.raw `newspaper format`,
  String.raw `distributed by`,
  String.raw `exemplar of`,
  String.raw `possible treatment`,
  String.raw `copyright holder`,
  String.raw `season ends`
];