export const KeysInLargeKB = {
  quantity : [
    String.raw `total fertility rate`,
    String.raw `inflation rate`,
    String.raw `water as percent of area`,
    String.raw `retirement age`,
    String.raw `marriageable age`,
    String.raw `compulsory education (maximum age)`,
    String.raw `compulsory education (minimum age)`,
    String.raw `unemployment rate`,
    String.raw `annual number of weddings`,
    String.raw `area`,
    String.raw `number of out-of-school children`,
    String.raw `age of majority`,
    String.raw `number of subscribers`,
    String.raw `population`,
    String.raw `Human Development Index`,
    String.raw `PPP GDP per capita`,
    String.raw `median income`,
    String.raw `GDP (PPP)`,
    String.raw `real gross domestic product growth rate`,
    String.raw `total reserves`,
    String.raw `nominal GDP per capita`,
    String.raw `nominal GDP`,
    String.raw `mains voltage`,
    String.raw `frequency`,
    String.raw `life expectancy`,
    String.raw `proportion`,
    String.raw `quantity`,
    String.raw `speed limit`,
    String.raw `VAT-rate`,
    String.raw `ranking`,
    String.raw `number of points/goals/set scored`,
    String.raw `price`,
    String.raw `vehicles per capita (1000)`,
    String.raw `female population`,
    String.raw `male population`,
    String.raw `age of consent`,
    String.raw `age of candidacy`,
    String.raw `Gini coefficient`,
    String.raw `member count`,
    String.raw `budget`,
    String.raw `height`,
    String.raw `width`,
    String.raw `number of children`,
    String.raw `votes received`,
    String.raw `number of speakers`,
    String.raw `employees`,
    String.raw `elevation above sea level`,
    String.raw `number of households`,
    String.raw `term length of office`,
    String.raw `duration`,
    String.raw `minimum value`,
    String.raw `maximum value`,
    String.raw `visitors per year`,
    String.raw `literacy rate`,
    String.raw `salinity`,
    String.raw `vertical depth`,
    String.raw `prize money`,
    String.raw `number of representations`,
    String.raw `age at event`,
    String.raw `numeric value`,
    String.raw `length`,
    String.raw `watershed area`,
    String.raw `maximum Strahler number`,
    String.raw `discharge`,
    String.raw `total revenue`,
    String.raw `number of works`,
    String.raw `number of works accessible online`,
    String.raw `number of deaths`,
    String.raw `number of representatives in an organization/legislature or won in elections`,
    String.raw `topographic prominence`,
    String.raw `thickness`,
    String.raw `mass`,
    String.raw `time index`,
    String.raw `oxidation state`,
    String.raw `atomic number`,
    String.raw `electronegativity`,
    String.raw `upper limit`,
    String.raw `lower limit`,
    String.raw `refractive index`,
    String.raw `temperature`,
    String.raw `density`,
    String.raw `speed of sound`,
    String.raw `thermal conductivity`,
    String.raw `ionization energy`,
    String.raw `melting point`,
    String.raw `boiling point`,
    String.raw `pressure`,
    String.raw `enthalpy of vaporization`,
    String.raw `number of parts of this work`,
    String.raw `cost`,
    String.raw `position angle`,
    String.raw `tensile modulus of elasticity`,
    String.raw `Poisson's ratio`,
    String.raw `Mohs' hardness`,
    String.raw `hardness`,
    String.raw `shear modulus`,
    String.raw `heat capacity`,
    String.raw `number of seats`,
    String.raw `UTC timezone offset`,
    String.raw `number of episodes`,
    String.raw `number of seasons`,
    String.raw `event interval`,
    String.raw `number of victims of killer`,
    String.raw `immediately dangerous to life or health`,
    String.raw `vapor pressure`,
    String.raw `time-weighted average exposure limit`,
    String.raw `median lethal dose (LD50)`,
    String.raw `short-term exposure limit`,
    String.raw `students count`,
    String.raw `rural population`,
    String.raw `urban population`,
    String.raw `electorate`,
    String.raw `fiscal/tax revenue`,
    String.raw `mean age`,
    String.raw `number of participants`,
    String.raw `race time`,
    String.raw `Alexa rank`,
    String.raw `maximum capacity`,
    String.raw `number of matches played/races/starts`,
    String.raw `total goals in career`,
    String.raw `match time of event`,
    String.raw `attendance`,
    String.raw `number of wins`,
    String.raw `number of draws/ties`,
    String.raw `number of losses`,
    String.raw `number of points/goals conceded`,
    String.raw `number of platform tracks`,
    String.raw `floors above ground`,
    String.raw `spin quantum number`,
    String.raw `parity quantum number`,
    String.raw `isospin z-component`,
    String.raw `isospin quantum number`,
    String.raw `g-factor`,
    String.raw `electric charge`,
    String.raw `magnetic moment`,
    String.raw `neutron number`,
    String.raw `number of graves`,
    String.raw `orbital inclination`,
    String.raw `orbital eccentricity`,
    String.raw `semi-major axis of an orbit`,
    String.raw `periapsis`,
    String.raw `longitude of ascending node`,
    String.raw `argument of periapsis`,
    String.raw `mean anomaly`,
    String.raw `orbital period`,
    String.raw `apoapsis`,
    String.raw `absolute magnitude`,
    String.raw `rotation period`,
    String.raw `diameter`,
    String.raw `albedo`,
    String.raw `perimeter`,
    String.raw `radius`,
    String.raw `volume as quantity`,
    String.raw `apparent magnitude`,
    String.raw `national team caps`,
    String.raw `patronage`,
    String.raw `gestation period`,
    String.raw `highest observed lifespan`,
    String.raw `parallax`,
    String.raw `right ascension`,
    String.raw `declination`,
    String.raw `proper motion`,
    String.raw `luminosity`,
    String.raw `net profit`,
    String.raw `total assets`,
    String.raw `operating income`,
    String.raw `total equity`,
    String.raw `redshift`,
    String.raw `radial velocity`,
    String.raw `number of elevators`,
    String.raw `conversion to standard unit`,
    String.raw `litter size`,
    String.raw `points for`,
    String.raw `total produced`,
    String.raw `wingspan`,
    String.raw `fee`,
    String.raw `minimal incubation period in humans`,
    String.raw `maximal incubation period in humans`,
    String.raw `maximum frequency of audible sound`,
    String.raw `minimum frequency of audible sound`,
    String.raw `maximum temperature record`,
    String.raw `event distance`,
    String.raw `speed`,
    String.raw `number of registered users/contributors`,
    String.raw `number of records`,
    String.raw `color index`,
    String.raw `distance from Earth`,
    String.raw `metallicity`,
    String.raw `effective temperature`,
    String.raw `stellar rotational velocity`,
    String.raw `surface gravity`,
    String.raw `angular diameter`,
    String.raw `personal best`,
    String.raw `market capitalization`,
    String.raw `total points in career`,
    String.raw `publication interval`,
    String.raw `number of houses`,
    String.raw `port`,
    String.raw `age estimated by a dating method`,
    String.raw `daily patronage`,
    String.raw `conversion to SI unit`,
    String.raw `sports league level`,
    String.raw `topographic isolation`,
    String.raw `galactic longitude`,
    String.raw `galactic latitude`,
    String.raw `period of lactation`,
    String.raw `residence time of water`,
    String.raw `standard enthalpy of formation`,
    String.raw `electric dipole moment`,
    String.raw `collection or exhibition size`,
    String.raw `number of platform faces`,
    String.raw `literate population`,
    String.raw `illiterate population`,
    String.raw `time gap`,
    String.raw `total valid votes`,
    String.raw `voltage`,
    String.raw `orbits completed`,
    String.raw `time in space`,
    String.raw `data size`,
    String.raw `number of casualties`,
    String.raw `number of survivors`,
    String.raw `payload mass`,
    String.raw `egg incubation period`,
    String.raw `units sold`,
    String.raw `incidence`,
    String.raw `beam`,
    String.raw `cumulative elevation gain`,
    String.raw `maximum operating altitude`,
    String.raw `net worth`,
    String.raw `wheelbase`,
    String.raw `eligible voters`,
    String.raw `ballots cast`,
    String.raw `number of negative votes`,
    String.raw `number of support votes`,
    String.raw `number of spoilt votes`,
    String.raw `total shots in career`,
    String.raw `penalty minutes in career`,
    String.raw `career plus-minus rating`,
    String.raw `total assists in career`,
    String.raw `number of pages`,
    String.raw `bite force quotient`,
    String.raw `defined daily dose`,
    String.raw `number of decimal digits`,
    String.raw `lighthouse range`,
    String.raw `heart rate`,
    String.raw `frequency of event`,
    String.raw `offset`,
    String.raw `number confirmed`,
    String.raw `number of injured`,
    String.raw `number of constituencies`,
    String.raw `number of perpetrators`,
    String.raw `maximum size or capacity`,
    String.raw `memory capacity`,
    String.raw `energy storage capacity`,
    String.raw `flash point`,
    String.raw `lower flammable limit`,
    String.raw `upper flammable limit`,
    String.raw `minimal lethal dose`,
    String.raw `autoignition temperature`,
    String.raw `fusion enthalpy`,
    String.raw `pKa`,
    String.raw `prevalence`,
    String.raw `M sin i`,
    String.raw `number of cases`,
    String.raw `standard molar entropy`,
    String.raw `floors below ground`,
    String.raw `closest approach`,
    String.raw `wavelength`,
    String.raw `moisture absorption`,
    String.raw `relative humidity`,
    String.raw `ultimate tensile strength`,
    String.raw `toughness`,
    String.raw `coefficient of friction`,
    String.raw `operating temperature`,
    String.raw `flexural strain at break`,
    String.raw `Elo rating`,
    String.raw `number of spans`,
    String.raw `draft`,
    String.raw `gross tonnage`,
    String.raw `installed capacity`,
    String.raw `wing area`,
    String.raw `vehicle range`,
    String.raw `specific absorption rate`,
    String.raw `carbon footprint`,
    String.raw `beats per minute`,
    String.raw `number of volunteers`,
    String.raw `longest span`,
    String.raw `power consumed`,
    String.raw `maximum gradient`,
    String.raw `mean lifetime`,
    String.raw `clock speed`,
    String.raw `quantity buried`,
    String.raw `number of cylinders`,
    String.raw `total liabilities`,
    String.raw `hydraulic head`,
    String.raw `number of abstentions`,
    String.raw `number of blank votes`,
    String.raw `minimum number of players`,
    String.raw `maximum number of players`,
    String.raw `size of team at start`,
    String.raw `chromosome count`,
    String.raw `points awarded`,
    String.raw `solubility`,
    String.raw `ceiling exposure limit`,
    String.raw `base salary`,
    String.raw `total expenditure`,
    String.raw `ride height`,
    String.raw `decomposition point`,
    String.raw `alcohol by volume`,
    String.raw `concentration`,
    String.raw `caliber`,
    String.raw `number of arrests`,
    String.raw `explosive energy equivalent`,
    String.raw `earthquake magnitude on the moment magnitude scale`,
    String.raw `aftershocks`,
    String.raw `maximum sustained winds`,
    String.raw `lowest atmospheric pressure`,
    String.raw `focal length`,
    String.raw `slope`,
    String.raw `distance from river mouth`,
    String.raw `number of missing`,
    String.raw `number of hospital beds`,
    String.raw `focal height`,
    String.raw `common equity tier 1 capital ratio (CETI)`,
    String.raw `prisoner count`,
    String.raw `coastline`,
    String.raw `cost of damage`,
    String.raw `minimum age`,
    String.raw `maximum age`,
    String.raw `face value`,
    String.raw `minimum wavelength of sensitivity`,
    String.raw `maximum wavelength of sensitivity`,
    String.raw `admission rate`,
    String.raw `bore`,
    String.raw `field of view`,
    String.raw `effective firing range`,
    String.raw `Scoville grade`,
    String.raw `non-operating temperature`,
    String.raw `average speed`,
    String.raw `century breaks`,
    String.raw `highest break`,
    String.raw `clearance`,
    String.raw `donations`,
    String.raw `assets under management`,
    String.raw `maximum thrust`,
    String.raw `luminous intensity`,
    String.raw `median lethal concentration (LC50)`,
    String.raw `global warming potential`,
    String.raw `surface tension`,
    String.raw `acceptable daily intake`,
    String.raw `partition coefficient water/octanol`,
    String.raw `data transfer speed`,
    String.raw `production rate`,
    String.raw `observing time available`,
    String.raw `number of reviews/ratings`,
    String.raw `endowment`,
    String.raw `earthquake magnitude on the Richter magnitude scale`,
    String.raw `number of branches`,
    String.raw `horizontal depth`,
    String.raw `boiler pressure`,
    String.raw `annual energy output`,
    String.raw `half-life`,
    String.raw `natural abundance`,
    String.raw `mass excess`,
    String.raw `binding energy`,
    String.raw `wind speed`,
    String.raw `IPA number order`,
    String.raw `scale`,
    String.raw `service life`,
    String.raw `estimated value`,
    String.raw `net tonnage`,
    String.raw `par`,
    String.raw `slope rating`,
    String.raw `number of masts`,
    String.raw `cruise speed`,
    String.raw `minimum temperature record`,
    String.raw `maximum glide ratio`,
    String.raw `approach angle`,
    String.raw `departure angle`,
    String.raw `number of clubs`,
    String.raw `block size`,
    String.raw `number of players in region`,
    String.raw `angle from vertical`,
    String.raw `offset from vertical`,
    String.raw `target interest rate`,
    String.raw `muzzle velocity`,
    String.raw `elongation at break`,
    String.raw `nominal share capital`,
    String.raw `graph diameter`,
    String.raw `narrative age`,
    String.raw `number of words`,
    String.raw `cardinality of the group`,
    String.raw `compression ratio`,
    String.raw `angular distance`,
    String.raw `angular resolution`,
    String.raw `computer performance`,
    String.raw `throughput`,
    String.raw `number of viewers/listeners`,
    String.raw `Sandbox-Quantity`,
    String.raw `capacity factor`,
    String.raw `engine displacement`,
    String.raw `social media followers`,
    String.raw `tuition fee`,
    String.raw `stroke`,
    String.raw `aperture`,
    String.raw `stroke count`,
    String.raw `JMA Magnitude`,
    String.raw `magnification`,
    String.raw `number of polling stations`,
    String.raw `point of penalty`,
    String.raw `number probable`,
    String.raw `number suspected`,
    String.raw `axle track`,
    String.raw `trading fee`,
    String.raw `laps completed`,
    String.raw `family relationship degree`,
    String.raw `number of processor cores`,
    String.raw `account charge / subscription fee`,
    String.raw `foreign transaction fee`,
    String.raw `cash back`,
    String.raw `number of clinical tests`,
    String.raw `number of recoveries`,
    String.raw `case fatality rate`,
    String.raw `number of hospitalized cases`,
    String.raw `suicide rate`,
    String.raw `disease burden`,
    String.raw `number of representatives in an organization/legislature`,
    String.raw `flattening`,
    String.raw `synodic period`,
    String.raw `semi-major axis`,
    String.raw `Erdős number`,
    String.raw `timezone offset`,
    String.raw `electrical conductivity`,
    String.raw `beer bitterness`,
    String.raw `water footprint`,
    String.raw `dynamic viscosity`,
    String.raw `maximum peak exposure limit`,
    String.raw `Euler characteristic`,
    String.raw `Wikidata time precision`,
    String.raw `minimum explosive concentration`,
    String.raw `number of parts of this work of art`,
    String.raw `generation time`,
    String.raw `flux`,
    String.raw `combustion enthalpy`,
    String.raw `average shot length`,
    String.raw `kinematic viscosity`,
    String.raw `thermal diffusivity`,
    String.raw `genome size`,
    String.raw `stated age at event`,
    String.raw `molar volume`,
    String.raw `explosive velocity`,
    String.raw `biobased content weight percentage`,
    String.raw `vehicles per thousand people`,
    String.raw `rate of fire`,
    String.raw `solar irradiance`,
    String.raw `precipitation height`,
    String.raw `basic reproduction number`,
    String.raw `fineness`,
    String.raw `foreign direct investment net outflow`,
    String.raw `foreign direct investment net inflow`,
    String.raw `embodied energy`,
    String.raw `relative permeability`,
    String.raw `compressive modulus of elasticity`,
    String.raw `minimum quantity`,
    String.raw `relative permittivity`,
    String.raw `consumption rate per capita`,
    String.raw `consumption rate`,
    String.raw `thermal design power`,
    String.raw `test score`,
    String.raw `food energy`,
    String.raw `average gradient`,
    String.raw `residual stroke count`,
    String.raw `median lethal dose`,
    String.raw `feed-in tariff`,
    String.raw `drag coefficient`,
    String.raw `yield strength`,
    String.raw `total exports`,
    String.raw `central government debt as a percent of GDP`,
    String.raw `gyromagnetic ratio`,
    String.raw `cash`,
    String.raw `shelf life`,
    String.raw `sound power level`,
    String.raw `stall speed`,
    String.raw `decay width`,
    String.raw `readership`,
    String.raw `torque`,
    String.raw `takeoff roll`,
    String.raw `size of team at finish`,
    String.raw `individual tax rate`,
    String.raw `highest income threshold`,
    String.raw `lowest income threshold`,
    String.raw `number of rooms`,
    String.raw `turning radius`,
    String.raw `limiting oxygen index`,
    String.raw `Vicat softening point`,
    String.raw `force`,
    String.raw `flexural strength`,
    String.raw `flexural modulus`,
    String.raw `total imports`,
    String.raw `pitting resistance equivalent number`,
    String.raw `linear reference`,
    String.raw `no-observed-adverse-effect level`,
    String.raw `hill size`,
    String.raw `construction point`,
    String.raw `total debt`,
    String.raw `Football Money League rank`,
    String.raw `minimal lethal concentration`,
    String.raw `minimum wage`,
    String.raw `charge conjugation quantum number`,
    String.raw `time to altitude`,
    String.raw `graph radius`,
    String.raw `shear strength`,
    String.raw `f-number`,
  ],
  date : [
    String.raw `point in time`,
    String.raw `end time`,
    String.raw `start time`,
    String.raw `inception`,
    String.raw `retrieved`,
    String.raw `publication date`,
    String.raw `date of birth`,
    String.raw `date of death`,
    String.raw `dissolved, abolished or demolished`,
    String.raw `date of burial or cremation`,
    String.raw `oath of office date`,
    String.raw `public domain date`,
    String.raw `time of earliest written record`,
    String.raw `earliest date`,
    String.raw `latest date`,
    String.raw `work period (start)`,
    String.raw `date of baptism in early childhood`,
    String.raw `time of discovery or invention`,
    String.raw `work period (end)`,
    String.raw `date of first performance`,
    String.raw `date of official opening`,
    String.raw `year of taxon publication`,
    String.raw `date of the first one`,
    String.raw `date of the latest one`,
    String.raw `announcement date`,
    String.raw `floruit`,
    String.raw `first flight`,
    String.raw `service retirement`,
    String.raw `date of official closure`,
    String.raw `service entry`,
    String.raw `archive date`,
    String.raw `discontinued date`,
    String.raw `UTC date of spacecraft launch`,
    String.raw `time of spacecraft orbit decay`,
    String.raw `time of spacecraft landing`,
    String.raw `latest start date`,
    String.raw `date of disappearance`,
    String.raw `date of commercialization`,
    String.raw `production date`,
    String.raw `extinction date`,
    String.raw `date depicted`,
    String.raw `effective date`,
    String.raw `date of assent`,
    String.raw `spacecraft docking/undocking date`,
    String.raw `last update`,
    String.raw `awarded for period`,
    String.raw `periapsis date`,
    String.raw `minimum date (property constraint)`,
    String.raw `earliest end date`,
    String.raw `year of taxon name publication`,
    String.raw `start of covered period`,
    String.raw `maximum date (property constraint)`,
    String.raw `Gregorian calendar start date`,
    String.raw `end of covered period`,
  ],
  string : [
    String.raw `determination method`,
    String.raw `NUTS code`,
    String.raw `maritime identification digits`,
    String.raw `CIVICUS Monitor country entry`,
    String.raw `applies to part`,
    String.raw `short name`,
    String.raw `instance of`,
    String.raw `demonym`,
    String.raw `sex or gender`,
    String.raw `ISO 3166-1 numeric code`,
    String.raw `ISO 3166-1 alpha-3 code`,
    String.raw `ISO 3166-1 alpha-2 code`,
    String.raw `IOC country code`,
    String.raw `official website`,
    String.raw `subreddit`,
    String.raw `language of work or name`,
    String.raw `FIPS 10-4 (countries and regions)`,
    String.raw `UIC numerical country code`,
    String.raw `UIC alphabetical country code`,
    String.raw `country calling code`,
    String.raw `Dewey Decimal Classification`,
    String.raw `motto text`,
    String.raw `trunk prefix`,
    String.raw `official name`,
    String.raw `licence plate code`,
    String.raw `INSEE countries and foreign territories code`,
    String.raw `mobile country code`,
    String.raw `ITU letter code`,
    String.raw `statement is subject of`,
    String.raw `valid in period`,
    String.raw `diplomatic mission sent`,
    String.raw `direction relative to location`,
    String.raw `performer`,
    String.raw `object has role`,
    String.raw `located in the administrative territorial entity`,
    String.raw `of`,
    String.raw `street address`,
    String.raw `has cause`,
    String.raw `reason for deprecation`,
    String.raw `female form of label`,
    String.raw `replaces`,
    String.raw `replaced by`,
    String.raw `series ordinal`,
    String.raw `cabinet`,
    String.raw `valid in place`,
    String.raw `relief location map`,
    String.raw `ISNI`,
    String.raw `currency`,
    String.raw `native label`,
    String.raw `Twitter hashtag`,
    String.raw `Stack Exchange tag`,
    String.raw `location`,
    String.raw `main regulatory text`,
    String.raw `end cause`,
    String.raw `sourcing circumstances`,
    String.raw `country`,
    String.raw `nature of statement`,
    String.raw `together with`,
    String.raw `participant`,
    String.raw `headquarters location`,
    String.raw `image`,
    String.raw `legal form`,
    String.raw `represents`,
    String.raw `represented by`,
    String.raw `basic form of government`,
    String.raw `reason for preferred rank`,
    String.raw `platform`,
    String.raw `direction`,
    String.raw `excluding`,
    String.raw `quotation`,
    String.raw `Wikitribune category`,
    String.raw `follows`,
    String.raw `position held`,
    String.raw `title`,
    String.raw `statement disputed by`,
    String.raw `member of`,
    String.raw `criterion used`,
    String.raw `statement supported by`,
    String.raw `use`,
    String.raw `writing system`,
    String.raw `video`,
    String.raw `IAB code`,
    String.raw `external data available at`,
    String.raw `main subject`,
    String.raw `GS1 country code`,
    String.raw `nighttime view`,
    String.raw `Instagram username`,
    String.raw `Twitter username`,
    String.raw `detail map`,
    String.raw `M.49 code`,
    String.raw `vocalized name`,
    String.raw `member of political party`,
    String.raw `subject has role`,
    String.raw `including`,
    String.raw `name in native language`,
    String.raw `monogram`,
    String.raw `place of marriage`,
    String.raw `military rank`,
    String.raw `regnal ordinal`,
    String.raw `type of kinship`,
    String.raw `inventory number`,
    String.raw `postal code`,
    String.raw `IPv6 routing prefix`,
    String.raw `Twitter user numeric ID`,
    String.raw `has quality`,
    String.raw `collection`,
    String.raw `depicts Iconclass notation`,
    String.raw `catalog code`,
    String.raw `applies to jurisdiction`,
    String.raw `ISO 3166-2 code`,
    String.raw `locator map image`,
    String.raw `volume`,
    String.raw `page(s)`,
    String.raw `section, verse, paragraph, or clause`,
    String.raw `applies to name of value`,
    String.raw `Libris-URI`,
    String.raw `KulturNav-id`,
    String.raw `Biografisch Portaal number`,
    String.raw `British Museum person-institution`,
    String.raw `elected in`,
    String.raw `burial plot reference`,
    String.raw `stated as`,
    String.raw `described at URL`,
    String.raw `named as`,
    String.raw `drug used for treatment`,
    String.raw `relative position within image`,
    String.raw `applies to name`,
    String.raw `political party`,
    String.raw `parliamentary term`,
    String.raw `employer`,
    String.raw `organization directed by the office or person`,
    String.raw `affiliation`,
    String.raw `electoral district`,
    String.raw `Library of Congress Classification`,
    String.raw `IPTC Newscode`,
    String.raw `native language`,
    String.raw `operating area`,
    String.raw `languages spoken, written or signed`,
    String.raw `broadcast by`,
    String.raw `identity of object in context`,
    String.raw `lyrics by`,
    String.raw `translator`,
    String.raw `distributed by`,
    String.raw `religion`,
    String.raw `Munzinger IBA`,
    String.raw `birth name`,
    String.raw `Google Doodle`,
    String.raw `for work`,
    String.raw `academic degree`,
    String.raw `academic major`,
    String.raw `partnership with`,
    String.raw `field of work`,
    String.raw `genre`,
    String.raw `OCLC control number`,
    String.raw `ISBN-10`,
    String.raw `ISBN-13`,
    String.raw `followed by`,
    String.raw `local dialing code`,
    String.raw `located at street address (DEPRECATED)`,
    String.raw `phone number`,
    String.raw `DfE URN`,
    String.raw `UK Provider Reference Number`,
    String.raw `winner`,
    String.raw `work location`,
    String.raw `educated at`,
    String.raw `field of this occupation`,
    String.raw `URL`,
    String.raw `creator`,
    String.raw `comment (DEPRECATED)`,
    String.raw `author`,
    String.raw `street number`,
    String.raw `street address (DEPRECATED)`,
    String.raw `located on street`,
    String.raw `located on astronomical location`,
    String.raw `Glottolog code`,
    String.raw `WALS lect code`,
    String.raw `ISO 639-2 code`,
    String.raw `ISO 639-1 code`,
    String.raw `Wikimedia language code`,
    String.raw `GOST 7.75–97 code`,
    String.raw `Ethnologue.com language code`,
    String.raw `distribution map`,
    String.raw `IETF language tag`,
    String.raw `ISO 639-3 code`,
    String.raw `Universal Decimal Classification`,
    String.raw `Gallica ID`,
    String.raw `geoshape`,
    String.raw `country of citizenship`,
    String.raw `named by`,
    String.raw `refine date`,
    String.raw `Iconclass notation`,
    String.raw `Unicode character`,
    String.raw `sectional view`,
    String.raw `name`,
    String.raw `ISWC`,
    String.raw `RIA Novosti reference`,
    String.raw `color`,
    String.raw `applies to name of item`,
    String.raw `shown with features`,
    String.raw `present in work`,
    String.raw `nickname`,
    String.raw `cuisine`,
    String.raw `first line`,
    String.raw `last line`,
    String.raw `audio`,
    String.raw `China administrative division code`,
    String.raw `schematic`,
    String.raw `NLC authorities`,
    String.raw `nominated by`,
    String.raw `officeholder`,
    String.raw `Linguasphere code`,
    String.raw `has edition or translation`,
    String.raw `running mate`,
    String.raw `media legend`,
    String.raw `USDA NDB number`,
    String.raw `OSM tag or key`,
    String.raw `German municipality key`,
    String.raw `German district key`,
    String.raw `located at street address`,
    String.raw `occupation`,
    String.raw `military branch`,
    String.raw `IPA transcription`,
    String.raw `hashtag`,
    String.raw `catalog`,
    String.raw `award rationale`,
    String.raw `character role`,
    String.raw `parliamentary group`,
    String.raw `INSEE municipality code`,
    String.raw `SIREN number`,
    String.raw `Italian cadastre code`,
    String.raw `publisher`,
    String.raw `UN/LOCODE`,
    String.raw `facet of`,
    String.raw `GitHub username`,
    String.raw `IRS Employer Identification Number`,
    String.raw `ARCHON code`,
    String.raw `ISBN publisher prefix`,
    String.raw `NRHP reference number`,
    String.raw `donated by`,
    String.raw `has part`,
    String.raw `software version identifier`,
    String.raw `Regensburg Classification`,
    String.raw `mapping relation type`,
    String.raw `conflict`,
    String.raw `narrative location`,
    String.raw `allegiance`,
    String.raw `amateur radio callsign`,
    String.raw `party chief representative`,
    String.raw `appointed by`,
    String.raw `manufacturer`,
    String.raw `depicts`,
    String.raw `element symbol`,
    String.raw `CAS Registry Number`,
    String.raw `phase of matter`,
    String.raw `Unicode hex codepoint`,
    String.raw `electron configuration`,
    String.raw `chemical formula`,
    String.raw `TERYT municipality code`,
    String.raw `subtitle`,
    String.raw `INSEE region code`,
    String.raw `INSEE department code`,
    String.raw `Foundational Model of Anatomy ID`,
    String.raw `TA98 Latin term`,
    String.raw `LEM ID`,
    String.raw `last words`,
    String.raw `named after`,
    String.raw `place name sign`,
    String.raw `Commons category`,
    String.raw `Norwegian municipality number`,
    String.raw `Norwegian organisation number`,
    String.raw `PO Box`,
    String.raw `NIS/INS code`,
    String.raw `Finnish municipality number`,
    String.raw `SSR place name number`,
    String.raw `Swedish Anbytarforum`,
    String.raw `contains administrative territorial entity`,
    String.raw `commanded by`,
    String.raw `place of publication`,
    String.raw `exploitation visa number`,
    String.raw `box office`,
    String.raw `nominee`,
    String.raw `Brazilian municipality code`,
    String.raw `student of`,
    String.raw `IPI name number`,
    String.raw `Hornbostel-Sachs classification`,
    String.raw `in work`,
    String.raw `type of orbit`,
    String.raw `ISCO occupation code`,
    String.raw `ROME Occupation Code (v3)`,
    String.raw `director of photography`,
    String.raw `architect`,
    String.raw `uses`,
    String.raw `tributary orientation`,
    String.raw `conferred by`,
    String.raw `relative to`,
    String.raw `EPPO Code`,
    String.raw `Reaxys registry number`,
    String.raw `Gmelin number`,
    String.raw `CBS municipality code`,
    String.raw `Amsterdam code`,
    String.raw `ZVG number`,
    String.raw `UNII`,
    String.raw `InChIKey`,
    String.raw `NCI Thesaurus ID`,
    String.raw `isomeric SMILES`,
    String.raw `EC number`,
    String.raw `canonical SMILES`,
    String.raw `InChI`,
    String.raw `UMLS CUI`,
    String.raw `pseudonym`,
    String.raw `has effect`,
    String.raw `taxon name`,
    String.raw `FIPS 5-2 alpha code (US states)`,
    String.raw `FIPS 5-2 numeric code (US states)`,
    String.raw `FIPS 6-4 (US counties)`,
    String.raw `transliteration`,
    String.raw `ISO 4217 code`,
    String.raw `ISOCAT id`,
    String.raw `Swiss municipality code`,
    String.raw `unit symbol`,
    String.raw `catchphrase`,
    String.raw `PhilPapers topic`,
    String.raw `notable work`,
    String.raw `Thailand central administrative unit code`,
    String.raw `nominated for`,
    String.raw `RTECS number`,
    String.raw `UNSPSC Code`,
    String.raw `CosIng number`,
    String.raw `Google Maps Customer ID`,
    String.raw `narrative role`,
    String.raw `part of`,
    String.raw `format as a regular expression`,
    String.raw `sRGB color hex triplet`,
    String.raw `head of state`,
    String.raw `part of the series`,
    String.raw `coat of arms image`,
    String.raw `head of government`,
    String.raw `organizer`,
    String.raw `sport`,
    String.raw `chairperson`,
    String.raw `central bank`,
    String.raw `day in year for periodic occurrence`,
    String.raw `award received`,
    String.raw `founded by`,
    String.raw `noble title`,
    String.raw `territory claimed by`,
    String.raw `class`,
    String.raw `significant event`,
    String.raw `item operated`,
    String.raw `has immediate cause`,
    String.raw `medical condition`,
    String.raw `cause of death`,
    String.raw `Classification of Instructional Programs code`,
    String.raw `NIOSH Pocket Guide ID`,
    String.raw `route of administration`,
    String.raw `applies to taxon`,
    String.raw `afflicts`,
    String.raw `UN number`,
    String.raw `killed by`,
    String.raw `IPv4 routing prefix`,
    String.raw `Charity Commission no.`,
    String.raw `doctoral advisor`,
    String.raw `doctoral thesis`,
    String.raw `German regional key`,
    String.raw `EAGLE id`,
    String.raw `Revised Romanization`,
    String.raw `McCune-Reischauer romanization`,
    String.raw `Soundex`,
    String.raw `Cologne phonetics`,
    String.raw `Caverphone`,
    String.raw `Amazon author page`,
    String.raw `Artists in Canada record number`,
    String.raw `time period`,
    String.raw `IATA airport code`,
    String.raw `interested in`,
    String.raw `alternate names`,
    String.raw `male form of label`,
    String.raw `literal translation`,
    String.raw `Indian census area code (2001)`,
    String.raw `BMLO`,
    String.raw `filming location`,
    String.raw `taxon author`,
    String.raw `ITIS TSN`,
    String.raw `taxon common name`,
    String.raw `IUCN taxon ID`,
    String.raw `OpenStreetMap tag or key`,
    String.raw `place of death`,
    String.raw `name in hiero markup`,
    String.raw `Philippine Standard Geographic Code`,
    String.raw `Munzinger Sport number`,
    String.raw `conscription number`,
    String.raw `edition number`,
    String.raw `sports discipline competed in`,
    String.raw `member of sports team`,
    String.raw `test taken`,
    String.raw `country for sport`,
    String.raw `manner of death`,
    String.raw `administrative code of Indonesia`,
    String.raw `sport number`,
    String.raw `acquisition transaction`,
    String.raw `departure transaction`,
    String.raw `home venue`,
    String.raw `Giphy username`,
    String.raw `position played on team / speciality`,
    String.raw `FIFA country code`,
    String.raw `Wikidata SPARQL query equivalent`,
    String.raw `flag bearer`,
    String.raw `Statistics Canada Geographic code`,
    String.raw `proxy`,
    String.raw `competition class`,
    String.raw `OS grid reference`,
    String.raw `UAI code`,
    String.raw `Vimeo username`,
    String.raw `Name Assigning Authority Number`,
    String.raw `SIRET number`,
    String.raw `penalty`,
    String.raw `described by source`,
    String.raw `name in kana`,
    String.raw `archival creator authority record at the Archives nationales`,
    String.raw `file extension`,
    String.raw `media type`,
    String.raw `CVR number`,
    String.raw `EU VAT number`,
    String.raw `feast day`,
    String.raw `chapter`,
    String.raw `Monte Carlo Particle Number`,
    String.raw `review score`,
    String.raw `review score by`,
    String.raw `day of week`,
    String.raw `Snapchat username`,
    String.raw `mother`,
    String.raw `father`,
    String.raw `DiseasesDB`,
    String.raw `ICD-9`,
    String.raw `ICD-10`,
    String.raw `eMedicine`,
    String.raw `MeSH Code`,
    String.raw `editor`,
    String.raw `provisional designation`,
    String.raw `item of property constraint`,
    String.raw `INE municipality code`,
    String.raw `studies`,
    String.raw `GSS code (2011)`,
    String.raw `astronomical filter`,
    String.raw `NSDAP membership number (1925\u20131945)`,
    String.raw `SIRUTA code`,
    String.raw `LAU`,
    String.raw `asteroid family`,
    String.raw `voice type`,
    String.raw `ICAO airport code`,
    String.raw `head coach`,
    String.raw `coach of sports team`,
    String.raw `NBN System Key`,
    String.raw `parent taxon`,
    String.raw `Reddit username`,
    String.raw `name of the character role (theatre)`,
    String.raw `religious order`,
    String.raw `World Heritage criteria`,
    String.raw `production code`,
    String.raw `league`,
    String.raw `shape`,
    String.raw `spectral class`,
    String.raw `ISIN`,
    String.raw `ticker symbol`,
    String.raw `Swedish urban area code`,
    String.raw `ICD-9-CM`,
    String.raw `ICD-10-CM`,
    String.raw `place of birth`,
    String.raw `version type`,
    String.raw `GS1 Global Product Classification brick code`,
    String.raw `author citation (zoology)`,
    String.raw `Politika topic`,
    String.raw `J. Paul Getty Museum artist id`,
    String.raw `inflows`,
    String.raw `Revised Hepburn romanization`,
    String.raw `reference URL`,
    String.raw `GRIN URL`,
    String.raw `Telegram username`,
    String.raw `relative`,
    String.raw `inscription`,
    String.raw `unabbreviated text`,
    String.raw `dantai code`,
    String.raw `Corporate Number (Japan)`,
    String.raw `shares border with`,
    String.raw `pinyin transliteration`,
    String.raw `Tibetan pinyin`,
    String.raw `Wylie transliteration`,
    String.raw `Pinterest username`,
    String.raw `archive URL`,
    String.raw `married name`,
    String.raw `Roman praenomen`,
    String.raw `operator`,
    String.raw `wheelchair accessibility`,
    String.raw `does not have part`,
    String.raw `military designation`,
    String.raw `ICAO airline designator`,
    String.raw `IATA airline designator`,
    String.raw `callsign of airline`,
    String.raw `Merchant Category Code`,
    String.raw `airline accounting code`,
    String.raw `mobile network code`,
    String.raw `Enterprise number (Belgium)`,
    String.raw `official blog`,
    String.raw `stability of property value`,
    String.raw `manifestation of`,
    String.raw `quantity symbol (string)`,
    String.raw `has melody`,
    String.raw `investor`,
    String.raw `EDRPOU code`,
    String.raw `start period`,
    String.raw `end period`,
    String.raw `language used`,
    String.raw `business division`,
    String.raw `village code of Indonesia`,
    String.raw `ISO 15924 numeric code`,
    String.raw `regular expression syntax`,
    String.raw `ISO 15924 alpha-4 code`,
    String.raw `e-mail address`,
    String.raw `approved by`,
    String.raw `Patientplus ID`,
    String.raw `ATC code`,
    String.raw `World Health Organisation International Nonproprietary Name`,
    String.raw `chemical structure`,
    String.raw `spouse`,
    String.raw `given name`,
    String.raw `IRC channel`,
    String.raw `GeoNames feature code`,
    String.raw `material used`,
    String.raw `mountain range`,
    String.raw `continent`,
    String.raw `distribution format`,
    String.raw `original broadcaster`,
    String.raw `runway`,
    String.raw `ISO standard`,
    String.raw `bug tracking system`,
    String.raw `road number`,
    String.raw `courtesy name`,
    String.raw `autonomous system number`,
    String.raw `ISO 9362 SWIFT/BIC code`,
    String.raw `serial number`,
    String.raw `yard number`,
    String.raw `vehicle normally used`,
    String.raw `public key fingerprint`,
    String.raw `ISSN`,
    String.raw `quote`,
    String.raw `issue`,
    String.raw `full work available at URL`,
    String.raw `aircraft registration`,
    String.raw `HDS ID`,
    String.raw `TeX string`,
    String.raw `HTML entity`,
    String.raw `code`,
    String.raw `encoding`,
    String.raw `posthumous name`,
    String.raw `temple name`,
    String.raw `singles record`,
    String.raw `doubles record`,
    String.raw `located in or next to body of water`,
    String.raw `station code`,
    String.raw `towards`,
    String.raw `connecting service`,
    String.raw `dan/kyu rank`,
    String.raw `ACM Classification Code (2012)`,
    String.raw `website username`,
    String.raw `greater than`,
    String.raw `Minor Planet Center observatory code`,
    String.raw `galaxy morphological type`,
    String.raw `studied by`,
    String.raw `streaming media URL`,
    String.raw `DOI prefix`,
    String.raw `owned by`,
    String.raw `points/goal scored by`,
    String.raw `ICPC 2 ID`,
    String.raw `architectural style`,
    String.raw `director / manager`,
    String.raw `Wikimedia username`,
    String.raw `Nickel-Strunz '10th ed', review of (9th ed/ 2009 update)`,
    String.raw `Nickel-Strunz 9th edition (updated 2009)`,
    String.raw `Strunz 8th edition (series ID, updated)`,
    String.raw `fax number`,
    String.raw `Common Procurement Vocabulary`,
    String.raw `DNB editions`,
    String.raw `MCN code`,
    String.raw `channel number`,
    String.raw `draft pick number`,
    String.raw `drafted by`,
    String.raw `SOC Code (2010)`,
    String.raw `Gentoo package`,
    String.raw `MAME ROM name`,
    String.raw `download link`,
    String.raw `Fedora package`,
    String.raw `Debian stable package`,
    String.raw `Ubuntu package`,
    String.raw `astronaut mission`,
    String.raw `separated from`,
    String.raw `identity of subject in context`,
    String.raw `Ameblo username`,
    String.raw `connecting line`,
    String.raw `Indian census area code (2011)`,
    String.raw `Medium username`,
    String.raw `botanist author abbreviation`,
    String.raw `ELSTAT geographical code`,
    String.raw `author name string`,
    String.raw `EThOS thesis ID`,
    String.raw `NOC Occupation Code`,
    String.raw `E number`,
    String.raw `EC enzyme number`,
    String.raw `incertae sedis`,
    String.raw `participant in`,
    String.raw `operating system`,
    String.raw `voice actor`,
    String.raw `FAA airport code`,
    String.raw `directions`,
    String.raw `flight number`,
    String.raw `academic minor`,
    String.raw `start point`,
    String.raw `diocese`,
    String.raw `romanization of Belarusian (2007 system)`,
    String.raw `pennant number`,
    String.raw `commissioned by`,
    String.raw `Danish urban area code`,
    String.raw `ex taxon author`,
    String.raw `webcam page URL`,
    String.raw `fabrication method`,
    String.raw `state of conservation`,
    String.raw `cause of destruction`,
    String.raw `destroyed`,
    String.raw `legislative body`,
    String.raw `located on terrain feature`,
    String.raw `unmarried partner`,
    String.raw `distribution`,
    String.raw `country of origin`,
    String.raw `parliament.uk biography pages`,
    String.raw `distinctive jersey`,
    String.raw `Dewey Decimal Classification (works and editions)`,
    String.raw `Library of Congress Classification (works and editions)`,
    String.raw `measures`,
    String.raw `composer`,
    String.raw `ISO 3166-3`,
    String.raw `Sandbox-String`,
    String.raw `syntax clarification`,
    String.raw `gender of a scientific name of a genus`,
    String.raw `taxon author citation`,
    String.raw `Australian Business Number`,
    String.raw `EHAK id`,
    String.raw `office contested`,
    String.raw `candidate number`,
    String.raw `recorded at studio or venue`,
    String.raw `WMI code`,
    String.raw `said to be the same as`,
    String.raw `victory`,
    String.raw `located in time zone`,
    String.raw `Swedish municipality code`,
    String.raw `Swedish Organization Number`,
    String.raw `route number`,
    String.raw `parent organization`,
    String.raw `National Heritage List for England number`,
    String.raw `seed`,
    String.raw `Hungarian-style transcription`,
    String.raw `original spelling`,
    String.raw `Nupill Literatura Digital - Author`,
    String.raw `different from`,
    String.raw `captain`,
    String.raw `nomenclatural status`,
    String.raw `SWB editions`,
    String.raw `NATO reporting name`,
    String.raw `dummy value`,
    String.raw `SPLASH`,
    String.raw `ISO 639-5 code`,
    String.raw `stage classification`,
    String.raw `LinkedIn personal profile URL`,
    String.raw `issued by`,
    String.raw `KLfG Critical Dictionary of foreign contemporary literature`,
    String.raw `family`,
    String.raw `copyright license`,
    String.raw `signatory`,
    String.raw `Mastodon address`,
    String.raw `pronunciation`,
    String.raw `Dreadnought Project page`,
    String.raw `IPI base code`,
    String.raw `docking port`,
    String.raw `Arch Linux package`,
    String.raw `file format identification pattern`,
    String.raw `has contributing factor`,
    String.raw `court`,
    String.raw `armament`,
    String.raw `plea`,
    String.raw `laws applied`,
    String.raw `judge`,
    String.raw `RxNorm CUI`,
    String.raw `Quebec municipalities geographical code`,
    String.raw `electoral district number`,
    String.raw `edition or translation of`,
    String.raw `codename`,
    String.raw `structure replaced by`,
    String.raw `place of burial`,
    String.raw `family name`,
    String.raw `image of grave`,
    String.raw `model item`,
    String.raw `search formatter URL`,
    String.raw `KSH code`,
    String.raw `exception to constraint`,
    String.raw `characters`,
    String.raw `file format`,
    String.raw `mascot`,
    String.raw `solvent`,
    String.raw `model year code`,
    String.raw `secretary general`,
    String.raw `workshop of`,
    String.raw `from narrative universe`,
    String.raw `wears`,
    String.raw `home world`,
    String.raw `UN class`,
    String.raw `adapted by`,
    String.raw `depicted by`,
    String.raw `OLAC video game genre vocabulary`,
    String.raw `located in present-day administrative territorial entity`,
    String.raw `coordinate location`,
    String.raw `sponsor`,
    String.raw `Academia.edu profile URL`,
    String.raw `Catalogus Professorum Halensis`,
    String.raw `level of description`,
    String.raw `partially coincident with`,
    String.raw `terminus`,
    String.raw `vehicle`,
    String.raw `road number formatter`,
    String.raw `UCI code`,
    String.raw `terminus location`,
    String.raw `investigated by`,
    String.raw `film poster`,
    String.raw `standards body`,
    String.raw `recycling code`,
    String.raw `icon`,
    String.raw `place of detention`,
    String.raw `web feed URL`,
    String.raw `official color`,
    String.raw `significant person`,
    String.raw `grammatical gender`,
    String.raw `Exif model`,
    String.raw `Exif make`,
    String.raw `used by`,
    String.raw `IMO ship number`,
    String.raw `call sign`,
    String.raw `opponent during disputation`,
    String.raw `partner in business or sport`,
    String.raw `tonality`,
    String.raw `contributor to the creative work or subject`,
    String.raw `Wikidata usage instructions`,
    String.raw `quotation or excerpt`,
    String.raw `vessel class`,
    String.raw `speaker`,
    String.raw `child`,
    String.raw `Austrian municipality key`,
    String.raw `Iranian National Heritage registration number`,
    String.raw `MAC Address Block Large ID`,
    String.raw `heritage designation`,
    String.raw `Museofile`,
    String.raw `musical conductor`,
    String.raw `taxon rank`,
    String.raw `score method`,
    String.raw `title in HTML`,
    String.raw `narrator`,
    String.raw `asteroid taxonomy`,
    String.raw `symptoms`,
    String.raw `Danish Bibliometric Research Indicator level`,
    String.raw `source of material`,
    String.raw `Dictionary of Medieval Names from European Sources entry`,
    String.raw `PCP reference number`,
    String.raw `Irish Grid Reference`,
    String.raw `Parsons code`,
    String.raw `stage reached`,
    String.raw `reporting mark`,
    String.raw `United States Armed Forces service number`,
    String.raw `DOI`,
    String.raw `protocol`,
    String.raw `published in`,
    String.raw `results`,
    String.raw `brand`,
    String.raw `based on`,
    String.raw `Quora username`,
    String.raw `industry`,
    String.raw `charter URL`,
    String.raw `symbolizes`,
    String.raw `rating certificate ID`,
    String.raw `National Bridge Inventory Number`,
    String.raw `OKPD code of the good or service`,
    String.raw `OKPD2 code of the good or service`,
    String.raw `movement`,
    String.raw `instrument`,
    String.raw `religious name`,
    String.raw `Central Index Key`,
    String.raw `see also`,
    String.raw `location of creation`,
    String.raw `via`,
    String.raw `orientation`,
    String.raw `structure replaces`,
    String.raw `Amtrak station code`,
    String.raw `recovered by`,
    String.raw `natural product of taxon`,
    String.raw `reviewed by`,
    String.raw `contains`,
    String.raw `connects with`,
    String.raw `ammunition`,
    String.raw `kinship equivalent in SPARQL at Wikidata`,
    String.raw `AISHE code`,
    String.raw `Unicode range`,
    String.raw `CSS color keyword`,
    String.raw `type locality (geology)`,
    String.raw `art-name`,
    String.raw `M\u00F6llendorff transliteration`,
    String.raw `intended public`,
    String.raw `does not have quality`,
    String.raw `subclass of`,
    String.raw `HURDAT identifier`,
    String.raw `consecrator`,
    String.raw `ICD-O`,
    String.raw `rating`,
    String.raw `fleet or registration number`,
    String.raw `epigraph (literature)`,
    String.raw `dedicated to`,
    String.raw `IUCN protected areas category`,
    String.raw `developer`,
    String.raw `cast member`,
    String.raw `member of military unit`,
    String.raw `student`,
    String.raw `light characteristic of lighthouse`,
    String.raw `light sector`,
    String.raw `NACE code`,
    String.raw `United States Navy aircraft designation`,
    String.raw `legal citation of this text`,
    String.raw `HomoloGene ID`,
    String.raw `LIBRIS editions`,
    String.raw `Code of Household Registration and Conscription Information System (Taiwan)`,
    String.raw `lowest point`,
    String.raw `highest point`,
    String.raw `animal breed`,
    String.raw `ISCO-88 occupation code`,
    String.raw `ISCO-08 occupation code`,
    String.raw `official number of town quarter`,
    String.raw `has command line option`,
    String.raw `IIIF manifest`,
    String.raw `snap package`,
    String.raw `general manager`,
    String.raw `inspired by`,
    String.raw `record label`,
    String.raw `expression, gesture or body pose`,
    String.raw `hair color`,
    String.raw `school class`,
    String.raw `engine configuration`,
    String.raw `adjacent station`,
    String.raw `authority`,
    String.raw `Kemler code`,
    String.raw `iFixit repairability score (DEPRECATED)`,
    String.raw `partition type identifier`,
    String.raw `partition table type`,
    String.raw `Indian census area code (1991)`,
    String.raw `commander of (DEPRECATED)`,
    String.raw `generational suffix`,
    String.raw `currency symbol description`,
    String.raw `statutory purpose`,
    String.raw `residence`,
    String.raw `embed URL template`,
    String.raw `Cullum number`,
    String.raw `Scottish Charity number`,
    String.raw `post town`,
    String.raw `sitter`,
    String.raw `stepparent`,
    String.raw `column`,
    String.raw `official language`,
    String.raw `contains settlement`,
    String.raw `site of astronomical discovery`,
    String.raw `place served by transport hub`,
    String.raw `Harmonized System Code`,
    String.raw `KldB-2010 occupation code`,
    String.raw `racon signal`,
    String.raw `genomic end`,
    String.raw `chromosome`,
    String.raw `genomic assembly`,
    String.raw `genomic start`,
    String.raw `cytogenetic location`,
    String.raw `uncertainty corresponds to`,
    String.raw `original language of film or TV show`,
    String.raw `opposite of`,
    String.raw `Portable Game Notation`,
    String.raw `media franchise`,
    String.raw `street key`,
    String.raw `instrumentation`,
    String.raw `theme music`,
    String.raw `foundational text`,
    String.raw `position in Forsyth-Edwards Notation`,
    String.raw `season`,
    String.raw `uses property`,
    String.raw `stated in`,
    String.raw `influenced by`,
    String.raw `forgery after`,
    String.raw `Education Institution Identification Number`,
    String.raw `Bulbapedia article`,
    String.raw `coolant`,
    String.raw `has parts of the class`,
    String.raw `soundtrack release`,
    String.raw `International Classification for Standards`,
    String.raw `SBC-2010 occupation code`,
    String.raw `director`,
    String.raw `Air Ministry specification ID`,
    String.raw `professorship`,
    String.raw `powered by`,
    String.raw `statistical leader`,
    String.raw `product or material produced`,
    String.raw `destination point`,
    String.raw `therapeutic area`,
    String.raw `school of`,
    String.raw `trophy awarded`,
    String.raw `WALS family code`,
    String.raw `Statistics Indonesia ethnicity code`,
    String.raw `National Taxonomy of Exempt Entities code`,
    String.raw `discoverer or inventor`,
    String.raw `original network`,
    String.raw `IAAF competition category`,
    String.raw `constraint status`,
    String.raw `decays to`,
    String.raw `decay mode`,
    String.raw `ethnic group`,
    String.raw `SlideShare username`,
    String.raw `temporal range end`,
    String.raw `production company`,
    String.raw `subject item of this property`,
    String.raw `aspect ratio`,
    String.raw `CRICOS Provider Code`,
    String.raw `Party Number (Taiwan)`,
    String.raw `PubMed ID`,
    String.raw `Roman nomen gentilicium`,
    String.raw `gens`,
    String.raw `constellation`,
    String.raw `has facility`,
    String.raw `jockey`,
    String.raw `SIC code`,
    String.raw `Index Herbariorum code`,
    String.raw `anti-virus alias`,
    String.raw `participating team`,
    String.raw `OpenStreetMap zoom level`,
    String.raw `Kirshenbaum code`,
    String.raw `IPA Braille`,
    String.raw `based on heuristic`,
    String.raw `space launch vehicle`,
    String.raw `animator`,
    String.raw `substitute/deputy/replacement of office/officeholder`,
    String.raw `statement is regarded as spoiler for`,
    String.raw `ISRC`,
    String.raw `MusicBrainz recording ID`,
    String.raw `found in taxon`,
    String.raw `corporate officer`,
    String.raw `floor number`,
    String.raw `member of the deme`,
    String.raw `ISO 9:1995`,
    String.raw `charge`,
    String.raw `screenwriter`,
    String.raw `producer`,
    String.raw `original combination`,
    String.raw `after a work by`,
    String.raw `opinion joined by`,
    String.raw `law or regulation identifying number`,
    String.raw `does not have effect`,
    String.raw `Library of Congress Cultural Heritage Organizations`,
    String.raw `author of foreword`,
    String.raw `mouth of the watercourse`,
    String.raw `parent peak`,
    String.raw `trading name`,
    String.raw `tributary`,
    String.raw `lakes on river`,
    String.raw `state of use`,
    String.raw `ordered by`,
    String.raw `significant environmental impact`,
    String.raw `commemorates`,
    String.raw `offers view on`,
    String.raw `occupant`,
    String.raw `objective of project or action`,
    String.raw `programming language`,
    String.raw `territory overlaps`,
    String.raw `history of topic`,
    String.raw `BHL Page ID`,
    String.raw `International Nuclear Event Scale`,
    String.raw `parent of this hybrid, breed, or cultivar`,
    String.raw `flower color`,
    String.raw `month of the year`,
    String.raw `Deutsche Bahn station code`,
    String.raw `candidate`,
    String.raw `political coalition`,
    String.raw `open days`,
    String.raw `quantitative metrical pattern`,
    String.raw `legislated by`,
    String.raw `sibling`,
    String.raw `crew member`,
    String.raw `Consolidated code of the electronic catalog of libraries of Belarus`,
    String.raw `derivative work`,
    String.raw `capital of`,
    String.raw `page at OSTIS Belarus Wiki`,
    String.raw `RSL scanned books identifier`,
    String.raw `office held by head of the organization`,
    String.raw `Universal Decimal Classification (works and editions)`,
    String.raw `instruction set`,
    String.raw `Skype username`,
    String.raw `Australian Company Number`,
    String.raw `station class`,
    String.raw `chief executive officer`,
    String.raw `order number`,
    String.raw `edibility`,
    String.raw `OpenCorporates corporate grouping`,
    String.raw `plaintiff`,
    String.raw `house publication`,
    String.raw `teaching method`,
    String.raw `habitat`,
    String.raw `qualifies for event`,
    String.raw `maintained by`,
    String.raw `form of creative work`,
    String.raw `is a list of`,
    String.raw `writing language`,
    String.raw `charted in`,
    String.raw `takes place in fictional universe`,
    String.raw `set in period`,
    String.raw `IUCN conservation status`,
    String.raw `category contains`,
    String.raw `affiliation string`,
    String.raw `convicted of`,
    String.raw `formatter URL`,
    String.raw `medical condition treated`,
    String.raw `successful candidate`,
    String.raw `canonization status`,
    String.raw `origin of the watercourse`,
    String.raw `host`,
    String.raw `type of variable star`,
    String.raw `possessed by spirit`,
    String.raw `anatomical branch of`,
    String.raw `DSM-5 classification`,
    String.raw `software engine`,
    String.raw `statistical unit`,
    String.raw `deprecated in version`,
    String.raw `applies to people`,
    String.raw `source of energy`,
    String.raw `practiced by`,
    String.raw `category combines topics`,
    String.raw `set in environment`,
    String.raw `ancestral home`,
    String.raw `title of chess person`,
    String.raw `location of formation`,
    String.raw `Cook Partisan Voting Index`,
    String.raw `INCI name`,
    String.raw `programming paradigm`,
    String.raw `key press`,
    String.raw `introduced feature`,
    String.raw `open period from`,
    String.raw `open period to`,
    String.raw `ENI number`,
    String.raw `health specialty`,
    String.raw `intended subject of deprecated statement`,
    String.raw `season of club or team`,
    String.raw `attested in`,
    String.raw `officially opened by`,
    String.raw `samples from work`,
    String.raw `Gazette of India notification`,
    String.raw `THL Simplified Phonetic Transcription`,
    String.raw `stock exchange`,
    String.raw `curator`,
    String.raw `youth wing`,
    String.raw `record held`,
    String.raw `International Standard Industrial Classification code Rev.4`,
    String.raw `diplomatic relation`,
    String.raw `office held by head of state`,
    String.raw `designed by`,
    String.raw `official residence`,
    String.raw `school district`,
    String.raw `defendant`,
    String.raw `Library of Congress authority ID`,
    String.raw `location of first performance`,
    String.raw `cryptocurrency symbol`,
    String.raw `premiere type`,
    String.raw `cover art by`,
    String.raw `candidacy in election`,
    String.raw `exhibition history`,
    String.raw `has works in the collection`,
    String.raw `collection creator`,
    String.raw `borrowing rate`,
    String.raw `patronym or matronym for this person`,
    String.raw `has index case`,
    String.raw `perpetrator`,
    String.raw `significant place`,
    String.raw `sexual orientation`,
    String.raw `sports competition competed at`,
    String.raw `social classification`,
    String.raw `intangible cultural heritage status`,
    String.raw `second family name in Spanish name`,
    String.raw `political ideology`,
    String.raw `victim`,
    String.raw `license`,
    String.raw `capital`,
    String.raw `Möllendorff transliteration`,
    String.raw `weather history`,
    String.raw `twinned administrative body`,
    String.raw `office held by head of government`,
    String.raw `copyright status`,
    String.raw `opening time`,
    String.raw `closing time`,
    String.raw `dissertation submitted to`,
    String.raw `editor-in-chief`,
    String.raw `Dictionary of Swedish National Biography`,
    String.raw `properties for this type`,
    String.raw `Yahoo Answers category`,
    String.raw `doctoral student`,
    String.raw `target`,
    String.raw `worshipped by`,
    String.raw `patron saint`,
    String.raw `Wikidata property`,
    String.raw `definition domain`,
    String.raw `sports season of league or competition`,
    String.raw `crosses`,
    String.raw `Minitel code`,
    String.raw `printed by`,
    String.raw `Schl\u00E4fli symbol`,
    String.raw `expected completeness`,
    String.raw `NSDAP membership number (1925–1945)`,
    String.raw `defender`,
    String.raw `BALaT person/organisation id`,
    String.raw `addressee`,
    String.raw `entry in abbreviations table`,
    String.raw `PubMed Health`,
    String.raw `room number`,
    String.raw `members have occupation`,
    String.raw `base`,
    String.raw `final event`,
    String.raw `removed feature`,
    String.raw `Cooperative Patent Classification code`,
    String.raw `Formal Public Identifier`,
    String.raw `Mac OS type code`,
    String.raw `executive producer`,
    String.raw `IMDb ID`,
    String.raw `DBU playerprofile`,
    String.raw `ploidy`,
    String.raw `game mode`,
    String.raw `UN packaging group`,
    String.raw `UN code classification`,
    String.raw `general formula`,
    String.raw `molecule conformation`,
    String.raw `rector`,
    String.raw `approximation algorithm`,
    String.raw `Artsy gene`,
    String.raw `chivalric order`,
    String.raw `closed on`,
    String.raw `temporal range start`,
    String.raw `measured physical quantity`,
    String.raw `Taxonomic Literature 2 number`,
    String.raw `location of landing`,
    String.raw `people or cargo transported`,
    String.raw `volcanic explosivity index`,
    String.raw `GUI toolkit or framework`,
    String.raw `grammatical aspect`,
    String.raw `rules for classification`,
    String.raw `honorific prefix`,
    String.raw `godparent`,
    String.raw `main building contractor`,
    String.raw `location of the point of view`,
    String.raw `checksum`,
    String.raw `broader concept`,
    String.raw `copyright holder`,
    String.raw `adjacent building`,
    String.raw `CPU`,
    String.raw `librettist`,
    String.raw `film editor`,
    String.raw `culture`,
    String.raw `archives at`,
    String.raw `contributed to creative work`,
    String.raw `located in the ecclesiastical territorial entity`,
    String.raw `highway system`,
    String.raw `radio format`,
    String.raw `circle of`,
    String.raw `input set`,
    String.raw `codomain`,
    String.raw `taxonomic type`,
    String.raw `modified version of`,
    String.raw `damaged`,
    String.raw `Google Books ID`,
    String.raw `has pet`,
    String.raw `location of discovery`,
    String.raw `educational stage`,
    String.raw `epoch`,
    String.raw `pronunciation variety`,
    String.raw `presented in`,
    String.raw `ESRB rating`,
    String.raw `content descriptor`,
    String.raw `interactive elements`,
    String.raw `aircraft registration prefix`,
    String.raw `immediate cause of`,
    String.raw `anatomical location`,
    String.raw `cardinality of this set`,
    String.raw `Swiss Football Association Club Number`,
    String.raw `article ID`,
    String.raw `relevant qualification`,
    String.raw `SMARTS notation`,
    String.raw `ASIN`,
    String.raw `GEMS Code`,
    String.raw `tabular population`,
    String.raw `owner of`,
    String.raw `IM channel`,
    String.raw `website account on`,
    String.raw `IAST transliteration`,
    String.raw `guest of honor`,
    String.raw `art director`,
    String.raw `choreographer`,
    String.raw `possible creator`,
    String.raw `match interval`,
    String.raw `track gauge`,
    String.raw `notation`,
    String.raw `reservoir created`,
    String.raw `grants`,
    String.raw `Deutsche Bahn station category`,
    String.raw `permanent resident of`,
    String.raw `PEGI rating`,
    String.raw `cites work`,
    String.raw `manner of`,
    String.raw `eye color`,
    String.raw `VIAF ID`,
    String.raw `historic county`,
    String.raw `Internet Archive ID`,
    String.raw `depicted part`,
    String.raw `online service`,
    String.raw `less than`,
    String.raw `disjoint union of`,
    String.raw `medical evacuation to`,
    String.raw `presenter`,
    String.raw `GOST 7.67 cyrillic`,
    String.raw `spatial reference system`,
    String.raw `ABS ASCL code`,
    String.raw `depends on software`,
    String.raw `field of training`,
    String.raw `business model`,
    String.raw `central bank/issuer`,
    String.raw `statement describes`,
    String.raw `contributing factor of`,
    String.raw `film crew member`,
    String.raw `executive body`,
    String.raw `name of the character role`,
    String.raw `Biographical Dictionary of Swedish Women`,
    String.raw `flag`,
    String.raw `Lagrangian point`,
    String.raw `full work available at`,
    String.raw `dam`,
    String.raw `general property-based URL formatter`,
    String.raw `Unicode block`,
    String.raw `measurement scale`,
    String.raw `programmer`,
    String.raw `title of broader work`,
    String.raw `Sächsische Biografie`,
    String.raw `identifier shared with`,
    String.raw `political alignment`,
    String.raw `streak color`,
    String.raw `reward`,
    String.raw `Thibaudeau classification`,
    String.raw `reports periodicity`,
    String.raw `member category`,
    String.raw `Sandbox-Monolingual text`,
    String.raw `chord progression`,
    String.raw `possible treatment`,
    String.raw `drainage basin`,
    String.raw `RefSeq`,
    String.raw `typeface/font used`,
    String.raw `carries`,
    String.raw `TDD number`,
    String.raw `funding scheme`,
    String.raw `folio(s)`,
    String.raw `in opposition to`,
    String.raw `handedness`,
    String.raw `Dictionary of New Zealand Biography`,
    String.raw `input method`,
    String.raw `property`,
    String.raw `calculated from`,
    String.raw `admissible rule in`,
    String.raw `UNESCO Biosphere Reserve url`,
    String.raw `Latvian transcription`,
    String.raw `military casualty classification`,
    String.raw `UniProt protein ID`,
    String.raw `descriptive solubility`,
    String.raw `plot expanded in`,
    String.raw `exposure time`,
    String.raw `has edition`,
    String.raw `Roman cognomen`,
    String.raw `funder`,
    String.raw `licensed to broadcast to`,
    String.raw `Norway Import Service and Registration Authority publisher code`,
    String.raw `four-corner method`,
    String.raw `MusicBrainz artist ID`,
    String.raw `has vertex figure`,
    String.raw `discovery method`,
    String.raw `FCC Product Code`,
    String.raw `grade of kanji`,
    String.raw `Australian Classification`,
    String.raw `co-driver`,
    String.raw `illustrator`,
    String.raw `incarnation of`,
    String.raw `physically interacts with`,
    String.raw `parent astronomical body`,
    String.raw `Thomson Reuters Business Classification`,
    String.raw `item disputed by`,
    String.raw `RFE symbol`,
    String.raw `means of locomotion`,
    String.raw `structural engineer`,
    String.raw `regulated by`,
    String.raw `space group`,
    String.raw `follower of`,
    String.raw `FAO risk status`,
    String.raw `provisional house number in the Czech Republic`,
    String.raw `production designer`,
    String.raw `dialect of`,
    String.raw `complies with`,
    String.raw `hyphenation`,
    String.raw `list of episodes`,
    String.raw `key performance indicator`,
    String.raw `home port`,
    String.raw `Portuguese Job Code CPP-2010`,
    String.raw `UNDP country code`,
    String.raw `overlies`,
    String.raw `GS1 Manufacturer code`,
    String.raw `KLG Kritisches Lexikon der Gegenwartsliteratur`,
    String.raw `cell component`,
    String.raw `subsidiary`,
    String.raw `has decorative pattern`,
    String.raw `transmitted signal type`,
    String.raw `newspaper format`,
    String.raw `is pollinator of`,
    String.raw `indigenous to`,
    String.raw `UPA transcription`,
    String.raw `topic's main template`,
    String.raw `unveiled by`,
    String.raw `student organization of`,
    String.raw `by-product of`,
    String.raw `acknowledged`,
    String.raw `quotes work`,
  ],
};
