export const AllAttrsInLargeKB = [
  String.raw `face value`,
  String.raw `has parts of the class`,
  String.raw `inflation rate`,
  String.raw `longest span`,
  String.raw `luminous intensity`,
  String.raw `foreign transaction fee`,
  String.raw `fee`,
  String.raw `net worth`,
  String.raw `yard number`,
  String.raw `Pinterest username`,
  String.raw `described by source`,
  String.raw `number of matches played/races/starts`,
  String.raw `audio`,
  String.raw `wing area`,
  String.raw `road number`,
  String.raw `alcohol by volume`,
  String.raw `FIFA country code`,
  String.raw `website username`,
  String.raw `magnetic moment`,
  String.raw `rector`,
  String.raw `oxidation state`,
  String.raw `vehicles per thousand people`,
  String.raw `United States Navy aircraft designation`,
  String.raw `followed by`,
  String.raw `absolute magnitude`,
  String.raw `number of decimal digits`,
  String.raw `ballots cast`,
  String.raw `last line`,
  String.raw `awarded for period`,
  String.raw `borrowing rate`,
  String.raw `disease burden`,
  String.raw `service retirement`,
  String.raw `bore`,
  String.raw `International Standard Industrial Classification code Rev.4`,
  String.raw `age of majority`,
  String.raw `boiling point`,
  String.raw `has melody`,
  String.raw `minimum temperature record`,
  String.raw `prevalence`,
  String.raw `has cause`,
  String.raw `Mohs' hardness`,
  String.raw `Mac OS type code`,
  String.raw `size of team at finish`,
  String.raw `iFixit repairability score (DEPRECATED)`,
  String.raw `speed`,
  String.raw `Universal Decimal Classification`,
  String.raw `SBC-2010 occupation code`,
  String.raw `collection or exhibition size`,
  String.raw `name in native language`,
  String.raw `review score`,
  String.raw `Vimeo username`,
  String.raw `legislated by`,
  String.raw `author`,
  String.raw `number of parts of this work`,
  String.raw `quotation or excerpt`,
  String.raw `IOC country code`,
  String.raw `Yahoo Answers category`,
  String.raw `HURDAT identifier`,
  String.raw `legal citation of this text`,
  String.raw `numeric value`,
  String.raw `precipitation height`,
  String.raw `monogram`,
  String.raw `singles record`,
  String.raw `flattening`,
  String.raw `ISO 3166-1 alpha-2 code`,
  String.raw `position in Forsyth-Edwards Notation`,
  String.raw `country of citizenship`,
  String.raw `series ordinal`,
  String.raw `foreign direct investment net inflow`,
  String.raw `elongation at break`,
  String.raw `Caverphone`,
  String.raw `number of seasons`,
  String.raw `model year code`,
  String.raw `Air Ministry specification ID`,
  String.raw `electric charge`,
  String.raw `ceiling exposure limit`,
  String.raw `Monte Carlo Particle Number`,
  String.raw `Wikitribune category`,
  String.raw `rural population`,
  String.raw `date of death`,
  String.raw `wheelbase`,
  String.raw `external data available at`,
  String.raw `number of representations`,
  String.raw `GEMS Code`,
  String.raw `temple name`,
  String.raw `streaming media URL`,
  String.raw `archives at`,
  String.raw `practiced by`,
  String.raw `director`,
  String.raw `replaces`,
  String.raw `German district key`,
  String.raw `relative permittivity`,
  String.raw `number of losses`,
  String.raw `market capitalization`,
  String.raw `taxon name`,
  String.raw `performer`,
  String.raw `chemical structure`,
  String.raw `discharge`,
  String.raw `FIPS 5-2 numeric code (US states)`,
  String.raw `neutron number`,
  String.raw `units sold`,
  String.raw `number of negative votes`,
  String.raw `spouse`,
  String.raw `personal best`,
  String.raw `Revised Hepburn romanization`,
  String.raw `shape`,
  String.raw `party chief representative`,
  String.raw `number of viewers/listeners`,
  String.raw `cause of death`,
  String.raw `distance from Earth`,
  String.raw `adjacent station`,
  String.raw `IPA Braille`,
  String.raw `Unicode range`,
  String.raw `maximum frequency of audible sound`,
  String.raw `main subject`,
  String.raw `official website`,
  String.raw `armament`,
  String.raw `destination point`,
  String.raw `Snapchat username`,
  String.raw `USDA NDB number`,
  String.raw `highest observed lifespan`,
  String.raw `employer`,
  String.raw `LIBRIS editions`,
  String.raw `notation`,
  String.raw `media legend`,
  String.raw `narrative age`,
  String.raw `date of assent`,
  String.raw `partition coefficient water/octanol`,
  String.raw `carbon footprint`,
  String.raw `follows`,
  String.raw `beer bitterness`,
  String.raw `NIOSH Pocket Guide ID`,
  String.raw `software version identifier`,
  String.raw `stellar rotational velocity`,
  String.raw `Quora username`,
  String.raw `aircraft registration`,
  String.raw `yield strength`,
  String.raw `member count`,
  String.raw `name`,
  String.raw `attendance`,
  String.raw `statutory purpose`,
  String.raw `natural abundance`,
  String.raw `Finnish municipality number`,
  String.raw `relative position within image`,
  String.raw `number of perpetrators`,
  String.raw `Charity Commission no.`,
  String.raw `posthumous name`,
  String.raw `space group`,
  String.raw `declination`,
  String.raw `general property-based URL formatter`,
  String.raw `parallax`,
  String.raw `vehicle`,
  String.raw `candidate number`,
  String.raw `WALS lect code`,
  String.raw `route number`,
  String.raw `occupation`,
  String.raw `element symbol`,
  String.raw `binding energy`,
  String.raw `birth name`,
  String.raw `BMLO`,
  String.raw `British Museum person-institution`,
  String.raw `native label`,
  String.raw `Instagram username`,
  String.raw `FCC Product Code`,
  String.raw `page(s)`,
  String.raw `Strunz 8th edition (series ID, updated)`,
  String.raw `film poster`,
  String.raw `replaced by`,
  String.raw `Gmelin number`,
  String.raw `Unicode hex codepoint`,
  String.raw `nickname`,
  String.raw `RFE symbol`,
  String.raw `maximum age`,
  String.raw `educated at`,
  String.raw `theme music`,
  String.raw `Amsterdam code`,
  String.raw `Politika topic`,
  String.raw `powered by`,
  String.raw `set in period`,
  String.raw `caliber`,
  String.raw `instance of`,
  String.raw `crosses`,
  String.raw `editor-in-chief`,
  String.raw `Indian census area code (2011)`,
  String.raw `taxon author citation`,
  String.raw `budget`,
  String.raw `electric dipole moment`,
  String.raw `magnification`,
  String.raw `Reaxys registry number`,
  String.raw `official color`,
  String.raw `TeX string`,
  String.raw `number of platform faces`,
  String.raw `parent taxon`,
  String.raw `Gazette of India notification`,
  String.raw `standard molar entropy`,
  String.raw `diameter`,
  String.raw `recovered by`,
  String.raw `Wikidata time precision`,
  String.raw `beam`,
  String.raw `draft`,
  String.raw `PEGI rating`,
  String.raw `Linguasphere code`,
  String.raw `successful candidate`,
  String.raw `age of consent`,
  String.raw `place name sign`,
  String.raw `payload mass`,
  String.raw `quantitative metrical pattern`,
  String.raw `IRS Employer Identification Number`,
  String.raw `ICD-10-CM`,
  String.raw `UNII`,
  String.raw `Twitter hashtag`,
  String.raw `hill size`,
  String.raw `shear modulus`,
  String.raw `SlideShare username`,
  String.raw `g-factor`,
  String.raw `lowest atmospheric pressure`,
  String.raw `compression ratio`,
  String.raw `total imports`,
  String.raw `UNDP country code`,
  String.raw `Statistics Indonesia ethnicity code`,
  String.raw `inception`,
  String.raw `slope rating`,
  String.raw `heat capacity`,
  String.raw `lowest point`,
  String.raw `partially coincident with`,
  String.raw `country`,
  String.raw `aperture`,
  String.raw `KLfG Critical Dictionary of foreign contemporary literature`,
  String.raw `gyromagnetic ratio`,
  String.raw `proper motion`,
  String.raw `doctoral thesis`,
  String.raw `number of branches`,
  String.raw `has index case`,
  String.raw `ACM Classification Code (2012)`,
  String.raw `illiterate population`,
  String.raw `social media followers`,
  String.raw `architectural style`,
  String.raw `median income`,
  String.raw `uses`,
  String.raw `total assists in career`,
  String.raw `density`,
  String.raw `date of birth`,
  String.raw `gross tonnage`,
  String.raw `angular distance`,
  String.raw `admission rate`,
  String.raw `RefSeq`,
  String.raw `instruction set`,
  String.raw `total reserves`,
  String.raw `military branch`,
  String.raw `points awarded`,
  String.raw `water as percent of area`,
  String.raw `pseudonym`,
  String.raw `Catalogus Professorum Halensis`,
  String.raw `member of sports team`,
  String.raw `has vertex figure`,
  String.raw `Skype username`,
  String.raw `residence time of water`,
  String.raw `inspired by`,
  String.raw `number of masts`,
  String.raw `RTECS number`,
  String.raw `number of casualties`,
  String.raw `standard enthalpy of formation`,
  String.raw `religious name`,
  String.raw `area`,
  String.raw `stall speed`,
  String.raw `Minor Planet Center observatory code`,
  String.raw `headquarters location`,
  String.raw `CAS Registry Number`,
  String.raw `IPA number order`,
  String.raw `Elo rating`,
  String.raw `maximum Strahler number`,
  String.raw `Irish Grid Reference`,
  String.raw `period of lactation`,
  String.raw `Regensburg Classification`,
  String.raw `eligible voters`,
  String.raw `point in time`,
  String.raw `official number of town quarter`,
  String.raw `formatter URL`,
  String.raw `is a list of`,
  String.raw `number of hospitalized cases`,
  String.raw `end of covered period`,
  String.raw `serial number`,
  String.raw `ride height`,
  String.raw `start time`,
  String.raw `number of elevators`,
  String.raw `limiting oxygen index`,
  String.raw `operating area`,
  String.raw `effective firing range`,
  String.raw `UIC alphabetical country code`,
  String.raw `assets under management`,
  String.raw `century breaks`,
  String.raw `road number formatter`,
  String.raw `platform`,
  String.raw `work period (start)`,
  String.raw `RxNorm CUI`,
  String.raw `hair color`,
  String.raw `DSM-5 classification`,
  String.raw `Library of Congress Cultural Heritage Organizations`,
  String.raw `head of state`,
  String.raw `marriageable age`,
  String.raw `Google Doodle`,
  String.raw `basic reproduction number`,
  String.raw `architect`,
  String.raw `has command line option`,
  String.raw `academic degree`,
  String.raw `hydraulic head`,
  String.raw `quotes work`,
  String.raw `located in the administrative territorial entity`,
  String.raw `DOI`,
  String.raw `inscription`,
  String.raw `ISO 639-1 code`,
  String.raw `lyrics by`,
  String.raw `taxon rank`,
  String.raw `ISO 639-3 code`,
  String.raw `Swiss Football Association Club Number`,
  String.raw `OKPD2 code of the good or service`,
  String.raw `UNESCO Biosphere Reserve url`,
  String.raw `video`,
  String.raw `family name`,
  String.raw `INSEE department code`,
  String.raw `watershed area`,
  String.raw `number confirmed`,
  String.raw `language of work or name`,
  String.raw `start of covered period`,
  String.raw `time index`,
  String.raw `distribution map`,
  String.raw `Wikidata usage instructions`,
  String.raw `acknowledged`,
  String.raw `total equity`,
  String.raw `Football Money League rank`,
  String.raw `annual number of weddings`,
  String.raw `explosive energy equivalent`,
  String.raw `orbital eccentricity`,
  String.raw `Munzinger IBA`,
  String.raw `Academia.edu profile URL`,
  String.raw `canonization status`,
  String.raw `KulturNav-id`,
  String.raw `commissioned by`,
  String.raw `student of`,
  String.raw `item operated`,
  String.raw `earliest date`,
  String.raw `CIVICUS Monitor country entry`,
  String.raw `quantity`,
  String.raw `instrumentation`,
  String.raw `ISO 639-2 code`,
  String.raw `TA98 Latin term`,
  String.raw `number of parts of this work of art`,
  String.raw `vehicles per capita (1000)`,
  String.raw `sexual orientation`,
  String.raw `recorded at studio or venue`,
  String.raw `provisional house number in the Czech Republic`,
  String.raw `position angle`,
  String.raw `ICD-9`,
  String.raw `ICD-9-CM`,
  String.raw `hardness`,
  String.raw `IMO ship number`,
  String.raw `snap package`,
  String.raw `catchphrase`,
  String.raw `home world`,
  String.raw `award received`,
  String.raw `total liabilities`,
  String.raw `noble title`,
  String.raw `UN class`,
  String.raw `date of official closure`,
  String.raw `recycling code`,
  String.raw `number of subscribers`,
  String.raw `village code of Indonesia`,
  String.raw `GRIN URL`,
  String.raw `vehicle normally used`,
  String.raw `kinematic viscosity`,
  String.raw `IPTC Newscode`,
  String.raw `number of survivors`,
  String.raw `wavelength`,
  String.raw `political ideology`,
  String.raw `sectional view`,
  String.raw `INSEE municipality code`,
  String.raw `Nickel-Strunz 9th edition (updated 2009)`,
  String.raw `effective temperature`,
  String.raw `real gross domestic product growth rate`,
  String.raw `Biographical Dictionary of Swedish Women`,
  String.raw `Cook Partisan Voting Index`,
  String.raw `Party Number (Taiwan)`,
  String.raw `speed limit`,
  String.raw `periapsis`,
  String.raw `quantity symbol (string)`,
  String.raw `number of cases`,
  String.raw `compulsory education (minimum age)`,
  String.raw `duration`,
  String.raw `located at street address (DEPRECATED)`,
  String.raw `present in work`,
  String.raw `TERYT municipality code`,
  String.raw `Australian Company Number`,
  String.raw `source of energy`,
  String.raw `minimum number of players`,
  String.raw `Quebec municipalities geographical code`,
  String.raw `located in time zone`,
  String.raw `e-mail address`,
  String.raw `ESRB rating`,
  String.raw `base salary`,
  String.raw `ICPC 2 ID`,
  String.raw `file extension`,
  String.raw `average gradient`,
  String.raw `married name`,
  String.raw `compressive modulus of elasticity`,
  String.raw `year of taxon publication`,
  String.raw `power consumed`,
  String.raw `has part`,
  String.raw `earthquake magnitude on the moment magnitude scale`,
  String.raw `member of the deme`,
  String.raw `SPLASH`,
  String.raw `defined daily dose`,
  String.raw `operator`,
  String.raw `health specialty`,
  String.raw `official name`,
  String.raw `Thailand central administrative unit code`,
  String.raw `dantai code`,
  String.raw `motto text`,
  String.raw `endowment`,
  String.raw `location of landing`,
  String.raw `general formula`,
  String.raw `no-observed-adverse-effect level`,
  String.raw `director / manager`,
  String.raw `VAT-rate`,
  String.raw `sport number`,
  String.raw `local dialing code`,
  String.raw `executive producer`,
  String.raw `EC enzyme number`,
  String.raw `total assets`,
  String.raw `electoral district number`,
  String.raw `time of spacecraft orbit decay`,
  String.raw `flash point`,
  String.raw `Dictionary of New Zealand Biography`,
  String.raw `bite force quotient`,
  String.raw `Danish urban area code`,
  String.raw `food energy`,
  String.raw `median lethal dose (LD50)`,
  String.raw `demonym`,
  String.raw `career plus-minus rating`,
  String.raw `Philippine Standard Geographic Code`,
  String.raw `racon signal`,
  String.raw `total goals in career`,
  String.raw `affiliation string`,
  String.raw `elevation above sea level`,
  String.raw `child`,
  String.raw `EAGLE id`,
  String.raw `cash`,
  String.raw `f-number`,
  String.raw `maximum size or capacity`,
  String.raw `voltage`,
  String.raw `cryptocurrency symbol`,
  String.raw `Dictionary of Medieval Names from European Sources entry`,
  String.raw `significant environmental impact`,
  String.raw `OpenStreetMap tag or key`,
  String.raw `mean anomaly`,
  String.raw `writing system`,
  String.raw `Giphy username`,
  String.raw `maximum capacity`,
  String.raw `DiseasesDB`,
  String.raw `orbits completed`,
  String.raw `entry in abbreviations table`,
  String.raw `number of households`,
  String.raw `orbital inclination`,
  String.raw `nominal GDP`,
  String.raw `temperature`,
  String.raw `surface gravity`,
  String.raw `explosive velocity`,
  String.raw `conscription number`,
  String.raw `ionization energy`,
  String.raw `licence plate code`,
  String.raw `National Heritage List for England number`,
  String.raw `partition type identifier`,
  String.raw `time-weighted average exposure limit`,
  String.raw `decomposition point`,
  String.raw `languages spoken, written or signed`,
  String.raw `characters`,
  String.raw `production date`,
  String.raw `INE municipality code`,
  String.raw `Kemler code`,
  String.raw `illustrator`,
  String.raw `topographic isolation`,
  String.raw `ISBN-10`,
  String.raw `parent of this hybrid, breed, or cultivar`,
  String.raw `burial plot reference`,
  String.raw `ICAO airport code`,
  String.raw `discontinued date`,
  String.raw `Ubuntu package`,
  String.raw `ranking`,
  String.raw `general manager`,
  String.raw `Wikimedia username`,
  String.raw `spectral class`,
  String.raw `Classification of Instructional Programs code`,
  String.raw `DfE URN`,
  String.raw `Exif model`,
  String.raw `maximum peak exposure limit`,
  String.raw `foundational text`,
  String.raw `significant event`,
  String.raw `prize money`,
  String.raw `luminosity`,
  String.raw `military rank`,
  String.raw `time of earliest written record`,
  String.raw `Indian census area code (1991)`,
  String.raw `number of representatives in an organization/legislature or won in elections`,
  String.raw `flexural modulus`,
  String.raw `apoapsis`,
  String.raw `embodied energy`,
  String.raw `cruise speed`,
  String.raw `maximum glide ratio`,
  String.raw `UCI code`,
  String.raw `ISNI`,
  String.raw `member of`,
  String.raw `different from`,
  String.raw `statistical leader`,
  String.raw `Human Development Index`,
  String.raw `pressure`,
  String.raw `UIC numerical country code`,
  String.raw `solubility`,
  String.raw `Swedish Anbytarforum`,
  String.raw `Sandbox-String`,
  String.raw `place of death`,
  String.raw `IAB code`,
  String.raw `programmer`,
  String.raw `currency`,
  String.raw `number of episodes`,
  String.raw `voice actor`,
  String.raw `locator map image`,
  String.raw `use`,
  String.raw `ISO 639-5 code`,
  String.raw `opposite of`,
  String.raw `estimated value`,
  String.raw `carries`,
  String.raw `UN number`,
  String.raw `CVR number`,
  String.raw `aspect ratio`,
  String.raw `number of polling stations`,
  String.raw `highway system`,
  String.raw `Amazon author page`,
  String.raw `INSEE countries and foreign territories code`,
  String.raw `wind speed`,
  String.raw `service life`,
  String.raw `HTML entity`,
  String.raw `SIRET number`,
  String.raw `KSH code`,
  String.raw `has quality`,
  String.raw `Index Herbariorum code`,
  String.raw `water footprint`,
  String.raw `literacy rate`,
  String.raw `IUCN taxon ID`,
  String.raw `amateur radio callsign`,
  String.raw `DNB editions`,
  String.raw `doctoral student`,
  String.raw `product or material produced`,
  String.raw `parliament.uk biography pages`,
  String.raw `number of support votes`,
  String.raw `isomeric SMILES`,
  String.raw `immediately dangerous to life or health`,
  String.raw `Norwegian organisation number`,
  String.raw `folio(s)`,
  String.raw `AISHE code`,
  String.raw `Revised Romanization`,
  String.raw `chapter`,
  String.raw `melting point`,
  String.raw `father`,
  String.raw `located at street address`,
  String.raw `screenwriter`,
  String.raw `hashtag`,
  String.raw `enthalpy of vaporization`,
  String.raw `minimum age`,
  String.raw `creator`,
  String.raw `maximum thrust`,
  String.raw `heritage designation`,
  String.raw `anti-virus alias`,
  String.raw `date of baptism in early childhood`,
  String.raw `does not have part`,
  String.raw `author name string`,
  String.raw `religion`,
  String.raw `runway`,
  String.raw `software engine`,
  String.raw `minimal incubation period in humans`,
  String.raw `muzzle velocity`,
  String.raw `nominal share capital`,
  String.raw `UMLS CUI`,
  String.raw `canonical SMILES`,
  String.raw `Parsons code`,
  String.raw `publication interval`,
  String.raw `common equity tier 1 capital ratio (CETI)`,
  String.raw `tributary`,
  String.raw `approach angle`,
  String.raw `candidate`,
  String.raw `Swiss municipality code`,
  String.raw `central government debt as a percent of GDP`,
  String.raw `minimal lethal concentration`,
  String.raw `after a work by`,
  String.raw `synodic period`,
  String.raw `number of injured`,
  String.raw `number of graves`,
  String.raw `dissolved, abolished or demolished`,
  String.raw `place of detention`,
  String.raw `pinyin transliteration`,
  String.raw `track gauge`,
  String.raw `DOI prefix`,
  String.raw `unit symbol`,
  String.raw `radius`,
  String.raw `time in space`,
  String.raw `composer`,
  String.raw `maximum temperature record`,
  String.raw `Roman cognomen`,
  String.raw `political party`,
  String.raw `number of constituencies`,
  String.raw `acceptable daily intake`,
  String.raw `IUCN protected areas category`,
  String.raw `points for`,
  String.raw `GOST 7.67 cyrillic`,
  String.raw `public domain date`,
  String.raw `ISBN publisher prefix`,
  String.raw `location`,
  String.raw `flight number`,
  String.raw `Glottolog code`,
  String.raw `name in hiero markup`,
  String.raw `reporting mark`,
  String.raw `throughput`,
  String.raw `M sin i`,
  String.raw `drag coefficient`,
  String.raw `Norwegian municipality number`,
  String.raw `postal code`,
  String.raw `gens`,
  String.raw `axle track`,
  String.raw `date of commercialization`,
  String.raw `electorate`,
  String.raw `litter size`,
  String.raw `boiler pressure`,
  String.raw `salinity`,
  String.raw `account charge / subscription fee`,
  String.raw `Merchant Category Code`,
  String.raw `vocalized name`,
  String.raw `chemical formula`,
  String.raw `GDP (PPP)`,
  String.raw `Soundex`,
  String.raw `SMARTS notation`,
  String.raw `author citation (zoology)`,
  String.raw `designed by`,
  String.raw `HomoloGene ID`,
  String.raw `time of spacecraft landing`,
  String.raw `manner of death`,
  String.raw `lighthouse range`,
  String.raw `InChI`,
  String.raw `archival creator authority record at the Archives nationales`,
  String.raw `eMedicine`,
  String.raw `film editor`,
  String.raw `UN packaging group`,
  String.raw `length`,
  String.raw `Sandbox-Monolingual text`,
  String.raw `location of discovery`,
  String.raw `readership`,
  String.raw `discoverer or inventor`,
  String.raw `construction point`,
  String.raw `MAC Address Block Large ID`,
  String.raw `doubles record`,
  String.raw `structural engineer`,
  String.raw `flexural strain at break`,
  String.raw `post town`,
  String.raw `relative permeability`,
  String.raw `sports league level`,
  String.raw `Code of Household Registration and Conscription Information System (Taiwan)`,
  String.raw `M.49 code`,
  String.raw `Munzinger Sport number`,
  String.raw `number of blank votes`,
  String.raw `Harmonized System Code`,
  String.raw `earthquake magnitude on the Richter magnitude scale`,
  String.raw `MCN code`,
  String.raw `date of official opening`,
  String.raw `Erdős number`,
  String.raw `regnal ordinal`,
  String.raw `pKa`,
  String.raw `energy storage capacity`,
  String.raw `visitors per year`,
  String.raw `killed by`,
  String.raw `source of material`,
  String.raw `ISCO occupation code`,
  String.raw `weather history`,
  String.raw `McCune-Reischauer romanization`,
  String.raw `horizontal depth`,
  String.raw `compulsory education (maximum age)`,
  String.raw `LAU`,
  String.raw `Fedora package`,
  String.raw `FAO risk status`,
  String.raw `volume as quantity`,
  String.raw `part of the series`,
  String.raw `Statistics Canada Geographic code`,
  String.raw `ATC code`,
  String.raw `charge conjugation quantum number`,
  String.raw `depicts`,
  String.raw `Swedish municipality code`,
  String.raw `ICAO airline designator`,
  String.raw `chairperson`,
  String.raw `stepparent`,
  String.raw `PCP reference number`,
  String.raw `military designation`,
  String.raw `Corporate Number (Japan)`,
  String.raw `ISO 3166-3`,
  String.raw `mean lifetime`,
  String.raw `shear strength`,
  String.raw `coastline`,
  String.raw `applies to jurisdiction`,
  String.raw `mobile network code`,
  String.raw `ethnic group`,
  String.raw `metallicity`,
  String.raw `page at OSTIS Belarus Wiki`,
  String.raw `by-product of`,
  String.raw `fax number`,
  String.raw `administrative code of Indonesia`,
  String.raw `vehicle range`,
  String.raw `sponsor`,
  String.raw `focal height`,
  String.raw `sRGB color hex triplet`,
  String.raw `signatory`,
  String.raw `refractive index`,
  String.raw `semi-major axis`,
  String.raw `Cullum number`,
  String.raw `Wikidata SPARQL query equivalent`,
  String.raw `national team caps`,
  String.raw `spacecraft docking/undocking date`,
  String.raw `collection`,
  String.raw `IAAF competition category`,
  String.raw `maximum wavelength of sensitivity`,
  String.raw `WMI code`,
  String.raw `Swedish urban area code`,
  String.raw `minimum frequency of audible sound`,
  String.raw `electronegativity`,
  String.raw `work period (end)`,
  String.raw `EU VAT number`,
  String.raw `edition or translation of`,
  String.raw `JMA Magnitude`,
  String.raw `industry`,
  String.raw `Gentoo package`,
  String.raw `Library of Congress Classification (works and editions)`,
  String.raw `consecrator`,
  String.raw `position held`,
  String.raw `decays to`,
  String.raw `draft pick number`,
  String.raw `start point`,
  String.raw `Formal Public Identifier`,
  String.raw `donations`,
  String.raw `notable work`,
  String.raw `distribution format`,
  String.raw `phone number`,
  String.raw `LEM ID`,
  String.raw `foreign direct investment net outflow`,
  String.raw `Dictionary of Swedish National Biography`,
  String.raw `EDRPOU code`,
  String.raw `Library of Congress Classification`,
  String.raw `EPPO Code`,
  String.raw `volume`,
  String.raw `number of spans`,
  String.raw `CRICOS Provider Code`,
  String.raw `UTC date of spacecraft launch`,
  String.raw `thermal diffusivity`,
  String.raw `kinship equivalent in SPARQL at Wikidata`,
  String.raw `date depicted`,
  String.raw `total shots in career`,
  String.raw `memory capacity`,
  String.raw `date of disappearance`,
  String.raw `place served by transport hub`,
  String.raw `votes received`,
  String.raw `Sächsische Biografie`,
  String.raw `GS1 Manufacturer code`,
  String.raw `published in`,
  String.raw `destroyed`,
  String.raw `number of deaths`,
  String.raw `radial velocity`,
  String.raw `heart rate`,
  String.raw `median lethal dose`,
  String.raw `announcement date`,
  String.raw `turning radius`,
  String.raw `winner`,
  String.raw `unmarried partner`,
  String.raw `latest date`,
  String.raw `IPA transcription`,
  String.raw `flexural strength`,
  String.raw `first flight`,
  String.raw `political alignment`,
  String.raw `GS1 country code`,
  String.raw `parity quantum number`,
  String.raw `original language of film or TV show`,
  String.raw `electrical conductivity`,
  String.raw `GS1 Global Product Classification brick code`,
  String.raw `ISO 15924 numeric code`,
  String.raw `timezone offset`,
  String.raw `total expenditure`,
  String.raw `NIS/INS code`,
  String.raw `has pet`,
  String.raw `SSR place name number`,
  String.raw `SIREN number`,
  String.raw `genre`,
  String.raw `SIRUTA code`,
  String.raw `SIC code`,
  String.raw `par`,
  String.raw `media type`,
  String.raw `code`,
  String.raw `solar irradiance`,
  String.raw `Norway Import Service and Registration Authority publisher code`,
  String.raw `ISBN-13`,
  String.raw `NUTS code`,
  String.raw `number of spoilt votes`,
  String.raw `linear reference`,
  String.raw `cost of damage`,
  String.raw `bug tracking system`,
  String.raw `National Bridge Inventory Number`,
  String.raw `angular resolution`,
  String.raw `vapor pressure`,
  String.raw `trading fee`,
  String.raw `connecting line`,
  String.raw `floruit`,
  String.raw `ITIS TSN`,
  String.raw `non-operating temperature`,
  String.raw `tensile modulus of elasticity`,
  String.raw `consumption rate`,
  String.raw `Swedish Organization Number`,
  String.raw `operating income`,
  String.raw `pennant number`,
  String.raw `country calling code`,
  String.raw `exposure time`,
  String.raw `PO Box`,
  String.raw `age at event`,
  String.raw `participant`,
  String.raw `chief executive officer`,
  String.raw `UNSPSC Code`,
  String.raw `OS grid reference`,
  String.raw `pitting resistance equivalent number`,
  String.raw `conversion to SI unit`,
  String.raw `number of seats`,
  String.raw `date of burial or cremation`,
  String.raw `ICD-10`,
  String.raw `net profit`,
  String.raw `Deutsche Bahn station code`,
  String.raw `film crew member`,
  String.raw `consumption rate per capita`,
  String.raw `total points in career`,
  String.raw `number of clinical tests`,
  String.raw `GitHub username`,
  String.raw `nighttime view`,
  String.raw `EHAK id`,
  String.raw `female form of label`,
  String.raw `gestation period`,
  String.raw `sex or gender`,
  String.raw `RSL scanned books identifier`,
  String.raw `last update`,
  String.raw `end time`,
  String.raw `number of processor cores`,
  String.raw `wingspan`,
  String.raw `dummy value`,
  String.raw `annual energy output`,
  String.raw `call sign`,
  String.raw `Iconclass notation`,
  String.raw `number of participants`,
  String.raw `frequency of event`,
  String.raw `genome size`,
  String.raw `trunk prefix`,
  String.raw `title`,
  String.raw `observing time available`,
  String.raw `minimum wavelength of sensitivity`,
  String.raw `residence`,
  String.raw `Patientplus ID`,
  String.raw `number of volunteers`,
  String.raw `ICD-O`,
  String.raw `has works in the collection`,
  String.raw `event distance`,
  String.raw `IATA airport code`,
  String.raw `epigraph (literature)`,
  String.raw `Portuguese Job Code CPP-2010`,
  String.raw `IPv6 routing prefix`,
  String.raw `box office`,
  String.raw `number of arrests`,
  String.raw `ISO 4217 code`,
  String.raw `pronunciation`,
  String.raw `data size`,
  String.raw `number of wins`,
  String.raw `OpenStreetMap zoom level`,
  String.raw `animator`,
  String.raw `OKPD code of the good or service`,
  String.raw `ISO 15924 alpha-4 code`,
  String.raw `callsign of airline`,
  String.raw `given name`,
  String.raw `total produced`,
  String.raw `InChIKey`,
  String.raw `Gini coefficient`,
  String.raw `capacity factor`,
  String.raw `Dreadnought Project page`,
  String.raw `literal translation`,
  String.raw `Stack Exchange tag`,
  String.raw `material used`,
  String.raw `sibling`,
  String.raw `individual tax rate`,
  String.raw `ISIN`,
  String.raw `IPI name number`,
  String.raw `Universal Decimal Classification (works and editions)`,
  String.raw `organizer`,
  String.raw `UPA transcription`,
  String.raw `WALS family code`,
  String.raw `relief location map`,
  String.raw `based on`,
  String.raw `total exports`,
  String.raw `number of pages`,
  String.raw `event interval`,
  String.raw `production code`,
  String.raw `argument of periapsis`,
  String.raw `National Taxonomy of Exempt Entities code`,
  String.raw `toughness`,
  String.raw `ABS ASCL code`,
  String.raw `autoignition temperature`,
  String.raw `data transfer speed`,
  String.raw `Telegram username`,
  String.raw `copyright license`,
  String.raw `fusion enthalpy`,
  String.raw `ultimate tensile strength`,
  String.raw `country of origin`,
  String.raw `art-name`,
  String.raw `ISWC`,
  String.raw `format as a regular expression`,
  String.raw `NRHP reference number`,
  String.raw `UN/LOCODE`,
  String.raw `clearance`,
  String.raw `angle from vertical`,
  String.raw `INSEE region code`,
  String.raw `head of government`,
  String.raw `has contributing factor`,
  String.raw `main building contractor`,
  String.raw `Central Index Key`,
  String.raw `genomic start`,
  String.raw `Thibaudeau classification`,
  String.raw `second family name in Spanish name`,
  String.raw `name in kana`,
  String.raw `maximum operating altitude`,
  String.raw `color`,
  String.raw `mobile country code`,
  String.raw `surface tension`,
  String.raw `last words`,
  String.raw `soundtrack release`,
  String.raw `German municipality key`,
  String.raw `street address (DEPRECATED)`,
  String.raw `NCI Thesaurus ID`,
  String.raw `average speed`,
  String.raw `extinction date`,
  String.raw `cardinality of the group`,
  String.raw `patronym or matronym for this person`,
  String.raw `IETF language tag`,
  String.raw `shares border with`,
  String.raw `decay width`,
  String.raw `measurement scale`,
  String.raw `Indian census area code (2001)`,
  String.raw `net tonnage`,
  String.raw `IRC channel`,
  String.raw `doctoral advisor`,
  String.raw `presenter`,
  String.raw `production designer`,
  String.raw `Mastodon address`,
  String.raw `handedness`,
  String.raw `overlies`,
  String.raw `effective date`,
  String.raw `CSS color keyword`,
  String.raw `key press`,
  String.raw `mass`,
  String.raw `chromosome count`,
  String.raw `subtitle`,
  String.raw `Dewey Decimal Classification (works and editions)`,
  String.raw `mother`,
  String.raw `number of abstentions`,
  String.raw `Biografisch Portaal number`,
  String.raw `maximum gradient`,
  String.raw `beats per minute`,
  String.raw `section, verse, paragraph, or clause`,
  String.raw `total debt`,
  String.raw `floors below ground`,
  String.raw `Artsy gene`,
  String.raw `topographic prominence`,
  String.raw `number of works`,
  String.raw `publisher`,
  String.raw `ZVG number`,
  String.raw `width`,
  String.raw `number of out-of-school children`,
  String.raw `size of team at start`,
  String.raw `sitter`,
  String.raw `EC number`,
  String.raw `street key`,
  String.raw `coefficient of friction`,
  String.raw `librettist`,
  String.raw `service entry`,
  String.raw `China administrative division code`,
  String.raw `graph radius`,
  String.raw `number of missing`,
  String.raw `E number`,
  String.raw `spin quantum number`,
  String.raw `target interest rate`,
  String.raw `number of rooms`,
  String.raw `distributed by`,
  String.raw `case fatality rate`,
  String.raw `four-corner method`,
  String.raw `NLC authorities`,
  String.raw `schematic`,
  String.raw `NBN System Key`,
  String.raw `unemployment rate`,
  String.raw `number of speakers`,
  String.raw `total valid votes`,
  String.raw `cost`,
  String.raw `codename`,
  String.raw `daily patronage`,
  String.raw `male population`,
  String.raw `lower limit`,
  String.raw `number of victims of killer`,
  String.raw `apparent magnitude`,
  String.raw `file format identification pattern`,
  String.raw `street address`,
  String.raw `search formatter URL`,
  String.raw `light characteristic of lighthouse`,
  String.raw `maritime identification digits`,
  String.raw `number of players in region`,
  String.raw `CBS municipality code`,
  String.raw `cash back`,
  String.raw `station class`,
  String.raw `suicide rate`,
  String.raw `RIA Novosti reference`,
  String.raw `ticker symbol`,
  String.raw `qualifies for event`,
  String.raw `slope`,
  String.raw `Museofile`,
  String.raw `short-term exposure limit`,
  String.raw `field of work`,
  String.raw `number of houses`,
  String.raw `students count`,
  String.raw `narrative location`,
  String.raw `World Health Organisation International Nonproprietary Name`,
  String.raw `NSDAP membership number (1925–1945)`,
  String.raw `conversion to standard unit`,
  String.raw `catalog code`,
  String.raw `electron configuration`,
  String.raw `Amtrak station code`,
  String.raw `aftershocks`,
  String.raw `Sandbox-Quantity`,
  String.raw `record label`,
  String.raw `speed of sound`,
  String.raw `male form of label`,
  String.raw `airline accounting code`,
  String.raw `topic's main template`,
  String.raw `number of records`,
  String.raw `alternate names`,
  String.raw `cast member`,
  String.raw `thickness`,
  String.raw `history of topic`,
  String.raw `block size`,
  String.raw `charter URL`,
  String.raw `biobased content weight percentage`,
  String.raw `short name`,
  String.raw `average shot length`,
  String.raw `Gregorian calendar start date`,
  String.raw `mains voltage`,
  String.raw `taxonomic type`,
  String.raw `minimum wage`,
  String.raw `part of`,
  String.raw `Unicode character`,
  String.raw `DBU playerprofile`,
  String.raw `generation time`,
  String.raw `female population`,
  String.raw `scale`,
  String.raw `vertical depth`,
  String.raw `developer`,
  String.raw `NACE code`,
  String.raw `clock speed`,
  String.raw `highest point`,
  String.raw `OCLC control number`,
  String.raw `light sector`,
  String.raw `SWB editions`,
  String.raw `embed URL template`,
  String.raw `computer performance`,
  String.raw `Artists in Canada record number`,
  String.raw `incidence`,
  String.raw `German regional key`,
  String.raw `total fertility rate`,
  String.raw `subclass of`,
  String.raw `genomic end`,
  String.raw `lower flammable limit`,
  String.raw `place of burial`,
  String.raw `FIPS 10-4 (countries and regions)`,
  String.raw `stroke`,
  String.raw `edition number`,
  String.raw `GSS code (2011)`,
  String.raw `number of points/goals conceded`,
  String.raw `focal length`,
  String.raw `continent`,
  String.raw `KLG Kritisches Lexikon der Gegenwartsliteratur`,
  String.raw `named after`,
  String.raw `Enterprise number (Belgium)`,
  String.raw `frequency`,
  String.raw `number of clubs`,
  String.raw `secretary general`,
  String.raw `Name Assigning Authority Number`,
  String.raw `Iranian National Heritage registration number`,
  String.raw `Ethnologue.com language code`,
  String.raw `Roman nomen gentilicium`,
  String.raw `full work available at`,
  String.raw `mass excess`,
  String.raw `ISCO-88 occupation code`,
  String.raw `isospin quantum number`,
  String.raw `thermal conductivity`,
  String.raw `Poisson's ratio`,
  String.raw `ARCHON code`,
  String.raw `Foundational Model of Anatomy ID`,
  String.raw `trading name`,
  String.raw `cause of destruction`,
  String.raw `Cologne phonetics`,
  String.raw `INCI name`,
  String.raw `BALaT person/organisation id`,
  String.raw `field of view`,
  String.raw `Common Procurement Vocabulary`,
  String.raw `albedo`,
  String.raw `detail map`,
  String.raw `galactic longitude`,
  String.raw `from narrative universe`,
  String.raw `Italian cadastre code`,
  String.raw `floors above ground`,
  String.raw `ELSTAT geographical code`,
  String.raw `shelf life`,
  String.raw `production rate`,
  String.raw `Cooperative Patent Classification code`,
  String.raw `Debian stable package`,
  String.raw `moisture absorption`,
  String.raw `exhibition history`,
  String.raw `rotation period`,
  String.raw `galactic latitude`,
  String.raw `Thomson Reuters Business Classification`,
  String.raw `Minitel code`,
  String.raw `Austrian municipality key`,
  String.raw `input method`,
  String.raw `sports season of league or competition`,
  String.raw `fiscal/tax revenue`,
  String.raw `order number`,
  String.raw `UTC timezone offset`,
  String.raw `engine displacement`,
  String.raw `number of draws/ties`,
  String.raw `ISOCAT id`,
  String.raw `penalty minutes in career`,
  String.raw `Danish Bibliometric Research Indicator level`,
  String.raw `has immediate cause`,
  String.raw `combustion enthalpy`,
  String.raw `LinkedIn personal profile URL`,
  String.raw `time of discovery or invention`,
  String.raw `Alexa rank`,
  String.raw `edibility`,
  String.raw `flux`,
  String.raw `time to altitude`,
  String.raw `total revenue`,
  String.raw `J. Paul Getty Museum artist id`,
  String.raw `port`,
  String.raw `maximal incubation period in humans`,
  String.raw `geoshape`,
  String.raw `Latvian transcription`,
  String.raw `TDD number`,
  String.raw `color index`,
  String.raw `MeSH Code`,
  String.raw `public key fingerprint`,
  String.raw `ITU letter code`,
  String.raw `Exif make`,
  String.raw `channel number`,
  String.raw `botanist author abbreviation`,
  String.raw `angular diameter`,
  String.raw `quantity buried`,
  String.raw `family relationship degree`,
  String.raw `number of words`,
  String.raw `cytogenetic location`,
  String.raw `number of children`,
  String.raw `semi-major axis of an orbit`,
  String.raw `programming paradigm`,
  String.raw `IM channel`,
  String.raw `Australian Business Number`,
  String.raw `ENI number`,
  String.raw `Twitter username`,
  String.raw `global warming potential`,
  String.raw `Reddit username`,
  String.raw `Consolidated code of the electronic catalog of libraries of Belarus`,
  String.raw `life expectancy`,
  String.raw `graph diameter`,
  String.raw `charge`,
  String.raw `law or regulation identifying number`,
  String.raw `population`,
  String.raw `director of photography`,
  String.raw `Kirshenbaum code`,
  String.raw `age estimated by a dating method`,
  String.raw `relative`,
  String.raw `ISCO-08 occupation code`,
  String.raw `age of candidacy`,
  String.raw `nominal GDP per capita`,
  String.raw `place of birth`,
  String.raw `installed capacity`,
  String.raw `minimal lethal dose`,
  String.raw `price`,
  String.raw `terminus`,
  String.raw `number of recoveries`,
  String.raw `MAME ROM name`,
  String.raw `right ascension`,
  String.raw `IPI base code`,
  String.raw `upper limit`,
  String.raw `Vicat softening point`,
  String.raw `date of first performance`,
  String.raw `maximum number of players`,
  String.raw `programming language`,
  String.raw `first line`,
  String.raw `rate of fire`,
  String.raw `mean age`,
  String.raw `ISO 3166-2 code`,
  String.raw `Education Institution Identification Number`,
  String.raw `KldB-2010 occupation code`,
  String.raw `longitude of ascending node`,
  String.raw `feed-in tariff`,
  String.raw `perpetrator`,
  String.raw `ISO 3166-1 numeric code`,
  String.raw `fineness`,
  String.raw `Bulbapedia article`,
  String.raw `FIPS 6-4 (US counties)`,
  String.raw `means of locomotion`,
  String.raw `nominated for`,
  String.raw `galaxy morphological type`,
  String.raw `GOST 7.75–97 code`,
  String.raw `isospin z-component`,
  String.raw `significant person`,
  String.raw `NOC Occupation Code`,
  String.raw `half-life`,
  String.raw `IATA airline designator`,
  String.raw `checksum`,
  String.raw `ISO 9362 SWIFT/BIC code`,
  String.raw `patronage`,
  String.raw `home venue`,
  String.raw `founded by`,
  String.raw `subreddit`,
  String.raw `tuition fee`,
  String.raw `perimeter`,
  String.raw `fabrication method`,
  String.raw `ISO standard`,
  String.raw `transliteration`,
  String.raw `Roman praenomen`,
  String.raw `Euler characteristic`,
  String.raw `literate population`,
  String.raw `Hornbostel-Sachs classification`,
  String.raw `capital`,
  String.raw `quotation`,
  String.raw `term length of office`,
  String.raw `ISSN`,
  String.raw `producer`,
  String.raw `International Classification for Standards`,
  String.raw `egg incubation period`,
  String.raw `number of points/goals/set scored`,
  String.raw `PPP GDP per capita`,
  String.raw `dynamic viscosity`,
  String.raw `orbital period`,
  String.raw `award rationale`,
  String.raw `periapsis date`,
  String.raw `ROME Occupation Code (v3)`,
  String.raw `taxon common name`,
  String.raw `Dewey Decimal Classification`,
  String.raw `issue`,
  String.raw `ISO 3166-1 alpha-3 code`,
  String.raw `Portable Game Notation`,
  String.raw `stated as`,
  String.raw `PhilPapers topic`,
  String.raw `editor`,
  String.raw `IPv4 routing prefix`,
  String.raw `Libris-URI`,
  String.raw `official blog`,
  String.raw `operating temperature`,
  String.raw `head coach`,
  String.raw `parent organization`,
  String.raw `has edition or translation`,
  String.raw `median lethal concentration (LC50)`,
  String.raw `officeholder`,
  String.raw `specific absorption rate`,
  String.raw `ASIN`,
  String.raw `Scoville grade`,
  String.raw `inventory number`,
  String.raw `stroke count`,
  String.raw `number of representatives in an organization/legislature`,
  String.raw `Nickel-Strunz '10th ed', review of (9th ed/ 2009 update)`,
  String.raw `atomic number`,
  String.raw `Taxonomic Literature 2 number`,
  String.raw `webcam page URL`,
  String.raw `production company`,
  String.raw `NATO reporting name`,
  String.raw `UAI code`,
  String.raw `number of hospital beds`,
  String.raw `urban population`,
  String.raw `convicted of`,
  String.raw `United States Armed Forces service number`,
  String.raw `upper flammable limit`,
  String.raw `Medium username`,
  String.raw `OpenCorporates corporate grouping`,
  String.raw `Wikimedia language code`,
  String.raw `UN code classification`,
  String.raw `employees`,
  String.raw `tabular population`,
  String.raw `sound power level`,
  String.raw `GeoNames feature code`,
  String.raw `directions`,
  String.raw `takeoff roll`,
  String.raw `manufacturer`,
  String.raw `departure angle`,
  String.raw `flower color`,
  String.raw `exploitation visa number`,
  String.raw `number of registered users/contributors`,
  String.raw `prisoner count`,
  String.raw `legal form`,
  String.raw `art director`,
  String.raw `depicts Iconclass notation`,
  String.raw `redshift`,
  String.raw `publication date`,
  String.raw `autonomous system number`,
  String.raw `number of platform tracks`,
  String.raw `owned by`,
  String.raw `retirement age`,
  String.raw `used by`,
  String.raw `origin of the watercourse`,
  String.raw `filming location`,
  String.raw `Arch Linux package`,
  String.raw `Scottish Charity number`,
  String.raw `number of cylinders`,
  String.raw `OSM tag or key`,
  String.raw `original spelling`,
  String.raw `IIIF manifest`,
  String.raw `height`,
  String.raw `minimum explosive concentration`,
  String.raw `highest break`,
  String.raw `judge`,
  String.raw `CosIng number`,
  String.raw `proportion`,
  String.raw `maximum sustained winds`,
  String.raw `torque`,
  String.raw `Nupill Literatura Digital - Author`,
  String.raw `fleet or registration number`,
  String.raw `romanization of Belarusian (2007 system)`,
  String.raw `courtesy name`,
  String.raw `Australian Classification`,
  String.raw `provisional designation`,
  String.raw `PubMed Health`,
  String.raw `SOC Code (2010)`,
  String.raw `FAA airport code`,
  String.raw `UK Provider Reference Number`,
  String.raw `OLAC video game genre vocabulary`,
  String.raw `floor number`,
  String.raw `station code`,
  String.raw `eye color`,
  String.raw `FIPS 5-2 alpha code (US states)`,
  String.raw `cumulative elevation gain`,
  String.raw `Ameblo username`,
  String.raw `Brazilian municipality code`,
  String.raw `named as`,
  String.raw `aircraft registration prefix`,
  String.raw `possible treatment`
];