export const AllRelationsInSmallKB = [
  String.raw `operating area`,
  String.raw `owned by`,
  String.raw `archives at`,
  String.raw `airline hub`,
  String.raw `replaces`,
  String.raw `depicts`,
  String.raw `partner`,
  String.raw `has contributing factor`,
  String.raw `next lower rank`,
  String.raw `movement`,
  String.raw `distributor`,
  String.raw `official symbol`,
  String.raw `architect`,
  String.raw `director`,
  String.raw `mouth of the watercourse`,
  String.raw `voice actor`,
  String.raw `organizer`,
  String.raw `history of topic`,
  String.raw `rector`,
  String.raw `diplomatic relation`,
  String.raw `territory overlaps`,
  String.raw `child`,
  String.raw `honorific prefix`,
  String.raw `opposite of`,
  String.raw `licensed to broadcast to`,
  String.raw `substitute/deputy/replacement of office/officeholder`,
  String.raw `board member`,
  String.raw `terminus`,
  String.raw `partially contains`,
  String.raw `nutrient`,
  String.raw `permanent resident of`,
  String.raw `honorific suffix`,
  String.raw `child astronomical body`,
  String.raw `producer`,
  String.raw `military rank`,
  String.raw `sidekick of`,
  String.raw `set in period`,
  String.raw `replaced by`,
  String.raw `allegiance`,
  String.raw `captain`,
  String.raw `material used`,
  String.raw `language used`,
  String.raw `located on astronomical location`,
  String.raw `sports season of league or competition`,
  String.raw `soundtrack album`,
  String.raw `heritage designation`,
  String.raw `properties for this type`,
  String.raw `has effect`,
  String.raw `location of final assembly`,
  String.raw `parent club`,
  String.raw `location`,
  String.raw `facet of`,
  String.raw `risk factor`,
  String.raw `statistical leader`,
  String.raw `contributing factor of`,
  String.raw `office held by head of the organisation`,
  String.raw `exported to`,
  String.raw `present in work`,
  String.raw `worshipped by`,
  String.raw `dissertation submitted to`,
  String.raw `model item`,
  String.raw `significant person`,
  String.raw `highest judicial authority`,
  String.raw `discoverer or inventor`,
  String.raw `film distribute region`,
  String.raw `original network`,
  String.raw `field of work`,
  String.raw `geographic distribution`,
  String.raw `spouse`,
  String.raw `cause of death`,
  String.raw `head of government`,
  String.raw `continent`,
  String.raw `vehicle normally used`,
  String.raw `office contested`,
  String.raw `sport`,
  String.raw `eye color`,
  String.raw `takes place in fictional universe`,
  String.raw `record label`,
  String.raw `performer`,
  String.raw `designed by`,
  String.raw `place of birth`,
  String.raw `series spin-off`,
  String.raw `parent astronomical body`,
  String.raw `subject has role`,
  String.raw `professorship`,
  String.raw `contains administrative territorial entity`,
  String.raw `location of formation`,
  String.raw `place of publication`,
  String.raw `convicted of`,
  String.raw `official religion`,
  String.raw `part of`,
  String.raw `member of political party`,
  String.raw `language of work or name`,
  String.raw `shares border with`,
  String.raw `country of origin`,
  String.raw `superhuman feature or ability`,
  String.raw `cast member`,
  String.raw `doctoral advisor`,
  String.raw `religion`,
  String.raw `time period`,
  String.raw `source of income`,
  String.raw `costume designer`,
  String.raw `fabrication method`,
  String.raw `copyright representative`,
  String.raw `developer`,
  String.raw `family name`,
  String.raw `occupation`,
  String.raw `season starts`,
  String.raw `patron saint`,
  String.raw `narrative role`,
  String.raw `subsidiary`,
  String.raw `organisation directed from the office or person`,
  String.raw `studies`,
  String.raw `taxon rank`,
  String.raw `officially opened by`,
  String.raw `theme music`,
  String.raw `godparent`,
  String.raw `characters`,
  String.raw `languages spoken, written or signed`,
  String.raw `different from`,
  String.raw `talk show guest`,
  String.raw `participant`,
  String.raw `ethnic group`,
  String.raw `found`,
  String.raw `twinned administrative body`,
  String.raw `nominated for`,
  String.raw `award disciplines or subjects`,
  String.raw `geography of topic`,
  String.raw `award received`,
  String.raw `commissioned by`,
  String.raw `residence`,
  String.raw `affiliation`,
  String.raw `enclave within`,
  String.raw `appears in the form of`,
  String.raw `instrumentation`,
  String.raw `color`,
  String.raw `noble title`,
  String.raw `manufacturer`,
  String.raw `commander of`,
  String.raw `candidate`,
  String.raw `has dialect (DEPRECATED)`,
  String.raw `sponsor`,
  String.raw `conferred by`,
  String.raw `broadcast by`,
  String.raw `this taxon is source of`,
  String.raw `has quality`,
  String.raw `has edition`,
  String.raw `designed to carry`,
  String.raw `is a list of`,
  String.raw `presenter`,
  String.raw `uses`,
  String.raw `filming location`,
  String.raw `doctoral student`,
  String.raw `notable people with this condition`,
  String.raw `official language`,
  String.raw `director of photography`,
  String.raw `grants`,
  String.raw `studied by`,
  String.raw `student of`,
  String.raw `famous people`,
  String.raw `military conflicts`,
  String.raw `donated by`,
  String.raw `editor`,
  String.raw `author`,
  String.raw `symptom of`,
  String.raw `diaspora`,
  String.raw `does not have part`,
  String.raw `drug used for treatment`,
  String.raw `copyright holder`,
  String.raw `narrative location`,
  String.raw `chief executive officer`,
  String.raw `relative`,
  String.raw `practiced by`,
  String.raw `health specialty`,
  String.raw `military casualty classification`,
  String.raw `position held`,
  String.raw `designated as terrorist by`,
  String.raw `has immediate cause`,
  String.raw `published in`,
  String.raw `place of burial`,
  String.raw `Wikidata property`,
  String.raw `interests`,
  String.raw `airline alliance`,
  String.raw `inspired by`,
  String.raw `lyrics by`,
  String.raw `family`,
  String.raw `separated from`,
  String.raw `librettist`,
  String.raw `registered with`,
  String.raw `currency`,
  String.raw `location of discovery`,
  String.raw `stated in`,
  String.raw `tributary`,
  String.raw `creator`,
  String.raw `military branch`,
  String.raw `successful candidate`,
  String.raw `named after`,
  String.raw `main food source`,
  String.raw `kit supplier`,
  String.raw `political ideology`,
  String.raw `edition or translation of`,
  String.raw `writing system`,
  String.raw `member of sports team`,
  String.raw `legal form`,
  String.raw `capital of`,
  String.raw `appointed by`,
  String.raw `place of death`,
  String.raw `fictional universe described in`,
  String.raw `place of origin (Switzerland)`,
  String.raw `winner`,
  String.raw `penalty`,
  String.raw `after a work by`,
  String.raw `sexual orientation`,
  String.raw `owner of`,
  String.raw `official residence`,
  String.raw `feast day`,
  String.raw `art director`,
  String.raw `drafted by`,
  String.raw `located in time zone`,
  String.raw `dedicated to`,
  String.raw `ancestral home`,
  String.raw `illustrator`,
  String.raw `official color`,
  String.raw `significant event`,
  String.raw `place served by transport hub`,
  String.raw `part of the series`,
  String.raw `manner of death`,
  String.raw `platform`,
  String.raw `territory claimed by`,
  String.raw `influenced by`,
  String.raw `sibling`,
  String.raw `followed by`,
  String.raw `derivative work`,
  String.raw `participant of`,
  String.raw `conflict`,
  String.raw `film crew member`,
  String.raw `country for sport`,
  String.raw `narrator`,
  String.raw `legislative body`,
  String.raw `country of citizenship`,
  String.raw `located in or next to body of water`,
  String.raw `software engine`,
  String.raw `had as last meal`,
  String.raw `killed by`,
  String.raw `programming language`,
  String.raw `update method`,
  String.raw `home venue`,
  String.raw `has parts of the class`,
  String.raw `industry`,
  String.raw `original film format`,
  String.raw `lifestyle`,
  String.raw `contributor(s) to the creative work`,
  String.raw `applies to jurisdiction`,
  String.raw `newspaper format`,
  String.raw `filmography`,
  String.raw `medical condition`,
  String.raw `operating system`,
  String.raw `seed team`,
  String.raw `office held by head of state`,
  String.raw `symptoms`,
  String.raw `quotes work`,
  String.raw `architectural style`,
  String.raw `genre`,
  String.raw `foundational text`,
  String.raw `draft pick from school`,
  String.raw `cites`,
  String.raw `chairperson`,
  String.raw `approved by`,
  String.raw `coextensive with`,
  String.raw `public holiday`,
  String.raw `connects with`,
  String.raw `basic form of government`,
  String.raw `use`,
  String.raw `has cause`,
  String.raw `basin country`,
  String.raw `indigenous to`,
  String.raw `director/manager`,
  String.raw `production company`,
  String.raw `used by`,
  String.raw `musical conductor`,
  String.raw `production designer`,
  String.raw `start point`,
  String.raw `head of state`,
  String.raw `parent organization`,
  String.raw `instrument`,
  String.raw `source of material`,
  String.raw `professional or sports partner`,
  String.raw `follows`,
  String.raw `mascot`,
  String.raw `position played on team / speciality`,
  String.raw `item operated`,
  String.raw `culture`,
  String.raw `mother`,
  String.raw `domain of saint or deity`,
  String.raw `home world`,
  String.raw `publisher`,
  String.raw `natural product of taxon`,
  String.raw `next higher rank`,
  String.raw `office held by head of government`,
  String.raw `composer`,
  String.raw `business division`,
  String.raw `officeholder`,
  String.raw `film release region`,
  String.raw `film regional debut venue`,
  String.raw `afflicts`,
  String.raw `candidacy in election`,
  String.raw `academic degree`,
  String.raw `interested in`,
  String.raw `game mode`,
  String.raw `dialect of`,
  String.raw `located on terrain feature`,
  String.raw `based on`,
  String.raw `month of the year`,
  String.raw `collection`,
  String.raw `occupant`,
  String.raw `exclave of`,
  String.raw `lowest point`,
  String.raw `father`,
  String.raw `signatory`,
  String.raw `mountain range`,
  String.raw `distribution`,
  String.raw `work location`,
  String.raw `religious order`,
  String.raw `product or material produced`,
  String.raw `depicted by`,
  String.raw `make-up artist`,
  String.raw `employer`,
  String.raw `given name`,
  String.raw `located in the administrative territorial entity`,
  String.raw `maintained by`,
  String.raw `country`,
  String.raw `programming paradigm`,
  String.raw `native language`,
  String.raw `notable work`,
  String.raw `executive producer`,
  String.raw `member of`,
  String.raw `field of this occupation`,
  String.raw `headquarters location`,
  String.raw `original language of film or TV show`,
  String.raw `film editor`,
  String.raw `capital`,
  String.raw `operator`,
  String.raw `educated at`,
  String.raw `said to be the same as`,
  String.raw `destination point`,
  String.raw `hair color`,
  String.raw `head coach`,
  String.raw `from fictional universe`,
  String.raw `screenwriter`,
  String.raw `sex or gender`,
  String.raw `voice type`,
  String.raw `founded by`,
  String.raw `league`,
  String.raw `main subject`,
  String.raw `works in collection`,
  String.raw `student`,
  String.raw `general manager`,
  String.raw `contains settlement`,
  String.raw `has part`,
  String.raw `home port`,
  String.raw `medical treatment`,
  String.raw `political alignment`,
  String.raw `license`
];