export const AllAttrsInSmallKB = [
  String.raw `stall speed`,
  String.raw `SIRUTA code`,
  String.raw `Cologne phonetics`,
  String.raw `film poster`,
  String.raw `real gross domestic product growth rate`,
  String.raw `Biographical Dictionary of Swedish Women`,
  String.raw `demonym`,
  String.raw `UN class`,
  String.raw `Debian stable package`,
  String.raw `CVR number`,
  String.raw `admission rate`,
  String.raw `TOID`,
  String.raw `RePEc Short-ID`,
  String.raw `ICAO airport code`,
  String.raw `IPI base code`,
  String.raw `Quebec municipalities geographical code`,
  String.raw `UN number`,
  String.raw `solubility`,
  String.raw `speed of sound`,
  String.raw `NSDAP membership number (1925–1945)`,
  String.raw `Swedish Literature Bank AuthorID`,
  String.raw `Classification of Instructional Programs code`,
  String.raw `ISO 3166-1 alpha-2 code`,
  String.raw `number of deaths`,
  String.raw `sRGB color hex triplet`,
  String.raw `format as a regular expression`,
  String.raw `Giphy username`,
  String.raw `video`,
  String.raw `maritime identification digits`,
  String.raw `timezone offset`,
  String.raw `number of speakers`,
  String.raw `area`,
  String.raw `Quora username`,
  String.raw `population`,
  String.raw `nominal GDP`,
  String.raw `illiterate population`,
  String.raw `oxidation state`,
  String.raw `refractive index`,
  String.raw `time in space`,
  String.raw `transliteration`,
  String.raw `ROME Occupation Code (v3)`,
  String.raw `first flight`,
  String.raw `ABS ASCL code`,
  String.raw `Index Herbariorum code`,
  String.raw `Amtrak station code`,
  String.raw `country calling code`,
  String.raw `Norwegian municipality number`,
  String.raw `catalog code`,
  String.raw `watershed area`,
  String.raw `central government debt as a percent of GDP`,
  String.raw `combustion enthalpy`,
  String.raw `minimum explosive concentration`,
  String.raw `SIREN number`,
  String.raw `ISWC`,
  String.raw `draft`,
  String.raw `MeSH Code`,
  String.raw `airline accounting code`,
  String.raw `NIS/INS code`,
  String.raw `INE municipality code`,
  String.raw `WALS family code`,
  String.raw `diameter`,
  String.raw `KulturNav-id`,
  String.raw `exploitation visa number`,
  String.raw `Library of Congress Classification`,
  String.raw `magnetic moment`,
  String.raw `DOI prefix`,
  String.raw `IRS Employer Identification Number`,
  String.raw `AISHE code`,
  String.raw `ZVG number`,
  String.raw `INSEE region code`,
  String.raw `Revised Hepburn romanization`,
  String.raw `doubles record`,
  String.raw `MIL-STD-2525 Symbol Identification Code`,
  String.raw `total liabilities`,
  String.raw `disease burden`,
  String.raw `Amsterdam code`,
  String.raw `flash point`,
  String.raw `Glottolog code`,
  String.raw `discharge`,
  String.raw `GeoNames feature code`,
  String.raw `Indian census area code (1991)`,
  String.raw `TA98 Latin term`,
  String.raw `canonical SMILES`,
  String.raw `box office`,
  String.raw `discontinued date`,
  String.raw `Catalogus Professorum Halensis`,
  String.raw `KLfG Critical Dictionary of foreign contemporary literature`,
  String.raw `LIBRIS editions`,
  String.raw `date of birth`,
  String.raw `date of death`,
  String.raw `IPv6 routing prefix`,
  String.raw `marriageable age`,
  String.raw `pronunciation audio`,
  String.raw `located at street address (DEPRECATED)`,
  String.raw `minimal incubation period in humans`,
  String.raw `UNDP country code`,
  String.raw `RIA Novosti reference`,
  String.raw `Yahoo Answers category`,
  String.raw `angular diameter`,
  String.raw `UN packaging group`,
  String.raw `Swedish municipality code`,
  String.raw `PhilPapers topic`,
  String.raw `official blog`,
  String.raw `number of cases`,
  String.raw `ITU letter code`,
  String.raw `upper flammable limit`,
  String.raw `UNESCO Biosphere Reserve url`,
  String.raw `eligible voters`,
  String.raw `voltage`,
  String.raw `electronegativity`,
  String.raw `CosIng number`,
  String.raw `FIFA country code`,
  String.raw `HTML entity`,
  String.raw `LinkedIn personal profile URL`,
  String.raw `publication interval`,
  String.raw `periapsis`,
  String.raw `foreign direct investment net outflow`,
  String.raw `Soundex`,
  String.raw `botanist author abbreviation`,
  String.raw `German district key`,
  String.raw `edition number`,
  String.raw `official name`,
  String.raw `subtitle`,
  String.raw `boiling point`,
  String.raw `birth name`,
  String.raw `ICAO airline designator`,
  String.raw `orbital eccentricity`,
  String.raw `Education Institution Identification Number`,
  String.raw `net profit`,
  String.raw `CAS Registry Number`,
  String.raw `Dictionary of Medieval Names from European Sources entry`,
  String.raw `Universal Decimal Classification`,
  String.raw `ISCO occupation code`,
  String.raw `INSEE countries and foreign territories code`,
  String.raw `date of burial or cremation`,
  String.raw `married name`,
  String.raw `Medium username`,
  String.raw `RxNorm CUI`,
  String.raw `sports league level`,
  String.raw `depicts Iconclass notation`,
  String.raw `ISO 3166-3`,
  String.raw `Name Assigning Authority Number`,
  String.raw `ARCHON code`,
  String.raw `DOI`,
  String.raw `dynamic viscosity`,
  String.raw `EC number`,
  String.raw `NOC Occupation Code`,
  String.raw `total equity`,
  String.raw `longitude of ascending node`,
  String.raw `individual tax rate`,
  String.raw `relative permeability`,
  String.raw `FIPS 10-4 (countries and regions)`,
  String.raw `ELSTAT geographical code`,
  String.raw `Telegram username`,
  String.raw `date depicted`,
  String.raw `standard molar entropy`,
  String.raw `ISO 3166-1 alpha-3 code`,
  String.raw `ISIN`,
  String.raw `nickname`,
  String.raw `temperature`,
  String.raw `date of first performance`,
  String.raw `catchphrase`,
  String.raw `orbital period`,
  String.raw `publication date`,
  String.raw `Kemler code`,
  String.raw `beats per minute`,
  String.raw `EU VAT number`,
  String.raw `IATA airport code`,
  String.raw `fee`,
  String.raw `personal best`,
  String.raw `operating income`,
  String.raw `FAA airport code`,
  String.raw `number of graves`,
  String.raw `age of consent`,
  String.raw `CANTIC-ID`,
  String.raw `consumption rate per capita`,
  String.raw `call sign`,
  String.raw `ISO 639-3 code`,
  String.raw `volume as quantity`,
  String.raw `DNB editions`,
  String.raw `pseudonym`,
  String.raw `mass`,
  String.raw `spoken text audio`,
  String.raw `UN/LOCODE`,
  String.raw `ACM Classification Code (2012)`,
  String.raw `name in native language`,
  String.raw `taxon common name`,
  String.raw `runway`,
  String.raw `prevalence`,
  String.raw `number of houses`,
  String.raw `UIC alphabetical country code`,
  String.raw `SSR place name number`,
  String.raw `total reserves`,
  String.raw `Hornbostel-Sachs classification`,
  String.raw `media type`,
  String.raw `InChIKey`,
  String.raw `SIC code`,
  String.raw `PermID`,
  String.raw `full work available at`,
  String.raw `Austrian municipality key`,
  String.raw `time of earliest written record`,
  String.raw `fax number`,
  String.raw `net worth`,
  String.raw `Munzinger Sport number`,
  String.raw `Swiss municipality code`,
  String.raw `audio recording of the subject's spoken voice`,
  String.raw `local dialing code`,
  String.raw `melting point`,
  String.raw `Linguasphere code`,
  String.raw `patronage`,
  String.raw `NBN System Key`,
  String.raw `InChI`,
  String.raw `ISNI`,
  String.raw `Swedish Anbytarforum`,
  String.raw `volume`,
  String.raw `rural population`,
  String.raw `Bulbapedia article`,
  String.raw `Vimeo username`,
  String.raw `Ameblo username`,
  String.raw `IDLH`,
  String.raw `cash`,
  String.raw `Danish urban area code`,
  String.raw `trunk prefix`,
  String.raw `dissolved, abolished or demolished`,
  String.raw `file extension`,
  String.raw `number of subscribers`,
  String.raw `motto text`,
  String.raw `Portable Game Notation`,
  String.raw `fleet or registration number`,
  String.raw `mobile country code`,
  String.raw `ISO 639-5 code`,
  String.raw `elevation above sea level`,
  String.raw `Dewey Decimal Classification`,
  String.raw `Consolidated code of the electronic catalog of libraries of Belarus`,
  String.raw `age of candidacy`,
  String.raw `beam`,
  String.raw `radius`,
  String.raw `dantai code`,
  String.raw `mean age`,
  String.raw `time of discovery or invention`,
  String.raw `mean anomaly`,
  String.raw `term length of office`,
  String.raw `author citation (zoology)`,
  String.raw `pKa`,
  String.raw `ICD-9-CM`,
  String.raw `inflation rate`,
  String.raw `bug tracking system`,
  String.raw `salinity`,
  String.raw `Academia.edu profile URL`,
  String.raw `base salary`,
  String.raw `ISO 3166-2 code`,
  String.raw `Dictionary of Swedish National Biography`,
  String.raw `schematic`,
  String.raw `CIVICUS Monitor country entry`,
  String.raw `Merchant Category Code`,
  String.raw `flattening`,
  String.raw `ICD-10`,
  String.raw `last line`,
  String.raw `end time`,
  String.raw `total assets`,
  String.raw `UNSPSC Code`,
  String.raw `earliest date`,
  String.raw `postal code`,
  String.raw `Portuguese Job Code CPP-2010`,
  String.raw `minimum number of players`,
  String.raw `service entry`,
  String.raw `Amazon author page`,
  String.raw `FIPS 5-2 alpha code (US states)`,
  String.raw `Iconclass notation`,
  String.raw `Ethnologue.com language code`,
  String.raw `e-mail address`,
  String.raw `FIPS 5-2 numeric code (US states)`,
  String.raw `IOC country code`,
  String.raw `codename`,
  String.raw `density`,
  String.raw `McCune-Reischauer romanization`,
  String.raw `short-term exposure limit`,
  String.raw `date of official opening`,
  String.raw `awarded for period`,
  String.raw `inception`,
  String.raw `maximum number of players`,
  String.raw `United States Armed Forces service number`,
  String.raw `lower flammable limit`,
  String.raw `road number`,
  String.raw `visitors per year`,
  String.raw `public key fingerprint`,
  String.raw `number of out-of-school children`,
  String.raw `vehicles per capita (1000)`,
  String.raw `decomposition point`,
  String.raw `embodied energy`,
  String.raw `VAT-rate`,
  String.raw `sport number`,
  String.raw `charter URL`,
  String.raw `IIIF manifest`,
  String.raw `Twitter hashtag`,
  String.raw `IPv4 routing prefix`,
  String.raw `longest span`,
  String.raw `KLG Kritisches Lexikon der Gegenwartsliteratur`,
  String.raw `external data available at`,
  String.raw `vertical depth`,
  String.raw `Wikimedia username`,
  String.raw `Harmonized System Code`,
  String.raw `Reaxys registry number`,
  String.raw `streaming media URL`,
  String.raw `electorate`,
  String.raw `Central Index Key`,
  String.raw `short name`,
  String.raw `cost`,
  String.raw `annual number of weddings`,
  String.raw `OCLC control number`,
  String.raw `maximum capacity`,
  String.raw `MCN code`,
  String.raw `spectral class`,
  String.raw `WoRMS-ID`,
  String.raw `IETF language tag`,
  String.raw `ISO 15924 alpha-4 code`,
  String.raw `BMLO`,
  String.raw `Stack Exchange tag`,
  String.raw `tuition fee`,
  String.raw `M.49 code`,
  String.raw `public domain date`,
  String.raw `compressive modulus of elasticity`,
  String.raw `frequency of event`,
  String.raw `floruit`,
  String.raw `Statistics Canada Geographic code`,
  String.raw `SOC Code (2010)`,
  String.raw `monogram`,
  String.raw `NACE code`,
  String.raw `Code of Household Registration and Conscription Information System (Taiwan)`,
  String.raw `detail map`,
  String.raw `inscription`,
  String.raw `Gentoo package`,
  String.raw `IRC channel`,
  String.raw `number of seasons`,
  String.raw `Minitel code`,
  String.raw `apparent magnitude`,
  String.raw `argument of periapsis`,
  String.raw `Australian Company Number`,
  String.raw `OS grid reference`,
  String.raw `review score`,
  String.raw `work period (end)`,
  String.raw `SWB editions`,
  String.raw `orbital inclination`,
  String.raw `Irish Grid Reference`,
  String.raw `life expectancy`,
  String.raw `Swiss Football Association Club Number`,
  String.raw `Iranian National Heritage registration number`,
  String.raw `UNII`,
  String.raw `GOST 7.67 cyrillic`,
  String.raw `aircraft registration prefix`,
  String.raw `IATA airline designator`,
  String.raw `total fertility rate`,
  String.raw `first line`,
  String.raw `total produced`,
  String.raw `Corporate Number (Japan)`,
  String.raw `IAB code`,
  String.raw `located at street address`,
  String.raw `TERYT municipality code`,
  String.raw `floors above ground`,
  String.raw `urban population`,
  String.raw `ISBN-13`,
  String.raw `Wine AppDB-ID`,
  String.raw `parliament.uk biography pages`,
  String.raw `minimum frequency of audible sound`,
  String.raw `China administrative division code`,
  String.raw `SPLASH`,
  String.raw `number of participants`,
  String.raw `element symbol`,
  String.raw `PictoRight ID-Droit de suite`,
  String.raw `weather history`,
  String.raw `relief location map`,
  String.raw `German municipality key`,
  String.raw `name`,
  String.raw `prize money`,
  String.raw `heart rate`,
  String.raw `Fedora package`,
  String.raw `ISSN`,
  String.raw `number of spans`,
  String.raw `start time`,
  String.raw `IPTC Newscode`,
  String.raw `PCP reference number`,
  String.raw `water footprint`,
  String.raw `British Museum person-institution`,
  String.raw `Dreadnought Project page`,
  String.raw `autoignition temperature`,
  String.raw `compulsory education (minimum age)`,
  String.raw `name in kana`,
  String.raw `National Bridge Inventory Number`,
  String.raw `Erdős number`,
  String.raw `number of representatives in an organization/legislature`,
  String.raw `ionization energy`,
  String.raw `ISO 4217 code`,
  String.raw `INSEE municipality code`,
  String.raw `semi-major axis`,
  String.raw `male population`,
  String.raw `Gmelin number`,
  String.raw `series ordinal`,
  String.raw `distance from Earth`,
  String.raw `Biografisch Portaal number`,
  String.raw `units sold`,
  String.raw `Mastodon address`,
  String.raw `inventory number`,
  String.raw `point in time`,
  String.raw `GS1 country code`,
  String.raw `native label`,
  String.raw `atomic number`,
  String.raw `TeX string`,
  String.raw `yard number`,
  String.raw `UIC numerical country code`,
  String.raw `GitHub username`,
  String.raw `clearance`,
  String.raw `incidence`,
  String.raw `female population`,
  String.raw `eMedicine`,
  String.raw `Brazilian municipality code`,
  String.raw `ICD-O`,
  String.raw `unemployment rate`,
  String.raw `ISO 15924 numeric code`,
  String.raw `average shot length`,
  String.raw `Statistics Indonesia ethnicity code`,
  String.raw `PO Box`,
  String.raw `number of seats`,
  String.raw `literate population`,
  String.raw `religious name`,
  String.raw `GEMS Code`,
  String.raw `Parsons code`,
  String.raw `SlideShare username`,
  String.raw `WALS lect code`,
  String.raw `ISO 9362 SWIFT/BIC code`,
  String.raw `work period (start)`,
  String.raw `ISO 639-1 code`,
  String.raw `OKPD2 code of the good or service`,
  String.raw `quantity buried`,
  String.raw `Caverphone`,
  String.raw `thermal conductivity`,
  String.raw `tabular population`,
  String.raw `Norwegian organisation number`,
  String.raw `autonomous system number`,
  String.raw `callsign of airline`,
  String.raw `standard enthalpy of formation`,
  String.raw `page(s)`,
  String.raw `MAME ROM name`,
  String.raw `member count`,
  String.raw `number of children`,
  String.raw `KldB-2010 occupation code`,
  String.raw `PubChem CID`,
  String.raw `production date`,
  String.raw `age of majority`,
  String.raw `Nupill Literatura Digital - Author`,
  String.raw `water as percent of area`,
  String.raw `Politika topic`,
  String.raw `Artists in Canada record number`,
  String.raw `singles record`,
  String.raw `synodic period`,
  String.raw `Enterprise number (Belgium)`,
  String.raw `ISO 3166-1 numeric code`,
  String.raw `SIRET number`,
  String.raw `OLAC video game genre vocabulary`,
  String.raw `ISO standard`,
  String.raw `metallicity`,
  String.raw `number of episodes`,
  String.raw `residence time of water`,
  String.raw `number of parts of this work of art`,
  String.raw `mains voltage`,
  String.raw `total exports`,
  String.raw `GS1 Global Product Classification brick code`,
  String.raw `Libris-URI`,
  String.raw `International Standard Industrial Classification code Rev.4`,
  String.raw `Twitter username`,
  String.raw `luminosity`,
  String.raw `attendance`,
  String.raw `median income`,
  String.raw `IDESCAT territorial code in Catalonia`,
  String.raw `Artsy gene`,
  String.raw `Cullum number`,
  String.raw `albedo`,
  String.raw `Party Number (Taiwan)`,
  String.raw `rotation period`,
  String.raw `quantity`,
  String.raw `Indian census area code (2011)`,
  String.raw `GOST 7.75–97 code`,
  String.raw `INSEE department code`,
  String.raw `GS1 Manufacturer code`,
  String.raw `fiscal/tax revenue`,
  String.raw `German regional key`,
  String.raw `FIPS 6-4 (US counties)`,
  String.raw `Gini coefficient`,
  String.raw `RTECS number`,
  String.raw `distribution map`,
  String.raw `foreign direct investment net inflow`,
  String.raw `consumption rate`,
  String.raw `date of baptism in early childhood`,
  String.raw `speed`,
  String.raw `GRIN URL`,
  String.raw `LAU`,
  String.raw `OSM tag or key`,
  String.raw `EPPO Code`,
  String.raw `PlantList-ID`,
  String.raw `DiseasesDB`,
  String.raw `Deutsche Synchronkartei actor-ID`,
  String.raw `number of elevators`,
  String.raw `Charity Commission no.`,
  String.raw `official website`,
  String.raw `event distance`,
  String.raw `duration`,
  String.raw `IPI name number`,
  String.raw `subreddit`,
  String.raw `Thailand central administrative unit code`,
  String.raw `Wikimedia language code`,
  String.raw `DfE URN`,
  String.raw `World Health Organisation International Nonproprietary Name`,
  String.raw `archival creator authority record at the Archives nationales`,
  String.raw `British Museum bioID`,
  String.raw `ASIN`,
  String.raw `ICD-9`,
  String.raw `Philippine Standard Geographic Code`,
  String.raw `Museofile`,
  String.raw `number of constituencies`,
  String.raw `retirement age`,
  String.raw `ResearcherID`,
  String.raw `Italian cadastre code`,
  String.raw `phone number`,
  String.raw `nighttime view`,
  String.raw `ISBN-10`,
  String.raw `DSM-5 classification`,
  String.raw `electrical conductivity`,
  String.raw `Regensburg Classification`,
  String.raw `WOEID`,
  String.raw `ISBN publisher prefix`,
  String.raw `NLC authorities`,
  String.raw `OpenCorporates corporate grouping`,
  String.raw `Dictionary of New Zealand Biography`,
  String.raw `ISO 639-2 code`,
  String.raw `Human Development Index`,
  String.raw `ITIS TSN`,
  String.raw `suicide rate`,
  String.raw `Finnish municipality number`,
  String.raw `vapor pressure`,
  String.raw `UMLS CUI`,
  String.raw `width`,
  String.raw `students count`,
  String.raw `EDRPOU code`,
  String.raw `chemical structure`,
  String.raw `absolute magnitude`,
  String.raw `GDP (PPP)`,
  String.raw `price`,
  String.raw `PPP GDP per capita`,
  String.raw `Snapchat username`,
  String.raw `maximal incubation period in humans`,
  String.raw `last words`,
  String.raw `market capitalization`,
  String.raw `NRHP reference number`,
  String.raw `snap package`,
  String.raw `UK Provider Reference Number`,
  String.raw `ranking`,
  String.raw `total goals in career`,
  String.raw `nominal GDP per capita`,
  String.raw `sectional view`,
  String.raw `CBS municipality code`,
  String.raw `post town`,
  String.raw `Revised Romanization`,
  String.raw `production code`,
  String.raw `ATC code`,
  String.raw `height`,
  String.raw `PubMed Health`,
  String.raw `Ubuntu package`,
  String.raw `Minor Planet Center observatory code`,
  String.raw `Norway Import Service and Registration Authority publisher code`,
  String.raw `channel number`,
  String.raw `E number`,
  String.raw `Scottish Charity number`,
  String.raw `ceiling exposure limit`,
  String.raw `Australian Business Number`,
  String.raw `OKPD code of the good or service`,
  String.raw `Nintendo GameID`,
  String.raw `Reddit username`,
  String.raw `administrative code of Indonesia`,
  String.raw `apoapsis`,
  String.raw `Common Procurement Vocabulary`,
  String.raw `time-weighted average exposure limit`,
  String.raw `minimum age`,
  String.raw `floors below ground`,
  String.raw `Alexa rank`,
  String.raw `maximum frequency of audible sound`,
  String.raw `Google Doodle`,
  String.raw `Pinterest username`,
  String.raw `median lethal dose`,
  String.raw `USDA NDB number`,
  String.raw `budget`,
  String.raw `Arch Linux package`,
  String.raw `total expenditure`,
  String.raw `collection or exhibition size`,
  String.raw `employees`,
  String.raw `taxon name`,
  String.raw `Munzinger IBA`,
  String.raw `compulsory education (maximum age)`,
  String.raw `Instagram username`,
  String.raw `KSH code`,
  String.raw `place name sign`,
  String.raw `amateur radio callsign`,
  String.raw `Sächsische Biografie`,
  String.raw `Swedish Organization Number`,
  String.raw `Wikitribune category`,
  String.raw `GSS code (2011)`,
  String.raw `speed limit`,
  String.raw `NUTS code`,
  String.raw `total revenue`,
  String.raw `perimeter`,
  String.raw `DBU playerprofile`,
  String.raw `title`,
  String.raw `webcam page URL`,
  String.raw `chemical formula`,
  String.raw `licence plate code`,
  String.raw `time index`,
  String.raw `vocalized name`,
  String.raw `length`,
  String.raw `Swedish urban area code`,
  String.raw `UAI code`,
  String.raw `ICD-10-CM`,
  String.raw `National Heritage List for England number`,
  String.raw `IMO ship number`,
  String.raw `SBC-2010 occupation code`,
  String.raw `number of households`,
  String.raw `CRICOS Provider Code`,
  String.raw `number of pages`,
  String.raw `Library of Congress Cultural Heritage Organizations`,
  String.raw `defined daily dose`,
  String.raw `CLARA-ID`,
  String.raw `Indian census area code (2001)`
];