export const AllQualifiersInSmallKB = [
  String.raw `religion`,
  String.raw `instrument`,
  String.raw `operating area`,
  String.raw `number confirmed`,
  String.raw `OSM tag or key`,
  String.raw `award rationale`,
  String.raw `time period`,
  String.raw `valid in period`,
  String.raw `conscription number`,
  String.raw `nickname`,
  String.raw `writing system`,
  String.raw `member of sports team`,
  String.raw `applies to part`,
  String.raw `directions`,
  String.raw `official website`,
  String.raw `replaces`,
  String.raw `duration`,
  String.raw `temperature`,
  String.raw `occupation`,
  String.raw `follows`,
  String.raw `instance of`,
  String.raw `publication date`,
  String.raw `acquisition transaction`,
  String.raw `described by source`,
  String.raw `solvent`,
  String.raw `appointed by`,
  String.raw `position played on team / speciality`,
  String.raw `item operated`,
  String.raw `route of administration`,
  String.raw `mother`,
  String.raw `publisher`,
  String.raw `quote`,
  String.raw `located on street`,
  String.raw `sRGB color hex triplet`,
  String.raw `EThOS thesis ID`,
  String.raw `format as a regular expression`,
  String.raw `winner`,
  String.raw `penalty`,
  String.raw `nominee`,
  String.raw `voice actor`,
  String.raw `based on heuristic`,
  String.raw `timezone offset`,
  String.raw `applies to taxon`,
  String.raw `grammatical gender`,
  String.raw `pseudonym`,
  String.raw `number of speakers`,
  String.raw `organizer`,
  String.raw `composer`,
  String.raw `located at street address`,
  String.raw `population`,
  String.raw `draft pick number`,
  String.raw `together with`,
  String.raw `languages spoken, written or signed`,
  String.raw `running mate`,
  String.raw `different from`,
  String.raw `name in native language`,
  String.raw `burial plot reference`,
  String.raw `transliteration`,
  String.raw `direction relative to location`,
  String.raw `maximum value`,
  String.raw `image`,
  String.raw `highest income threshold`,
  String.raw `memory capacity`,
  String.raw `twinned administrative body`,
  String.raw `stated as`,
  String.raw `drafted by`,
  String.raw `of`,
  String.raw `academic degree`,
  String.raw `award received`,
  String.raw `subject item of this property`,
  String.raw `located in time zone`,
  String.raw `valid in place`,
  String.raw `prize money`,
  String.raw `points for`,
  String.raw `literal translation`,
  String.raw `country calling code`,
  String.raw `name`,
  String.raw `author name string`,
  String.raw `located on terrain feature`,
  String.raw `catalog code`,
  String.raw `affiliation`,
  String.raw `place of marriage`,
  String.raw `conversion to standard unit`,
  String.raw `reason for deprecation`,
  String.raw `start time`,
  String.raw `named by`,
  String.raw `manufacturer`,
  String.raw `year of taxon name publication`,
  String.raw `regular expression syntax`,
  String.raw `diplomatic mission sent`,
  String.raw `conferred by`,
  String.raw `collection`,
  String.raw `excluding`,
  String.raw `significant event`,
  String.raw `identity of subject in context`,
  String.raw `lowest income threshold`,
  String.raw `name in kana`,
  String.raw `sourcing circumstances`,
  String.raw `end cause`,
  String.raw `military rank`,
  String.raw `head of state`,
  String.raw `part of the series`,
  String.raw `has quality`,
  String.raw `width`,
  String.raw `has edition`,
  String.raw `lowest point`,
  String.raw `platform`,
  String.raw `filming location`,
  String.raw `influenced by`,
  String.raw `proxy`,
  String.raw `male population`,
  String.raw `intended public`,
  String.raw `alternate names`,
  String.raw `replaced by`,
  String.raw `ranking`,
  String.raw `series ordinal`,
  String.raw `dissolved, abolished or demolished`,
  String.raw `for work`,
  String.raw `number of subscribers`,
  String.raw `captain`,
  String.raw `material used`,
  String.raw `votes received`,
  String.raw `inventory number`,
  String.raw `distribution`,
  String.raw `point in time`,
  String.raw `followed by`,
  String.raw `applies to name`,
  String.raw `stated age at event`,
  String.raw `religious order`,
  String.raw `applies to people`,
  String.raw `Revised Hepburn romanization`,
  String.raw `Revised Romanization`,
  String.raw `conflict`,
  String.raw `elevation above sea level`,
  String.raw `heritage designation`,
  String.raw `legislative body`,
  String.raw `has effect`,
  String.raw `country of citizenship`,
  String.raw `employer`,
  String.raw `female population`,
  String.raw `refine date`,
  String.raw `located in the administrative territorial entity`,
  String.raw `located in or next to body of water`,
  String.raw `location`,
  String.raw `mapping relation type`,
  String.raw `Brazilian municipality code`,
  String.raw `country`,
  String.raw `archive date`,
  String.raw `donated by`,
  String.raw `editor`,
  String.raw `native language`,
  String.raw `pinyin transliteration`,
  String.raw `author`,
  String.raw `pressure`,
  String.raw `parliamentary term`,
  String.raw `identity of object in context`,
  String.raw `killed by`,
  String.raw `member of`,
  String.raw `discontinued date`,
  String.raw `addressee`,
  String.raw `tributary orientation`,
  String.raw `day in year for periodic occurrence`,
  String.raw `headquarters location`,
  String.raw `present in work`,
  String.raw `highest point`,
  String.raw `represented by`,
  String.raw `type of kinship`,
  String.raw `academic major`,
  String.raw `retrieved`,
  String.raw `minimum quantity`,
  String.raw `date of death`,
  String.raw `date of birth`,
  String.raw `end time`,
  String.raw `review score by`,
  String.raw `earliest date`,
  String.raw `operator`,
  String.raw `postal code`,
  String.raw `located at street address (DEPRECATED)`,
  String.raw `nature of statement`,
  String.raw `page(s)`,
  String.raw `capital`,
  String.raw `frequency`,
  String.raw `position held`,
  String.raw `educated at`,
  String.raw `said to be the same as`,
  String.raw `destination point`,
  String.raw `direction`,
  String.raw `original network`,
  String.raw `character role`,
  String.raw `field of work`,
  String.raw `determination method`,
  String.raw `criterion used`,
  String.raw `catalog`,
  String.raw `applies to jurisdiction`,
  String.raw `subclass of`,
  String.raw `medical condition`,
  String.raw `spouse`,
  String.raw `street number`,
  String.raw `number of matches played/races/starts`,
  String.raw `cause of death`,
  String.raw `object has role`,
  String.raw `has immediate cause`,
  String.raw `published in`,
  String.raw `operating system`,
  String.raw `rating`,
  String.raw `maximum age`,
  String.raw `sport`,
  String.raw `named as`,
  String.raw `number of points/goals/set scored`,
  String.raw `McCune-Reischauer romanization`,
  String.raw `court`,
  String.raw `ISO standard`,
  String.raw `inception`,
  String.raw `sex or gender`,
  String.raw `statement is subject of`,
  String.raw `lyrics by`,
  String.raw `performer`,
  String.raw `number of episodes`,
  String.raw `genre`,
  String.raw `voice type`,
  String.raw `foundational text`,
  String.raw `statement disputed by`,
  String.raw `cabinet`,
  String.raw `official name`,
  String.raw `subtitle`,
  String.raw `central bank/issuer`,
  String.raw `main subject`,
  String.raw `subject has role`,
  String.raw `last update`,
  String.raw `separated from`,
  String.raw `latest date`,
  String.raw `upper limit`,
  String.raw `lower limit`,
  String.raw `sport number`,
  String.raw `quantity`,
  String.raw `currency`,
  String.raw `title`,
  String.raw `approved by`,
  String.raw `has part`,
  String.raw `licence plate code`,
  String.raw `pronunciation variety`,
  String.raw `contains administrative territorial entity`,
  String.raw `statement supported by`,
  String.raw `proportion`,
  String.raw `start period`,
  String.raw `place of publication`,
  String.raw `external data available at`,
  String.raw `stated in`,
  String.raw `location of formation`,
  String.raw `elected in`,
  String.raw `length`,
  String.raw `part of`,
  String.raw `basic form of government`,
  String.raw `married name`,
  String.raw `taxon author`,
  String.raw `Möllendorff transliteration`,
  String.raw `short name`,
  String.raw `member of political party`,
  String.raw `main regulatory text`,
  String.raw `use`,
  String.raw `has cause`,
  String.raw `language of work or name`,
  String.raw `creator`,
  String.raw `DOI`,
  String.raw `number of households`,
  String.raw `start point`,
  String.raw `military branch`,
  String.raw `doctoral thesis`,
  String.raw `used by`,
  String.raw `license`,
  String.raw `relative to`,
  String.raw `doctoral advisor`,
  String.raw `named after`,
  String.raw `phase of matter`,
  String.raw `name of the character role`
];