export const KeysInSmallKB = {
  quantity: [
    String.raw `total fertility rate`,
    String.raw `inflation rate`,
    String.raw `marriageable age`,
    String.raw `area`,
    String.raw `number of out-of-school children`,
    String.raw `age of majority`,
    String.raw `population`,
    String.raw `Human Development Index`,
    String.raw `PPP GDP per capita`,
    String.raw `real gross domestic product growth rate`,
    String.raw `GDP (PPP)`,
    String.raw `total reserves`,
    String.raw `nominal GDP per capita`,
    String.raw `nominal GDP`,
    String.raw `mains voltage`,
    String.raw `frequency`,
    String.raw `life expectancy`,
    String.raw `unemployment rate`,
    String.raw `number of episodes`,
    String.raw `number of seasons`,
    String.raw `number of subscribers`,
    String.raw `duration`,
    String.raw `ranking`,
    String.raw `points for`,
    String.raw `number of matches played/races/starts`,
    String.raw `number of points/goals/set scored`,
    String.raw `box office`,
    String.raw `cost`,
    String.raw `budget`,
    String.raw `height`,
    String.raw `number of children`,
    String.raw `compulsory education (maximum age)`,
    String.raw `compulsory education (minimum age)`,
    String.raw `retirement age`,
    String.raw `elevation above sea level`,
    String.raw `number of speakers`,
    String.raw `net worth`,
    String.raw `water as percent of area`,
    String.raw `vehicles per capita (1000)`,
    String.raw `Gini coefficient`,
    String.raw `suicide rate`,
    String.raw `male population`,
    String.raw `female population`,
    String.raw `median income`,
    String.raw `proportion`,
    String.raw `prize money`,
    String.raw `students count`,
    String.raw `employees`,
    String.raw `attendance`,
    String.raw `price`,
    String.raw `annual number of weddings`,
    String.raw `voltage`,
    String.raw `mass`,
    String.raw `operating income`,
    String.raw `net profit`,
    String.raw `market capitalization`,
    String.raw `total revenue`,
    String.raw `total assets`,
    String.raw `individual tax rate`,
    String.raw `highest income threshold`,
    String.raw `lowest income threshold`,
    String.raw `VAT-rate`,
    String.raw `number of deaths`,
    String.raw `quantity`,
    String.raw `incidence`,
    String.raw `number of seats`,
    String.raw `speed limit`,
    String.raw `length`,
    String.raw `perimeter`,
    String.raw `age of candidacy`,
    String.raw `central government debt as a percent of GDP`,
    String.raw `width`,
    String.raw `Erdős number`,
    String.raw `visitors per year`,
    String.raw `maximum number of players`,
    String.raw `minimum number of players`,
    String.raw `admission rate`,
    String.raw `age of consent`,
    String.raw `argument of periapsis`,
    String.raw `periapsis`,
    String.raw `orbital eccentricity`,
    String.raw `synodic period`,
    String.raw `albedo`,
    String.raw `radius`,
    String.raw `longitude of ascending node`,
    String.raw `orbital inclination`,
    String.raw `orbital period`,
    String.raw `flattening`,
    String.raw `apparent magnitude`,
    String.raw `apoapsis`,
    String.raw `distance from Earth`,
    String.raw `semi-major axis`,
    String.raw `mean age`,
    String.raw `number of households`,
    String.raw `diameter`,
    String.raw `magnetic moment`,
    String.raw `volume as quantity`,
    String.raw `mean anomaly`,
    String.raw `member count`,
    String.raw `total equity`,
    String.raw `total liabilities`,
    String.raw `timezone offset`,
    String.raw `number of parts of this work of art`,
    String.raw `maximum age`,
    String.raw `minimum quantity`,
    String.raw `maximum value`,
    String.raw `number of representatives in an organization/legislature`,
    String.raw `term length of office`,
    String.raw `tuition fee`,
    String.raw `upper limit`,
    String.raw `lower limit`,
    String.raw `patronage`,
    String.raw `urban population`,
    String.raw `rural population`,
    String.raw `temperature`,
    String.raw `vertical depth`,
    String.raw `fee`,
    String.raw `total exports`,
    String.raw `residence time of water`,
    String.raw `number of participants`,
    String.raw `base salary`,
    String.raw `total goals in career`,
    String.raw `maximum capacity`,
    String.raw `number confirmed`,
    String.raw `water footprint`,
    String.raw `frequency of event`,
    String.raw `sports league level`,
    String.raw `foreign direct investment net outflow`,
    String.raw `foreign direct investment net inflow`,
    String.raw `votes received`,
    String.raw `Alexa rank`,
    String.raw `average shot length`,
    String.raw `stated age at event`,
    String.raw `units sold`,
    String.raw `minimal incubation period in humans`,
    String.raw `maximal incubation period in humans`,
    String.raw `number of cases`,
    String.raw `watershed area`,
    String.raw `vapor pressure`,
    String.raw `time-weighted average exposure limit`,
    String.raw `solubility`,
    String.raw `minimum explosive concentration`,
    String.raw `melting point`,
    String.raw `decomposition point`,
    String.raw `median lethal dose`,
    String.raw `density`,
    String.raw `electronegativity`,
    String.raw `atomic number`,
    String.raw `oxidation state`,
    String.raw `number of pages`,
    String.raw `disease burden`,
    String.raw `prevalence`,
    String.raw `pKa`,
    String.raw `discharge`,
    String.raw `time index`,
    String.raw `ceiling exposure limit`,
    String.raw `short-term exposure limit`,
    String.raw `IDLH`,
    String.raw `boiling point`,
    String.raw `pressure`,
    String.raw `ionization energy`,
    String.raw `speed of sound`,
    String.raw `combustion enthalpy`,
    String.raw `standard molar entropy`,
    String.raw `standard enthalpy of formation`,
    String.raw `autoignition temperature`,
    String.raw `upper flammable limit`,
    String.raw `lower flammable limit`,
    String.raw `refractive index`,
    String.raw `flash point`,
    String.raw `event distance`,
    String.raw `fiscal/tax revenue`,
    String.raw `electorate`,
    String.raw `total produced`,
    String.raw `number of houses`,
    String.raw `floors below ground`,
    String.raw `floors above ground`,
    String.raw `number of elevators`,
    String.raw `thermal conductivity`,
    String.raw `compressive modulus of elasticity`,
    String.raw `conversion to standard unit`,
    String.raw `defined daily dose`,
    String.raw `time in space`,
    String.raw `number of graves`,
    String.raw `electrical conductivity`,
    String.raw `cash`,
    String.raw `quantity buried`,
    String.raw `dynamic viscosity`,
    String.raw `rotation period`,
    String.raw `absolute magnitude`,
    String.raw `angular diameter`,
    String.raw `luminosity`,
    String.raw `metallicity`,
    String.raw `number of spans`,
    String.raw `clearance`,
    String.raw `longest span`,
    String.raw `publication interval`,
    String.raw `total expenditure`,
    String.raw `eligible voters`,
    String.raw `salinity`,
    String.raw `collection or exhibition size`,
    String.raw `number of constituencies`,
    String.raw `memory capacity`,
    String.raw `heart rate`,
    String.raw `embodied energy`,
    String.raw `relative permeability`,
    String.raw `minimum age`,
    String.raw `stall speed`,
    String.raw `consumption rate per capita`,
    String.raw `consumption rate`,
    String.raw `speed`,
    String.raw `illiterate population`,
    String.raw `literate population`,
    String.raw `maximum frequency of audible sound`,
    String.raw `minimum frequency of audible sound`,
    String.raw `personal best`,
    String.raw `beats per minute`,
    String.raw `draft`,
    String.raw `beam`,
  ],
  date: [
    String.raw `point in time`,
    String.raw `inception`,
    String.raw `start time`,
    String.raw `end time`,
    String.raw `date of birth`,
    String.raw `publication date`,
    String.raw `work period (start)`,
    String.raw `date of death`,
    String.raw `retrieved`,
    String.raw `work period (end)`,
    String.raw `date of first performance`,
    String.raw `latest date`,
    String.raw `earliest date`,
    String.raw `time of earliest written record`,
    String.raw `dissolved, abolished or demolished`,
    String.raw `date of official opening`,
    String.raw `date of burial or cremation`,
    String.raw `production date`,
    String.raw `date of baptism in early childhood`,
    String.raw `discontinued date`,
    String.raw `date depicted`,
    String.raw `public domain date`,
    String.raw `awarded for period`,
    String.raw `year of taxon name publication`,
    String.raw `time of discovery or invention`,
    String.raw `last update`,
    String.raw `first flight`,
    String.raw `archive date`,
    String.raw `service entry`,
    String.raw `floruit`,
  ],
  string: [
    String.raw `determination method`,
    String.raw `maritime identification digits`,
    String.raw `CIVICUS Monitor country entry`,
    String.raw `applies to part`,
    String.raw `short name`,
    String.raw `instance of`,
    String.raw `demonym`,
    String.raw `sex or gender`,
    String.raw `ISO 3166-1 numeric code`,
    String.raw `ISO 3166-1 alpha-3 code`,
    String.raw `ISO 3166-1 alpha-2 code`,
    String.raw `IOC country code`,
    String.raw `FIPS 10-4 (countries and regions)`,
    String.raw `country calling code`,
    String.raw `Dewey Decimal Classification`,
    String.raw `motto text`,
    String.raw `licence plate code`,
    String.raw `INSEE countries and foreign territories code`,
    String.raw `mobile country code`,
    String.raw `ITU letter code`,
    String.raw `statement is subject of`,
    String.raw `diplomatic mission sent`,
    String.raw `nature of statement`,
    String.raw `title`,
    String.raw `Twitter username`,
    String.raw `official website`,
    String.raw `place of publication`,
    String.raw `reason for deprecation`,
    String.raw `nominee`,
    String.raw `ISNI`,
    String.raw `Instagram username`,
    String.raw `birth name`,
    String.raw `character role`,
    String.raw `for work`,
    String.raw `winner`,
    String.raw `located in the administrative territorial entity`,
    String.raw `review score by`,
    String.raw `FIFA country code`,
    String.raw `official name`,
    String.raw `nickname`,
    String.raw `language of work or name`,
    String.raw `acquisition transaction`,
    String.raw `postal code`,
    String.raw `native label`,
    String.raw `Statistics Canada Geographic code`,
    String.raw `subreddit`,
    String.raw `ISO 3166-2 code`,
    String.raw `Munzinger IBA`,
    String.raw `Libris-URI`,
    String.raw `object has role`,
    String.raw `series ordinal`,
    String.raw `followed by`,
    String.raw `follows`,
    String.raw `exploitation visa number`,
    String.raw `identity of object in context`,
    String.raw `street number`,
    String.raw `located on street`,
    String.raw `pronunciation audio`,
    String.raw `pronunciation variety`,
    String.raw `criterion used`,
    String.raw `GS1 country code`,
    String.raw `UIC numerical country code`,
    String.raw `UIC alphabetical country code`,
    String.raw `trunk prefix`,
    String.raw `detail map`,
    String.raw `CANTIC-ID`,
    String.raw `IPTC Newscode`,
    String.raw `edition number`,
    String.raw `Hornbostel-Sachs classification`,
    String.raw `ACM Classification Code (2012)`,
    String.raw `platform`,
    String.raw `name in native language`,
    String.raw `country`,
    String.raw `NUTS code`,
    String.raw `subject has role`,
    String.raw `Glottolog code`,
    String.raw `WALS lect code`,
    String.raw `ISO 639-2 code`,
    String.raw `ISO 639-1 code`,
    String.raw `Wikimedia language code`,
    String.raw `GOST 7.75–97 code`,
    String.raw `IAB code`,
    String.raw `distribution map`,
    String.raw `IETF language tag`,
    String.raw `ISO 639-3 code`,
    String.raw `has quality`,
    String.raw `Deutsche Synchronkartei actor-ID`,
    String.raw `voice actor`,
    String.raw `located at street address`,
    String.raw `located at street address (DEPRECATED)`,
    String.raw `PermID`,
    String.raw `literal translation`,
    String.raw `FIPS 5-2 alpha code (US states)`,
    String.raw `FIPS 5-2 numeric code (US states)`,
    String.raw `place of marriage`,
    String.raw `replaced by`,
    String.raw `replaces`,
    String.raw `elected in`,
    String.raw `academic degree`,
    String.raw `Name Assigning Authority Number`,
    String.raw `Giphy username`,
    String.raw `WOEID`,
    String.raw `relief location map`,
    String.raw `external data available at`,
    String.raw `license`,
    String.raw `Stack Exchange tag`,
    String.raw `excluding`,
    String.raw `has cause`,
    String.raw `end cause`,
    String.raw `statement disputed by`,
    String.raw `local dialing code`,
    String.raw `Amazon author page`,
    String.raw `pseudonym`,
    String.raw `member of`,
    String.raw `position held`,
    String.raw `academic major`,
    String.raw `main subject`,
    String.raw `Iconclass notation`,
    String.raw `ISCO occupation code`,
    String.raw `Google Doodle`,
    String.raw `FIPS 6-4 (US counties)`,
    String.raw `direction relative to location`,
    String.raw `location`,
    String.raw `applies to name`,
    String.raw `first line`,
    String.raw `Regensburg Classification`,
    String.raw `IPv4 routing prefix`,
    String.raw `ISBN publisher prefix`,
    String.raw `codename`,
    String.raw `ROME Occupation Code (v3)`,
    String.raw `Swedish Anbytarforum`,
    String.raw `foundational text`,
    String.raw `separated from`,
    String.raw `review score`,
    String.raw `ISO 4217 code`,
    String.raw `OSM tag or key`,
    String.raw `inscription`,
    String.raw `valid in period`,
    String.raw `performer`,
    String.raw `sourcing circumstances`,
    String.raw `IPv6 routing prefix`,
    String.raw `British Museum person-institution`,
    String.raw `field of work`,
    String.raw `China administrative division code`,
    String.raw `GitHub username`,
    String.raw `public key fingerprint`,
    String.raw `use`,
    String.raw `official blog`,
    String.raw `IRS Employer Identification Number`,
    String.raw `Corporate Number (Japan)`,
    String.raw `autonomous system number`,
    String.raw `ISIN`,
    String.raw `IPI name number`,
    String.raw `start period`,
    String.raw `Snapchat username`,
    String.raw `spouse`,
    String.raw `named as`,
    String.raw `name`,
    String.raw `ARCHON code`,
    String.raw `together with`,
    String.raw `name in kana`,
    String.raw `M.49 code`,
    String.raw `catchphrase`,
    String.raw `KLfG Critical Dictionary of foreign contemporary literature`,
    String.raw `DiseasesDB`,
    String.raw `ICD-10`,
    String.raw `UMLS CUI`,
    String.raw `ICD-10-CM`,
    String.raw `ICD-9-CM`,
    String.raw `has part`,
    String.raw `proxy`,
    String.raw `type of kinship`,
    String.raw `UK Provider Reference Number`,
    String.raw `DfE URN`,
    String.raw `described by source`,
    String.raw `IPI base code`,
    String.raw `phone number`,
    String.raw `Pinterest username`,
    String.raw `main regulatory text`,
    String.raw `subtitle`,
    String.raw `mapping relation type`,
    String.raw `conflict`,
    String.raw `military branch`,
    String.raw `sRGB color hex triplet`,
    String.raw `stated as`,
    String.raw `video`,
    String.raw `MeSH Code`,
    String.raw `eMedicine`,
    String.raw `Vimeo username`,
    String.raw `National Heritage List for England number`,
    String.raw `BMLO`,
    String.raw `IATA airport code`,
    String.raw `Twitter hashtag`,
    String.raw `nighttime view`,
    String.raw `UN/LOCODE`,
    String.raw `place name sign`,
    String.raw `valid in place`,
    String.raw `destination point`,
    String.raw `start point`,
    String.raw `spoken text audio`,
    String.raw `aircraft registration prefix`,
    String.raw `filming location`,
    String.raw `significant event`,
    String.raw `Linguasphere code`,
    String.raw `Ethnologue.com language code`,
    String.raw `audio recording of the subject's spoken voice`,
    String.raw `transliteration`,
    String.raw `UNDP country code`,
    String.raw `catalog code`,
    String.raw `catalog`,
    String.raw `NRHP reference number`,
    String.raw `applies to jurisdiction`,
    String.raw `award received`,
    String.raw `Wikitribune category`,
    String.raw `Politika topic`,
    String.raw `PhilPapers topic`,
    String.raw `NSDAP membership number (1925–1945)`,
    String.raw `military rank`,
    String.raw `part of`,
    String.raw `contains administrative territorial entity`,
    String.raw `RIA Novosti reference`,
    String.raw `burial plot reference`,
    String.raw `GSS code (2011)`,
    String.raw `day in year for periodic occurrence`,
    String.raw `located on terrain feature`,
    String.raw `Universal Decimal Classification`,
    String.raw `editor`,
    String.raw `weather history`,
    String.raw `direction`,
    String.raw `twinned administrative body`,
    String.raw `organizer`,
    String.raw `author`,
    String.raw `identity of subject in context`,
    String.raw `member of political party`,
    String.raw `dantai code`,
    String.raw `TOID`,
    String.raw `DOI prefix`,
    String.raw `relative to`,
    String.raw `statement supported by`,
    String.raw `schematic`,
    String.raw `operating area`,
    String.raw `UNSPSC Code`,
    String.raw `country of citizenship`,
    String.raw `sport number`,
    String.raw `member of sports team`,
    String.raw `UNII`,
    String.raw `callsign of airline`,
    String.raw `ICAO airline designator`,
    String.raw `airline accounting code`,
    String.raw `Merchant Category Code`,
    String.raw `IATA airline designator`,
    String.raw `Reddit username`,
    String.raw `position played on team / speciality`,
    String.raw `format as a regular expression`,
    String.raw `McCune-Reischauer romanization`,
    String.raw `Revised Romanization`,
    String.raw `parliament.uk biography pages`,
    String.raw `operator`,
    String.raw `OCLC control number`,
    String.raw `CLARA-ID`,
    String.raw `educated at`,
    String.raw `composer`,
    String.raw `pinyin transliteration`,
    String.raw `languages spoken, written or signed`,
    String.raw `ISO standard`,
    String.raw `affiliation`,
    String.raw `headquarters location`,
    String.raw `basic form of government`,
    String.raw `named after`,
    String.raw `INSEE region code`,
    String.raw `SIREN number`,
    String.raw `streaming media URL`,
    String.raw `legislative body`,
    String.raw `ASIN`,
    String.raw `distribution`,
    String.raw `lyrics by`,
    String.raw `married name`,
    String.raw `head of state`,
    String.raw `approved by`,
    String.raw `OS grid reference`,
    String.raw `Austrian municipality key`,
    String.raw `name of the character role`,
    String.raw `present in work`,
    String.raw `doctoral advisor`,
    String.raw `doctoral thesis`,
    String.raw `Charity Commission no.`,
    String.raw `Swedish Literature Bank AuthorID`,
    String.raw `has immediate cause`,
    String.raw `has edition`,
    String.raw `KLG Kritisches Lexikon der Gegenwartsliteratur`,
    String.raw `ICAO airport code`,
    String.raw `runway`,
    String.raw `material used`,
    String.raw `Finnish municipality number`,
    String.raw `of`,
    String.raw `KldB-2010 occupation code`,
    String.raw `Italian cadastre code`,
    String.raw `KulturNav-id`,
    String.raw `Medium username`,
    String.raw `applies to people`,
    String.raw `conferred by`,
    String.raw `Indian census area code (2011)`,
    String.raw `Indian census area code (1991)`,
    String.raw `Indian census area code (2001)`,
    String.raw `ISO 9362 SWIFT/BIC code`,
    String.raw `currency`,
    String.raw `named by`,
    String.raw `image`,
    String.raw `Classification of Instructional Programs code`,
    String.raw `Brazilian municipality code`,
    String.raw `has effect`,
    String.raw `NLC authorities`,
    String.raw `award rationale`,
    String.raw `Munzinger Sport number`,
    String.raw `EPPO Code`,
    String.raw `SPLASH`,
    String.raw `PubChem CID`,
    String.raw `chemical formula`,
    String.raw `chemical structure`,
    String.raw `canonical SMILES`,
    String.raw `EC number`,
    String.raw `CAS Registry Number`,
    String.raw `InChIKey`,
    String.raw `InChI`,
    String.raw `World Health Organisation International Nonproprietary Name`,
    String.raw `USDA NDB number`,
    String.raw `Gmelin number`,
    String.raw `ZVG number`,
    String.raw `Reaxys registry number`,
    String.raw `RxNorm CUI`,
    String.raw `Quora username`,
    String.raw `Biografisch Portaal number`,
    String.raw `medical condition`,
    String.raw `cause of death`,
    String.raw `GOST 7.67 cyrillic`,
    String.raw `publisher`,
    String.raw `KSH code`,
    String.raw `Revised Hepburn romanization`,
    String.raw `Ameblo username`,
    String.raw `heritage designation`,
    String.raw `MCN code`,
    String.raw `writing system`,
    String.raw `e-mail address`,
    String.raw `LAU`,
    String.raw `conscription number`,
    String.raw `last words`,
    String.raw `Cullum number`,
    String.raw `monogram`,
    String.raw `represented by`,
    String.raw `amateur radio callsign`,
    String.raw `LinkedIn personal profile URL`,
    String.raw `German municipality key`,
    String.raw `German regional key`,
    String.raw `German district key`,
    String.raw `subject item of this property`,
    String.raw `IDESCAT territorial code in Catalonia`,
    String.raw `INE municipality code`,
    String.raw `film poster`,
    String.raw `road number`,
    String.raw `draft pick number`,
    String.raw `UAI code`,
    String.raw `SIRET number`,
    String.raw `occupation`,
    String.raw `subclass of`,
    String.raw `IRC channel`,
    String.raw `Irish Grid Reference`,
    String.raw `PCP reference number`,
    String.raw `ICD-9`,
    String.raw `PubMed Health`,
    String.raw `employer`,
    String.raw `based on heuristic`,
    String.raw `penalty`,
    String.raw `court`,
    String.raw `Education Institution Identification Number`,
    String.raw `Library of Congress Classification`,
    String.raw `Quebec municipalities geographical code`,
    String.raw `GS1 Manufacturer code`,
    String.raw `Yahoo Answers category`,
    String.raw `Common Procurement Vocabulary`,
    String.raw `part of the series`,
    String.raw `central bank/issuer`,
    String.raw `GeoNames feature code`,
    String.raw `INSEE department code`,
    String.raw `time period`,
    String.raw `ISO 639-5 code`,
    String.raw `TeX string`,
    String.raw `HTML entity`,
    String.raw `GS1 Global Product Classification brick code`,
    String.raw `GEMS Code`,
    String.raw `United States Armed Forces service number`,
    String.raw `vocalized name`,
    String.raw `Artists in Canada record number`,
    String.raw `Enterprise number (Belgium)`,
    String.raw `Index Herbariorum code`,
    String.raw `ICD-O`,
    String.raw `running mate`,
    String.raw `Dictionary of New Zealand Biography`,
    String.raw `SBC-2010 occupation code`,
    String.raw `ISO 3166-3`,
    String.raw `inventory number`,
    String.raw `DOI`,
    String.raw `instrument`,
    String.raw `ISO 15924 numeric code`,
    String.raw `ISO 15924 alpha-4 code`,
    String.raw `drafted by`,
    String.raw `archival creator authority record at the Archives nationales`,
    String.raw `webcam page URL`,
    String.raw `EU VAT number`,
    String.raw `highest point`,
    String.raw `page(s)`,
    String.raw `quote`,
    String.raw `refine date`,
    String.raw `located in time zone`,
    String.raw `taxon common name`,
    String.raw `ITIS TSN`,
    String.raw `taxon name`,
    String.raw `taxon author`,
    String.raw `GRIN URL`,
    String.raw `CRICOS Provider Code`,
    String.raw `original network`,
    String.raw `SOC Code (2010)`,
    String.raw `donated by`,
    String.raw `manufacturer`,
    String.raw `capital`,
    String.raw `DNB editions`,
    String.raw `Parsons code`,
    String.raw `sport`,
    String.raw `doubles record`,
    String.raw `singles record`,
    String.raw `Telegram username`,
    String.raw `Wikimedia username`,
    String.raw `EThOS thesis ID`,
    String.raw `DBU playerprofile`,
    String.raw `INSEE municipality code`,
    String.raw `E number`,
    String.raw `PictoRight ID-Droit de suite`,
    String.raw `religious order`,
    String.raw `route of administration`,
    String.raw `solvent`,
    String.raw `RTECS number`,
    String.raw `applies to taxon`,
    String.raw `channel number`,
    String.raw `Minitel code`,
    String.raw `element symbol`,
    String.raw `CBS municipality code`,
    String.raw `Amsterdam code`,
    String.raw `fleet or registration number`,
    String.raw `cabinet`,
    String.raw `NBN System Key`,
    String.raw `PlantList-ID`,
    String.raw `Möllendorff transliteration`,
    String.raw `killed by`,
    String.raw `Library of Congress Cultural Heritage Organizations`,
    String.raw `published in`,
    String.raw `Portuguese Job Code CPP-2010`,
    String.raw `RePEc Short-ID`,
    String.raw `ABS ASCL code`,
    String.raw `CVR number`,
    String.raw `addressee`,
    String.raw `ATC code`,
    String.raw `file extension`,
    String.raw `media type`,
    String.raw `MIL-STD-2525 Symbol Identification Code`,
    String.raw `regular expression syntax`,
    String.raw `volume`,
    String.raw `Dictionary of Swedish National Biography`,
    String.raw `mother`,
    String.raw `OLAC video game genre vocabulary`,
    String.raw `Scottish Charity number`,
    String.raw `Catalogus Professorum Halensis`,
    String.raw `appointed by`,
    String.raw `creator`,
    String.raw `tributary orientation`,
    String.raw `genre`,
    String.raw `stated in`,
    String.raw `Biographical Dictionary of Swedish Women`,
    String.raw `Swiss municipality code`,
    String.raw `intended public`,
    String.raw `SIRUTA code`,
    String.raw `WALS family code`,
    String.raw `ISBN-13`,
    String.raw `Swedish municipality code`,
    String.raw `Swedish urban area code`,
    String.raw `Nintendo GameID`,
    String.raw `phase of matter`,
    String.raw `UN number`,
    String.raw `UN class`,
    String.raw `UN packaging group`,
    String.raw `Kemler code`,
    String.raw `SIC code`,
    String.raw `SlideShare username`,
    String.raw `Philippine Standard Geographic Code`,
    String.raw `International Standard Industrial Classification code Rev.4`,
    String.raw `OKPD2 code of the good or service`,
    String.raw `Thailand central administrative unit code`,
    String.raw `sectional view`,
    String.raw `last line`,
    String.raw `different from`,
    String.raw `botanist author abbreviation`,
    String.raw `Gentoo package`,
    String.raw `Fedora package`,
    String.raw `Debian stable package`,
    String.raw `Ubuntu package`,
    String.raw `Arch Linux package`,
    String.raw `parliamentary term`,
    String.raw `Party Number (Taiwan)`,
    String.raw `PO Box`,
    String.raw `Academia.edu profile URL`,
    String.raw `Consolidated code of the electronic catalog of libraries of Belarus`,
    String.raw `item operated`,
    String.raw `located in or next to body of water`,
    String.raw `Nupill Literatura Digital - Author`,
    String.raw `captain`,
    String.raw `FAA airport code`,
    String.raw `bug tracking system`,
    String.raw `Central Index Key`,
    String.raw `Mastodon address`,
    String.raw `directions`,
    String.raw `Australian Business Number`,
    String.raw `EDRPOU code`,
    String.raw `Norwegian organisation number`,
    String.raw `NIS/INS code`,
    String.raw `NACE code`,
    String.raw `British Museum bioID`,
    String.raw `Artsy gene`,
    String.raw `NOC Occupation Code`,
    String.raw `influenced by`,
    String.raw `Danish urban area code`,
    String.raw `DSM-5 classification`,
    String.raw `full work available at`,
    String.raw `said to be the same as`,
    String.raw `Swiss Football Association Club Number`,
    String.raw `spectral class`,
    String.raw `National Bridge Inventory Number`,
    String.raw `UNESCO Biosphere Reserve url`,
    String.raw `Minor Planet Center observatory code`,
    String.raw `ISSN`,
    String.raw `Swedish Organization Number`,
    String.raw `Dreadnought Project page`,
    String.raw `used by`,
    String.raw `CosIng number`,
    String.raw `grammatical gender`,
    String.raw `administrative code of Indonesia`,
    String.raw `lowest point`,
    String.raw `rating`,
    String.raw `WoRMS-ID`,
    String.raw `OpenCorporates corporate grouping`,
    String.raw `author citation (zoology)`,
    String.raw `TA98 Latin term`,
    String.raw `Museofile`,
    String.raw `fax number`,
    String.raw `Bulbapedia article`,
    String.raw `TERYT municipality code`,
    String.raw `ELSTAT geographical code`,
    String.raw `Norwegian municipality number`,
    String.raw `SSR place name number`,
    String.raw `SWB editions`,
    String.raw `native language`,
    String.raw `Wine AppDB-ID`,
    String.raw `AISHE code`,
    String.raw `Code of Household Registration and Conscription Information System (Taiwan)`,
    String.raw `religious name`,
    String.raw `religion`,
    String.raw `location of formation`,
    String.raw `tabular population`,
    String.raw `post town`,
    String.raw `Iranian National Heritage registration number`,
    String.raw `alternate names`,
    String.raw `voice type`,
    String.raw `charter URL`,
    String.raw `Statistics Indonesia ethnicity code`,
    String.raw `Norway Import Service and Registration Authority publisher code`,
    String.raw `Harmonized System Code`,
    String.raw `Australian Company Number`,
    String.raw `Dictionary of Medieval Names from European Sources entry`,
    String.raw `Cologne phonetics`,
    String.raw `Soundex`,
    String.raw `Caverphone`,
    String.raw `ISWC`,
    String.raw `ISBN-10`,
    String.raw `production code`,
    String.raw `depicts Iconclass notation`,
    String.raw `author name string`,
    String.raw `MAME ROM name`,
    String.raw `Sächsische Biografie`,
    String.raw `collection`,
    String.raw `ResearcherID`,
    String.raw `LIBRIS editions`,
    String.raw `operating system`,
    String.raw `snap package`,
    String.raw `call sign`,
    String.raw `IMO ship number`,
    String.raw `yard number`,
    String.raw `Portable Game Notation`,
    String.raw `IIIF manifest`,
    String.raw `Amtrak station code`,
    String.raw `OKPD code of the good or service`,
  ],
};
